# isasmoke.tcl -- GENERATED by scripts/gen_board_prog.py from
# fpga/zc702/isasmoke.hex. Do not edit: re-run the generator instead. The program
# words below are the assembler's output, not a transcription of it.
source [file join [file dirname [info script]] board_env.tcl]
source $LOOM_JTAG_LIB
connect
targets -set -filter {name =~ "xc7z*"}
fpga -file $LOOM_OXC7_DIR/out/lnp64mini_epoch_top.bit
after 2000
puts "ID=[format 0x%08x [rd 0]]"
set h1 [rd 2]; after 200; set h2 [rd 2]
puts "HB_TICKING=[expr {$h2 != $h1}]"
# --- load 58 words at DDR 0x10001000 (DATA_BASE + TEXT_BASE) ---
# addr-8: the auto-increment latches the POST-increment address, so the
# write lands one word later than the address written.
wr 40 [expr {0x10001000 - 8}]; wr 41 0x00000000; wr 42 0x48080000
wr 40 [expr {0x10001008 - 8}]; wr 41 0x0007c000; wr 42 0x48180000
wr 40 [expr {0x10001010 - 8}]; wr 41 0x00000000; wr 42 0x52100000
wr 40 [expr {0x10001018 - 8}]; wr 41 0x00000000; wr 42 0x4a108000
wr 40 [expr {0x10001020 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x10001028 - 8}]; wr 41 0x00000000; wr 42 0x10084400
wr 40 [expr {0x10001030 - 8}]; wr 41 0x00000000; wr 42 0x52100000
wr 40 [expr {0x10001038 - 8}]; wr 41 0x00004000; wr 42 0x4a108000
wr 40 [expr {0x10001040 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x10001048 - 8}]; wr 41 0x00000000; wr 42 0x10084400
wr 40 [expr {0x10001050 - 8}]; wr 41 0x00000000; wr 42 0x52100000
wr 40 [expr {0x10001058 - 8}]; wr 41 0xffffc000; wr 42 0x4a10bfff
wr 40 [expr {0x10001060 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x10001068 - 8}]; wr 41 0x00000000; wr 42 0x10084400
wr 40 [expr {0x10001070 - 8}]; wr 41 0xffffc000; wr 42 0x52103fff
wr 40 [expr {0x10001078 - 8}]; wr 41 0xffffc000; wr 42 0x4a10bfff
wr 40 [expr {0x10001080 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x10001088 - 8}]; wr 41 0x00000000; wr 42 0x10084400
wr 40 [expr {0x10001090 - 8}]; wr 41 0xffffc000; wr 42 0x52101fff
wr 40 [expr {0x10001098 - 8}]; wr 41 0xffffc000; wr 42 0x4a10bfff
wr 40 [expr {0x100010a0 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x100010a8 - 8}]; wr 41 0x00000000; wr 42 0x10084400
wr 40 [expr {0x100010b0 - 8}]; wr 41 0x00000000; wr 42 0x52102000
wr 40 [expr {0x100010b8 - 8}]; wr 41 0x00000000; wr 42 0x4a108000
wr 40 [expr {0x100010c0 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x100010c8 - 8}]; wr 41 0x00000000; wr 42 0x10084400
wr 40 [expr {0x100010d0 - 8}]; wr 41 0x159e0000; wr 42 0x5210048d
wr 40 [expr {0x100010d8 - 8}]; wr 41 0x37bc0000; wr 42 0x4a109eaf
wr 40 [expr {0x100010e0 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x100010e8 - 8}]; wr 41 0x00000000; wr 42 0x10084400
wr 40 [expr {0x100010f0 - 8}]; wr 41 0x3fffc000; wr 42 0x52100000
wr 40 [expr {0x100010f8 - 8}]; wr 41 0xc0000000; wr 42 0x4a10bfff
wr 40 [expr {0x10001100 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x10001108 - 8}]; wr 41 0x00000000; wr 42 0x10084400
wr 40 [expr {0x10001110 - 8}]; wr 41 0x0000c000; wr 42 0x4c208000
wr 40 [expr {0x10001118 - 8}]; wr 41 0x0001c000; wr 42 0x4d288000
wr 40 [expr {0x10001120 - 8}]; wr 41 0x0001c000; wr 42 0x4e308000
wr 40 [expr {0x10001128 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x10001130 - 8}]; wr 41 0x00000000; wr 42 0x10084800
wr 40 [expr {0x10001138 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x10001140 - 8}]; wr 41 0x00000000; wr 42 0x10084a00
wr 40 [expr {0x10001148 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x10001150 - 8}]; wr 41 0x00000000; wr 42 0x10084c00
wr 40 [expr {0x10001158 - 8}]; wr 41 0x00000000; wr 42 0x48380000
wr 40 [expr {0x10001160 - 8}]; wr 41 0x00600000; wr 42 0x61400000
wr 40 [expr {0x10001168 - 8}]; wr 41 0x00190000; wr 42 0x4839c000
wr 40 [expr {0x10001170 - 8}]; wr 41 0x00014000; wr 42 0x48480000
wr 40 [expr {0x10001178 - 8}]; wr 41 0x00004000; wr 42 0x4839c000
wr 40 [expr {0x10001180 - 8}]; wr 41 0xffffc000; wr 42 0x484a7fff
wr 40 [expr {0x10001188 - 8}]; wr 41 0xfffffc00; wr 42 0x640241ff
wr 40 [expr {0x10001190 - 8}]; wr 41 0x00000400; wr 42 0x63024000
wr 40 [expr {0x10001198 - 8}]; wr 41 0x00fa0000; wr 42 0x4839c000
wr 40 [expr {0x100011a0 - 8}]; wr 41 0x00000000; wr 42 0x12084600
wr 40 [expr {0x100011a8 - 8}]; wr 41 0x00000000; wr 42 0x10084e00
wr 40 [expr {0x100011b0 - 8}]; wr 41 0x00020000; wr 42 0x7a000200
wr 40 [expr {0x100011b8 - 8}]; wr 41 0x00000000; wr 42 0xfc000000
wr 40 [expr {0x100011c0 - 8}]; wr 41 0x0001c000; wr 42 0x4839c000
wr 40 [expr {0x100011c8 - 8}]; wr 41 0x00000000; wr 42 0x62020000
# read the first and last word back, so a load that silently did not
# land is reported here rather than as a mystery trap later
wr 40 0x10001000; wr 43 1; after 10
puts "W0=[format 0x%08x%08x [rd 46] [rd 45]]  (want 0x4808000000000000)"
wr 40 0x100011c8; wr 43 1; after 10
puts "WLAST=[format 0x%08x%08x [rd 46] [rd 45]]  (want 0x6202000000000000)"
# --- reset (starts the zeroing sweep), then start ---
wr 13 1
after 300
wr 13 2
for {set i 0} {$i < 200} {incr i} {
  set stx [rd 20]
  if {$stx & 2} break
  after 100
}
puts "STATUS=[format 0x%x [rd 20]]"
puts "RETIRE=[rd 21]"
puts "PC=[rd 22]"
puts "TRAP=[format 0x%x [rd 40]]"
for {set i 1} {$i <= 9} {incr i} {
  wr 14 $i; after 5
  puts "r$i=[expr {([rd 24]<<32) | [rd 23]}]"
}
puts "EXPECT_r1=13739135111232609602"
puts "ISASMOKE_DONE"
