`timescale 1ns/1ps
module tb;
  reg clk=0, rst=1;
  wire [31:0] o_cyc;
  wire [15:0] o_lfsr;
  wire [2:0] o_ptr;
  wire [15:0] o_tmr;
  wire [0:0] o_dma_busy;
  wire [3:0] o_dma_cd;
  wire [31:0] o_injected;
  wire [31:0] o_serviced;
  wire [31:0] o_err;
  wire [31:0] o_maxout;
  wire [31:0] o_dma_sub;
  wire [31:0] o_dma_comp;
  wire [31:0] o_tmr_exp;
  wire [0:0] o_pend0;
  wire [0:0] o_pend1;
  wire [0:0] o_pend2;
  wire [0:0] o_pend3;
  wire [0:0] o_pend4;
  wire [0:0] o_pend5;
  wire [0:0] o_pend6;
  wire [0:0] o_pend7;
  wire [10:0] o_age0;
  wire [10:0] o_age1;
  wire [10:0] o_age2;
  wire [10:0] o_age3;
  wire [10:0] o_age4;
  wire [10:0] o_age5;
  wire [10:0] o_age6;
  wire [10:0] o_age7;
  s13soak dut(.clk(clk), .rst(rst), .o_cyc(o_cyc),.o_lfsr(o_lfsr),.o_ptr(o_ptr),.o_tmr(o_tmr),.o_dma_busy(o_dma_busy),.o_dma_cd(o_dma_cd),.o_injected(o_injected),.o_serviced(o_serviced),.o_err(o_err),.o_maxout(o_maxout),.o_dma_sub(o_dma_sub),.o_dma_comp(o_dma_comp),.o_tmr_exp(o_tmr_exp),.o_pend0(o_pend0),.o_pend1(o_pend1),.o_pend2(o_pend2),.o_pend3(o_pend3),.o_pend4(o_pend4),.o_pend5(o_pend5),.o_pend6(o_pend6),.o_pend7(o_pend7),.o_age0(o_age0),.o_age1(o_age1),.o_age2(o_age2),.o_age3(o_age3),.o_age4(o_age4),.o_age5(o_age5),.o_age6(o_age6),.o_age7(o_age7));
  always #2.5 clk = ~clk;
  integer i;
  initial begin
    @(negedge clk); rst = 0;
    for (i = 0; i < 100100; i = i + 1) @(negedge clk);
    $display("cyc=%0d", o_cyc);
    $display("lfsr=%0d", o_lfsr);
    $display("ptr=%0d", o_ptr);
    $display("tmr=%0d", o_tmr);
    $display("dma_busy=%0d", o_dma_busy);
    $display("dma_cd=%0d", o_dma_cd);
    $display("injected=%0d", o_injected);
    $display("serviced=%0d", o_serviced);
    $display("err=%0d", o_err);
    $display("maxout=%0d", o_maxout);
    $display("dma_sub=%0d", o_dma_sub);
    $display("dma_comp=%0d", o_dma_comp);
    $display("tmr_exp=%0d", o_tmr_exp);
    $display("pend0=%0d", o_pend0);
    $display("pend1=%0d", o_pend1);
    $display("pend2=%0d", o_pend2);
    $display("pend3=%0d", o_pend3);
    $display("pend4=%0d", o_pend4);
    $display("pend5=%0d", o_pend5);
    $display("pend6=%0d", o_pend6);
    $display("pend7=%0d", o_pend7);
    $display("age0=%0d", o_age0);
    $display("age1=%0d", o_age1);
    $display("age2=%0d", o_age2);
    $display("age3=%0d", o_age3);
    $display("age4=%0d", o_age4);
    $display("age5=%0d", o_age5);
    $display("age6=%0d", o_age6);
    $display("age7=%0d", o_age7);
    $finish;
  end
endmodule
