-- Copyright (c) 2026 Kevin Baragona
-- SPDX-License-Identifier: Apache-2.0
import Lake
open Lake DSL

package loom where
  version := v!"0.1.0-dev"
  description := "A proof-carrying processor toolchain and hardware EDSL in Lean 4"
  keywords := #["hardware", "formal-verification", "dsl", "verilog", "processor"]
  license := "Apache-2.0"
  licenseFiles := #["LICENSE", "NOTICE", "Machines/LICENSE"]
  testDriver := "Tests"
  -- The trusted path forbids `native_decide` (Rule 1); nothing here changes kernel options.
  leanOptions := #[
    ⟨`autoImplicit, false⟩,
    ⟨`relaxedAutoImplicit, false⟩
  ]

/-- The machine-generic toolchain. Never imports `Machines` (enforced by
`lake exe audit`). -/
@[default_target]
lean_lib Loom

/-- The machine models: LNP64-µ (the driving use case), LNP64mini (the board
integration vehicle), and smaller genericity examples. -/
@[default_target]
lean_lib Machines

lean_lib Tools

/-- Target profiles and empirical calibrations. This library may depend on
generic Loom APIs, but `Loom` never imports it. -/
lean_lib Evidence

/-- The release witness modules generated by `scripts/gen_release_witness.py`.
Not a default target: only built on demand (by the `parityGate*` exes), after
the release script has generated the sources. -/
lean_lib GeneratedRelease

lean_lib Tests

lean_exe iss where
  root := `Tools.Iss

/-- Compiled LNP64mini emission and architectural selftests. -/
lean_exe minitest where
  root := `Machines.Lnp64mini.Emit
  supportInterpreter := true

lean_exe audit where
  root := `Tools.Audit
  supportInterpreter := true

lean_exe emit where
  supportInterpreter := true
  root := `Tools.Emit

/-- The D38 portability table: which declared memory targets can realize
each shipped design's memories (`Loom/Hw/MemTarget.lean`). -/
lean_exe memtargets where
  supportInterpreter := true
  root := `Tools.MemTargets

/-- W6 cost report: the abstract cost vector per design, plus a calibrated
capacity/closure estimate per target. The report states provenance and
never conflates "it fits" with "the tools will close it". -/
lean_exe costreport where
  supportInterpreter := true
  root := `Tools.CostReport

/-- Per-rule area attribution: which cones the `bitOps` are in. -/
lean_exe areaattrib where
  supportInterpreter := true
  root := `Tools.AreaAttrib

lean_exe iccheck where
  supportInterpreter := true
  root := `Tools.IcCheck

/-- The µVerilog round trip applied to emitted *files*: parse `rtl/X.v`
and require reprinting it to reproduce the bytes. -/
lean_exe rtlroundtrip where
  root := `Tools.RtlRoundTrip

lean_exe bookgen where
  root := `Tools.BookGen

lean_exe actionwidegen where
  root := `Tools.ActionWideGen

lean_exe releaseAudit where
  root := `Tools.ReleaseAudit
  supportInterpreter := true

/-- FastEval benchmark / lockstep runner (compiled; the perf target). -/
lean_exe fastbench where
  root := `Tools.FastEvalBench

/-- Apples-to-apples LNP64mini generated-simulator/hand-ISS benchmark. -/
lean_exe lnpsimbench where
  root := `Tools.Lnp64miniSimBench

/-- Lightweight LNP64mini external BSCAN debug-map generator. -/
lean_exe debugmap where
  root := `Tools.Lnp64miniDebugMap

lean_exe parityGateAcc8 where
  root := `Tools.ParityGateAcc8

lean_exe parityGateLnp64u where
  root := `Tools.ParityGateLnp64u

require mathlib from git
  "https://github.com/leanprover-community/mathlib4" @ "v4.28.0"
