-- Copyright (c) 2026 Kevin Baragona
-- SPDX-License-Identifier: Apache-2.0
import Lake
open Lake DSL

package loom where
  version := v!"0.1.0-dev"
  description := "A proof-carrying processor toolchain and hardware EDSL in Lean 4"
  keywords := #["hardware", "formal-verification", "dsl", "verilog", "processor"]
  license := "Apache-2.0"
  licenseFiles := #["LICENSE", "NOTICE", "Machines/LICENSE"]
  testDriver := "Tests"
  -- The trusted path forbids `native_decide` (Rule 1); nothing here changes kernel options.
  leanOptions := #[
    ⟨`autoImplicit, false⟩,
    ⟨`relaxedAutoImplicit, false⟩
  ]

/-- The machine-generic toolchain. Never imports `Machines` (enforced by
`lake exe audit`). -/
@[default_target]
lean_lib Loom

/-- The machine models: LNP64-µ (the driving use case) and Acc8 (the tiny
pathfinder that keeps the toolchain honest about genericity). -/
@[default_target]
lean_lib Machines

lean_lib Tools

/-- The release witness modules generated by `scripts/gen_release_witness.py`.
Not a default target: only built on demand (by the `parityGate*` exes), after
the release script has generated the sources. -/
lean_lib GeneratedRelease

lean_lib Tests

lean_exe iss where
  root := `Tools.Iss

/-- **Compiled** lnp64mini selftests. `lake env lean --run
Machines/Lnp64mini/Emit.lean <target>` runs the same `main` under the
*interpreter*, where the EDSL≡ISS lockstep costs ~25 minutes per run and
`Design.reset`'s fold over the (six-increment-grown) register list overflows
the interpreter stack outright — `capxferselftest` needed
`ulimit -s unlimited` just to start. Compiled, the same targets run natively.
Use `lake exe minitest <target>`; the interpreted path still works and stays
the reference for `--run`-style one-offs. -/
lean_exe minitest where
  root := `Machines.Lnp64mini.Emit
  supportInterpreter := true

lean_exe audit where
  root := `Tools.Audit
  supportInterpreter := true

lean_exe emit where
  supportInterpreter := true
  root := `Tools.Emit

/-- The D38 portability table: which declared memory targets can realize
each shipped design's memories (`Loom/Hw/MemTarget.lean`). -/
lean_exe memtargets where
  supportInterpreter := true
  root := `Tools.MemTargets

/-- Post-synthesis equivalence checker (D22): µVerilog module vs the
yosys-synthesized netlist, LRAT-certified. -/
lean_exe eqcheck where
  root := `Tools.EqCheck

/-- The µVerilog round trip applied to emitted *files*: parse `rtl/X.v`
and require reprinting it to reproduce the bytes. -/
lean_exe rtlroundtrip where
  root := `Tools.RtlRoundTrip

lean_exe bookgen where
  root := `Tools.BookGen

lean_exe actionwidegen where
  root := `Tools.ActionWideGen

lean_exe releaseAudit where
  root := `Tools.ReleaseAudit
  supportInterpreter := true

/-- FastEval benchmark / lockstep runner (compiled; the perf target). -/
lean_exe fastbench where
  root := `Tools.FastEvalBench

lean_exe parityGateAcc8 where
  root := `Tools.ParityGateAcc8

lean_exe parityGateLnp64u where
  root := `Tools.ParityGateLnp64u

require mathlib from git
  "https://github.com/leanprover-community/mathlib4" @ "v4.28.0"
