-- Copyright (c) 2026 Kevin Baragona
-- SPDX-License-Identifier: Apache-2.0 OR SHL-2.1
import Machines.Lnp64u.Hw.Core
import Machines.Lnp64u.Logic.Inflight
import Machines.Lnp64u.Logic.Hostage
import Machines.Lnp64u.Theorems.RMCAbs

/-!
# R-MC — the LNP64-µ EDSL core refines the ISS

The machine-code refinement theorem: the EDSL core (`Hw.core m`, 1 hardware
cycle = 1 spec cycle) tracks the ISS (`machine m` = `Step.step` iterated)
exactly through the abstraction function `Hw.abs` of `Hw/Enc.lean`. This is
what transports T2–T9 from the ISS onto the emitted Verilog (text side via
the parser round-trip, tool side via the single `ImplementsStandard` axiom).

## The statement is now the *unbounded* lockstep (resolved 2026-07-04)

Until 2026-07-04 the refinement was stated on the `n < 2 ^ 32` horizon,
because the unbounded form was **uninhabited**: `MachineState.cycle` was a
`Nat`, strictly increasing at every spec step, so `machine m` had no
periodic points — while every forward orbit of `(core m).cycle` is
eventually periodic (finitely many declared registers + finite RAM). A
`Simulation.square` is a functional-graph homomorphism and would map a
concrete periodic orbit to a spec periodic orbit; contradiction.

**Resolution (D-class, user decision 2026-07-04): the spec counter is the
hardware counter.** `MachineState.cycle` is now a `BitVec 32` that wraps at
`2 ^ 32` exactly like the RTL register — the `Nat` counter was non-physical.
The proof-forced companion is `Manifest.WF.period_dvd` (`periodP ∣ 2 ^ 32`
per domain): the refill cadence `cycle % P = 0` stays `P`-periodic across
the wrap only under that divisibility — the same constraint real RTOS tick
periods have against a free-running hardware timer. With it, the hidden
mod-`P` counters (`Coupled.rctr_sync`) stay in sync *through* the wrap
(`(2 ^ 32 - 1) + 1 ≡ 0` and `rctr` rolls `P - 1 → 0` simultaneously), so the
old `hwrap` side conditions on `square`/`coupled_step` are gone.

What is stated here, all horizon-free:

* `square` — one core cycle = one spec step through `Hw.abs`, under the
  hidden-state coupling `Coupled`, datapath-fit `Fits`, and reachability on
  both sides. The per-field, per-opcode workhorse.
* `abs_run` (**the R-MC headline**) — for *every* `n`,
  `Hw.abs ((core m).run n reset) = stepN m n m.initState`: exact
  whole-state lockstep from reset, forever — through counter wraps. The
  formal generalization of the 2000-cycle `Tests/Lnp64uCore.lean` run.
* `refines` — the unbounded `Simulation` onto the ISS, with `Hw.abs` as the
  abstraction function, for the core *on its boot orbit* (`reachCore`, the
  same states/reset with the step exercised from reachable states — which
  is every state the powered-on device ever occupies, and reachability
  coincides with `(core m).toTSys`'s, `reachCore_reachable_iff`). The
  restriction is inherent, not a wrap artifact: `square` is conditioned on
  the physical coupling invariant `Coupled` (hidden refill counters in sync,
  canonical encodings), and garbage register files outside the boot orbit
  satisfy neither it nor the range invariants the per-opcode arms need. A
  full-state-space simulation would need a commuting abstraction for
  arbitrary junk states, which carries no verification content — every
  invariant transport already factors through reachable states
  (`invariant_transport`).
* `invariant_transport` — every ISS invariant (T2–T9's currency) holds of
  the abstraction of every core state, at every cycle count. Sorry-free
  given `square`/`coupled_step` (which carry the sorries below).

## Landed support (sorry-free)

* `RMCEnc.lean` — every encoder/decoder round trip (`decKind_encKind`,
  `decRegion_encRegion`, `decRef_encRef`/`encRef_decRef`, `decRun_encRun`,
  `decPerms_encPerms`, `finOfBv_ofNat`).
* `RMCReset.lean` — reset lookups for the 825-register file with a
  symbolic manifest: name distinctness checked in the kernel on a
  precomputed `Nat` key list (no string comparisons), `foldl_set_get`
  (last write wins), `reset_lookup i` (the register's name, width, and
  declared init all reduce definitionally), and `reset_mem`.
* `RMCAbs.lean` — `abs_reset`'s cheap fields: `cycle`, `mem`, `mover`,
  `inflight`, and all four gates; `abs_reset` below is assembled from
  them, so of the reset obligations only `absDom_reset` carries a sorry.

## Remaining work (the sorries), itemized

1. `absDom_reset` — the 548 domain-block lookup arms plus per-field
   decode-of-init case splits. The arm table is generated by
   `scripts/gen_rmc_reset_tab.py` (layout constants documented there) and
   typechecks arm-by-arm, but needs the generator's declList optimization
   before it is CI-affordable; the field assembly then mirrors
   `RMCAbs.absGate_reset` with the `RMCEnc` round trips.
2. `coupled_reset` — same machinery: `rctr = 0 = cycle % P`
   (`reset_drctr` arms), `run ≠ 3` (`reset_drun` arms; boot runs encode as
   `encRun .running = 0`), kind words in encoder image (`reset_dcapV` /
   `reset_dcapKind` arms + `decKind_encKind`).
3. `square` — the big one. Phase decomposition mirroring `Step.step`:
   a. rule-fold characterization: `(core m).cycle σ` as the four rules'
      `Act.run` composition (later writes win);
   b. refill: `refillCondE`/`drctr` vs `cycle % P` (uses `Coupled.rctr_sync`
      and the `effBudgetE` bypass for the charge path);
   c. core, in-flight arm: countdown vs `cyclesLeft - 1`; retirement
      dispatch — per-opcode circuit vs `Isa` exec semantics (25 ops; base
      ops first, mirroring Acc8 `AR.square`'s per-op `simp` pattern, then
      the system ops of `Hw/SysOps.lean`); the `cap_revoke` arm needs the
      pointer-doubling mark-engine correctness (`rv_*` registers converge
      to the spec `marks` closure in ≤ 7 of the 22 rounds) — this forces
      an `rv`-coupling clause into `Coupled` (currently absorbed by the
      concrete-reachability hypothesis `hcr`);
   d. core, idle arm: `schedOrder` fold vs `schedule`'s max-priority fold
      (uses `WF.prio_inj`), `payerE` unrolled walk vs `MachineState.payer`,
      fetch/decode/charge/latch vs the spec issue path;
   e. mover: `SysOps.moverAct`'s pre-cycle re-derivations vs
      `moverPhase ∘ corePhase` (kill sweeps, same-cycle store forwarding);
   f. tick: `cycle + 1`, `BitVec` addition on both sides (wraps identically).
4. `coupled_step` — preservation of `Coupled`: `rctr` increment vs counter
   increment mod `P`, canonical writes (every kind word the circuits write
   is an encoder image), `run` writes ∈ {0,1,2}.

`Coupled` is expected to grow proof-forced clauses (repo pattern); `square`
and `coupled_step` also carry `hcr` (concrete reachability), so clauses
provable from reachability can be added to `Coupled` without weakening the
assembled theorems — `lockstep_coupled` threads reachability on both sides.
-/

namespace Machines.Lnp64u.Theorems.RMC

open Machines.Lnp64u Loom Loom.Hw

/-! ## The coupling invariant and datapath fit -/

/-- Hidden-state / canonical-encoding coupling between a core state and its
abstraction: the register file is in the image of the encoding discipline
`Hw/Enc.lean` fixes, and the hidden refill counters track the cycle
register. (The `cap_revoke` mark-engine coupling is currently supplied by
the concrete-reachability hypothesis of `square`; it becomes a clause here
when the retirement arm forces its exact statement.) -/
structure Coupled (m : Manifest) (σ : Loom.Hw.St) : Prop where
  /-- The hidden per-domain refill counter is `cycle % P` of the *register*
  counter. The two stay in sync *through* the `2 ^ 32` wrap because
  `Manifest.WF.period_dvd` makes `P` divide `2 ^ 32`. -/
  rctr_sync : ∀ d : DomainId,
    (σ.regs (Hw.drctr d) 32).toNat =
      (σ.regs "cycle" 32).toNat % (m.doms d).periodP
  /-- The run state is canonically encoded (`3#2` is decode fallback only;
  the circuits test `= 0`, the spec tests `.running`). -/
  run_canon : ∀ d : DomainId, σ.regs (Hw.drun d) 2 ≠ 3#2
  /-- Every live capability's kind word is in the encoder image (`decKind`
  drops the unused high bits, which the circuits copy verbatim). -/
  kind_canon : ∀ (d : DomainId) (s : Slot), σ.regs (Hw.dcapV d s) 1 = 1#1 →
    Hw.encKind (Hw.decKind (σ.regs (Hw.dcapKind d s) 32)) =
      σ.regs (Hw.dcapKind d s) 32

/-- The manifest's `Nat` scheduling parameters fit the 32-bit datapath
registers that carry them (`budgetQ < 2 ^ 32` follows via `WF.budget_le`).
Vacuous for any realistic manifest; `demoManifest` satisfies it by
`decide`-scale arithmetic. -/
structure Fits (m : Manifest) : Prop where
  period_lt : ∀ d : DomainId, (m.doms d).periodP < 2 ^ 32
  maxdon_lt : ∀ d : DomainId, (m.doms d).maxDonation < 2 ^ 32

/-! ## Reset -/

/-- The domain blocks decode to the boot domain states. Remaining: the
548 domain-block `reset_lookup` arms (`scripts/gen_rmc_reset_tab.py` after
its declList optimization) and the per-field assembly mirroring
`RMCAbs.absGate_reset`: `Option` case splits on the boot value, then the
`RMCEnc` round trips (`decKind_encKind`, `decRegion_encRegion`,
`decRef_encRef`, `decRun_encRun`, `finOfBv_ofNat`); `budget`/`maxDonation`
need `hwf.budget_le` with `hfit` for `Nat.mod_eq_of_lt` under `toNat`. -/
theorem absDom_reset (m : Manifest) (hwf : m.WF) (hfit : Fits m)
    (d : DomainId) :
    Hw.absDom (Hw.core m).reset d = m.initState.doms d := by
  sorry

private theorem machineState_ext {a b : MachineState}
    (h1 : a.cycle = b.cycle) (h2 : a.mem = b.mem) (h3 : a.doms = b.doms)
    (h4 : a.gates = b.gates) (h5 : a.mover = b.mover)
    (h6 : a.inflight = b.inflight) : a = b := by
  cases a; cases b; simp_all

/-- Reset abstracts to boot: decoding the declared reset values recovers
`m.initState` field by field (sorry-free except `absDom_reset`). -/
theorem abs_reset (m : Manifest) (hwf : m.WF) (hfit : Fits m) :
    Hw.abs (Hw.core m).reset = m.initState :=
  machineState_ext (abs_cycle_reset m) (abs_mem_reset m)
    (funext (absDom_reset m hwf hfit)) (funext (absGate_reset m))
    (abs_mover_reset m) (abs_inflight_reset m)

/-- The coupling holds at reset (`cycle = 0`, `rctr = 0 % P`, all encodings
canonical by construction). Remaining: the `reset_drctr`, `reset_drun`,
`reset_dcapV`, and `reset_dcapKind` lookup arms of the generated table. -/
theorem coupled_reset (m : Manifest) : Coupled m (Hw.core m).reset := by
  sorry

/-! ## The commuting square and coupling preservation -/

/-- **The R-MC square**: one core cycle is exactly one spec step through
`Hw.abs`. Hypotheses: manifest WF (scheduler
determinism) and datapath fit, the hidden-state coupling, reachability on
both sides (spec-side range invariants — budgets `≤ Q`, `depth <
maxChainDepth`, `cyclesLeft ≤` max cost, mover regions valid — and the
concrete-side mark-engine state). No wrap side condition: the spec counter
is a `BitVec 32` too, so the tick arm is `cycle + 1` wrapping identically
on both sides. -/
theorem square (m : Manifest) (hwf : m.WF) (hfit : Fits m)
    (σ : Loom.Hw.St)
    (hcpl : Coupled m σ)
    (hcr : ((Hw.core m).toTSys).Reachable σ)
    (hsr : (machine m).Reachable (Hw.abs σ)) :
    Hw.abs ((Hw.core m).cycle σ) = step m (Hw.abs σ) := by
  sorry

/-- The coupling is preserved by one core cycle. At the wrap, `rctr` rolls
`P - 1 → 0` exactly when `cycle` rolls `2 ^ 32 - 1 → 0`, and
`(0 : Nat) % P = 0`; away from it both increment — `WF.period_dvd` is what
makes the two roll-overs coincide. -/
theorem coupled_step (m : Manifest) (hwf : m.WF) (hfit : Fits m)
    (σ : Loom.Hw.St)
    (hcpl : Coupled m σ)
    (hcr : ((Hw.core m).toTSys).Reachable σ)
    (hsr : (machine m).Reachable (Hw.abs σ)) :
    Coupled m ((Hw.core m).cycle σ) := by
  sorry

/-! ## Assembly (sorry-free given the square) -/

/-- `Design.run`'s successor on the right (its definition recurses on the
left). -/
private theorem design_run_succ (dz : Loom.Hw.Design) :
    ∀ (n : Nat) (σ : Loom.Hw.St),
      dz.run (n + 1) σ = dz.cycle (dz.run n σ) := by
  intro n
  induction n with
  | zero => intro σ; rfl
  | succ k ih =>
      intro σ
      show dz.run (k + 1) (dz.cycle σ) = _
      rw [ih (dz.cycle σ)]
      rfl

/-- Spec states along the run from boot are reachable. -/
theorem machine_reachable_stepN (m : Manifest) (n : Nat) :
    (machine m).Reachable (stepN m n m.initState) := by
  induction n with
  | zero => exact .init rfl
  | succ k ih =>
      rw [Wip.stepN_succ]
      exact .step ih rfl

/-- Core states along the run from reset are reachable. -/
theorem core_reachable_run (m : Manifest) (n : Nat) :
    ((Hw.core m).toTSys).Reachable ((Hw.core m).run n (Hw.core m).reset) := by
  induction n with
  | zero => exact .init rfl
  | succ k ih =>
      rw [design_run_succ]
      exact .step ih rfl

/-- The lockstep induction: abstraction equality and coupling, jointly —
for **every** `n`, no horizon. -/
theorem lockstep_coupled (m : Manifest) (hwf : m.WF) (hfit : Fits m) :
    ∀ n : Nat,
      Hw.abs ((Hw.core m).run n (Hw.core m).reset) = stepN m n m.initState ∧
      Coupled m ((Hw.core m).run n (Hw.core m).reset) := by
  intro n
  induction n with
  | zero => exact ⟨abs_reset m hwf hfit, coupled_reset m⟩
  | succ k ih =>
      obtain ⟨habs, hcpl⟩ := ih
      have hcr := core_reachable_run m k
      have hsr : (machine m).Reachable
          (Hw.abs ((Hw.core m).run k (Hw.core m).reset)) := by
        rw [habs]; exact machine_reachable_stepN m k
      refine ⟨?_, ?_⟩
      · rw [design_run_succ, square m hwf hfit _ hcpl hcr hsr, habs,
          Wip.stepN_succ]
      · rw [design_run_succ]
        exact coupled_step m hwf hfit _ hcpl hcr hsr

/-- **R-MC.** Exact whole-state lockstep, **unbounded**: after any `n`
cycles from reset — through any number of counter wraps — decoding the
core's register file yields precisely the ISS state after `n` steps from
boot. (The formal generalization of the `Tests/Lnp64uCore.lean` lockstep
runs; horizon-free since the 2026-07-04 `BitVec 32` cycle decision.) -/
theorem abs_run (m : Manifest) (hwf : m.WF) (hfit : Fits m) (n : Nat) :
    Hw.abs ((Hw.core m).run n (Hw.core m).reset) = stepN m n m.initState :=
  (lockstep_coupled m hwf hfit n).1

/-- **R-MC transport.** Every ISS invariant — in particular each of T2–T9's
invariant forms — holds of the abstraction of every core state, at every
cycle count. This is the theorem that carries the ledger onto the emitted
Verilog. -/
theorem invariant_transport (m : Manifest) (hwf : m.WF) (hfit : Fits m)
    {P : MachineState → Prop} (hP : (machine m).Invariant P)
    (n : Nat) :
    P (Hw.abs ((Hw.core m).run n (Hw.core m).reset)) := by
  rw [abs_run m hwf hfit n]
  exact hP _ (machine_reachable_stepN m n)

/-! ## The unbounded simulation -/

/-- Reachability in a deterministic single-init system is membership in an
indexed run: the generic engine behind `core_reachable_iff` (stated over an
abstract `M` so the `Reachable` recursor applies cleanly). -/
private theorem reachable_index {M : Loom.TSys} {σ : M.S} (h : M.Reachable σ)
    (r : Nat → M.S) (hr0 : ∀ σ₀, M.init σ₀ → σ₀ = r 0)
    (hrs : ∀ a b n, M.step a b → a = r n → b = r (n + 1)) :
    ∃ n, σ = r n := by
  induction h with
  | init h0 => exact ⟨0, hr0 _ h0⟩
  | step _ hs ih =>
      obtain ⟨n, hn⟩ := ih
      exact ⟨n + 1, hrs _ _ n hs hn⟩

/-- Concrete reachability is exactly the boot orbit: the core is
deterministic with the single initial state `reset`. -/
theorem core_reachable_iff (m : Manifest) (σ : Loom.Hw.St) :
    ((Hw.core m).toTSys).Reachable σ ↔
      ∃ n, (Hw.core m).run n (Hw.core m).reset = σ := by
  constructor
  · intro h
    obtain ⟨n, hn⟩ := reachable_index h (fun n => (Hw.core m).run n (Hw.core m).reset)
      (fun σ₀ h0 => h0) (fun a b n hs ha => by
        have ha' : a = (Hw.core m).run n (Hw.core m).reset := ha
        show b = (Hw.core m).run (n + 1) (Hw.core m).reset
        rw [design_run_succ, ← ha']; exact hs.symm)
    exact ⟨n, hn.symm⟩
  · rintro ⟨n, rfl⟩
    exact core_reachable_run m n

/-- The core **on its boot orbit**: same state space, same reset, the step
exercised from reachable states — every state the powered-on device ever
occupies. Its reachable set coincides with `(core m).toTSys`'s
(`reachCore_reachable_iff`), so invariants proved against it are invariants
of the full core. See the module docstring for why the unbounded simulation
lives here and not on arbitrary (garbage) register files. -/
def reachCore (m : Manifest) : Loom.TSys where
  S := Loom.Hw.St
  init := fun σ => σ = (Hw.core m).reset
  step := fun σ σ' =>
    ((Hw.core m).toTSys).Reachable σ ∧ (Hw.core m).cycle σ = σ'

/-- The boot orbit is `reachCore`-reachable. -/
theorem reachCore_reachable_run (m : Manifest) (n : Nat) :
    (reachCore m).Reachable ((Hw.core m).run n (Hw.core m).reset) := by
  induction n with
  | zero => exact .init rfl
  | succ k ih =>
      rw [design_run_succ]
      exact .step ih ⟨core_reachable_run m k, rfl⟩

/-- `reachCore` and the full core system reach exactly the same states. -/
theorem reachCore_reachable_iff (m : Manifest) (σ : Loom.Hw.St) :
    (reachCore m).Reachable σ ↔ ((Hw.core m).toTSys).Reachable σ := by
  constructor
  · intro h
    obtain ⟨n, hn⟩ := reachable_index h (fun n => (Hw.core m).run n (Hw.core m).reset)
      (fun σ₀ h0 => h0) (fun a b n hs ha => by
        have ha' : a = (Hw.core m).run n (Hw.core m).reset := ha
        show b = (Hw.core m).run (n + 1) (Hw.core m).reset
        rw [design_run_succ, ← ha']; exact hs.2.symm)
    rw [hn]
    exact core_reachable_run m n
  · intro h
    obtain ⟨n, hn⟩ := (core_reachable_iff m σ).mp h
    rw [← hn]
    exact reachCore_reachable_run m n

/-- **R-MC (the unbounded simulation).** `Hw.abs` is a genuine
`Simulation` of the ISS by the core on its boot orbit — the project plan's
`Simulation (machine m) (core.toTSys)` restricted to the states the device
can occupy. Inhabited *because* the spec counter now wraps with the
hardware's; with the `Nat` counter this type was provably empty (module
docstring). Sorry-free given `square` and the reset lemmas. -/
theorem refines (m : Manifest) (hwf : m.WF) (hfit : Fits m) :
    Nonempty (Simulation (machine m) (reachCore m)) := by
  refine ⟨{ abs := Hw.abs, init_ok := ?_, square := ?_ }⟩
  · intro σ hσ
    show Hw.abs σ = m.initState
    rw [show σ = (Hw.core m).reset from hσ]
    exact abs_reset m hwf hfit
  · rintro σ σ' ⟨hr, rfl⟩
    obtain ⟨n, rfl⟩ := (core_reachable_iff m σ).mp hr
    show step m _ = _
    rw [← design_run_succ, abs_run m hwf hfit, abs_run m hwf hfit,
      Wip.stepN_succ]

/-- Invariant pullback along the unbounded simulation, restated on the
full core system: any spec invariant holds of the abstraction of every
reachable core state. -/
theorem invariant_pullback (m : Manifest) (hwf : m.WF) (hfit : Fits m)
    {P : MachineState → Prop} (hP : (machine m).Invariant P) :
    ((Hw.core m).toTSys).Invariant (fun σ => P (Hw.abs σ)) := by
  intro σ hσ
  obtain ⟨n, rfl⟩ := (core_reachable_iff m σ).mp hσ
  rw [abs_run m hwf hfit n]
  exact hP _ (machine_reachable_stepN m n)

end Machines.Lnp64u.Theorems.RMC
