-- Copyright (c) 2026 Kevin Baragona
-- SPDX-License-Identifier: Apache-2.0 OR SHL-2.1
import Machines.Lnp64u.Theorems.RMCReset

/-!
# R-MC support: optimized reset declaration list

Generated explicit copy of `Hw.regDecls`. Literal-index reset lookup arms
reduce over this plain list instead of repeatedly unfolding the `flatMap`
construction of `regDecls`.
-/

namespace Machines.Lnp64u.Theorems.RMC

open Machines.Lnp64u Loom.Hw Machines.Lnp64u.Hw

private abbrev D0 : DomainId := ⟨0, by decide⟩
private abbrev D1 : DomainId := ⟨1, by decide⟩
private abbrev D2 : DomainId := ⟨2, by decide⟩
private abbrev D3 : DomainId := ⟨3, by decide⟩
private abbrev R0 : RegId := ⟨0, by decide⟩
private abbrev R1 : RegId := ⟨1, by decide⟩
private abbrev R2 : RegId := ⟨2, by decide⟩
private abbrev R3 : RegId := ⟨3, by decide⟩
private abbrev R4 : RegId := ⟨4, by decide⟩
private abbrev R5 : RegId := ⟨5, by decide⟩
private abbrev R6 : RegId := ⟨6, by decide⟩
private abbrev R7 : RegId := ⟨7, by decide⟩
private abbrev S0 : Slot := ⟨0, by decide⟩
private abbrev S1 : Slot := ⟨1, by decide⟩
private abbrev S2 : Slot := ⟨2, by decide⟩
private abbrev S3 : Slot := ⟨3, by decide⟩
private abbrev S4 : Slot := ⟨4, by decide⟩
private abbrev S5 : Slot := ⟨5, by decide⟩
private abbrev S6 : Slot := ⟨6, by decide⟩
private abbrev S7 : Slot := ⟨7, by decide⟩
private abbrev S8 : Slot := ⟨8, by decide⟩
private abbrev S9 : Slot := ⟨9, by decide⟩
private abbrev S10 : Slot := ⟨10, by decide⟩
private abbrev S11 : Slot := ⟨11, by decide⟩
private abbrev S12 : Slot := ⟨12, by decide⟩
private abbrev S13 : Slot := ⟨13, by decide⟩
private abbrev S14 : Slot := ⟨14, by decide⟩
private abbrev S15 : Slot := ⟨15, by decide⟩
private abbrev L0 : LineageId := ⟨0, by decide⟩
private abbrev L1 : LineageId := ⟨1, by decide⟩
private abbrev L2 : LineageId := ⟨2, by decide⟩
private abbrev L3 : LineageId := ⟨3, by decide⟩
private abbrev L4 : LineageId := ⟨4, by decide⟩
private abbrev L5 : LineageId := ⟨5, by decide⟩
private abbrev L6 : LineageId := ⟨6, by decide⟩
private abbrev L7 : LineageId := ⟨7, by decide⟩
private abbrev L8 : LineageId := ⟨8, by decide⟩
private abbrev L9 : LineageId := ⟨9, by decide⟩
private abbrev L10 : LineageId := ⟨10, by decide⟩
private abbrev L11 : LineageId := ⟨11, by decide⟩
private abbrev L12 : LineageId := ⟨12, by decide⟩
private abbrev L13 : LineageId := ⟨13, by decide⟩
private abbrev L14 : LineageId := ⟨14, by decide⟩
private abbrev L15 : LineageId := ⟨15, by decide⟩
private abbrev G0 : RegionId := ⟨0, by decide⟩
private abbrev G1 : RegionId := ⟨1, by decide⟩
private abbrev G2 : RegionId := ⟨2, by decide⟩
private abbrev G3 : RegionId := ⟨3, by decide⟩
private abbrev Gt0 : GateId := ⟨0, by decide⟩
private abbrev Gt1 : GateId := ⟨1, by decide⟩
private abbrev Gt2 : GateId := ⟨2, by decide⟩
private abbrev Gt3 : GateId := ⟨3, by decide⟩
private abbrev N0 : Hw.NodeId := ⟨0, by decide⟩
private abbrev N1 : Hw.NodeId := ⟨1, by decide⟩
private abbrev N2 : Hw.NodeId := ⟨2, by decide⟩
private abbrev N3 : Hw.NodeId := ⟨3, by decide⟩
private abbrev N4 : Hw.NodeId := ⟨4, by decide⟩
private abbrev N5 : Hw.NodeId := ⟨5, by decide⟩
private abbrev N6 : Hw.NodeId := ⟨6, by decide⟩
private abbrev N7 : Hw.NodeId := ⟨7, by decide⟩
private abbrev N8 : Hw.NodeId := ⟨8, by decide⟩
private abbrev N9 : Hw.NodeId := ⟨9, by decide⟩
private abbrev N10 : Hw.NodeId := ⟨10, by decide⟩
private abbrev N11 : Hw.NodeId := ⟨11, by decide⟩
private abbrev N12 : Hw.NodeId := ⟨12, by decide⟩
private abbrev N13 : Hw.NodeId := ⟨13, by decide⟩
private abbrev N14 : Hw.NodeId := ⟨14, by decide⟩
private abbrev N15 : Hw.NodeId := ⟨15, by decide⟩
private abbrev N16 : Hw.NodeId := ⟨16, by decide⟩
private abbrev N17 : Hw.NodeId := ⟨17, by decide⟩
private abbrev N18 : Hw.NodeId := ⟨18, by decide⟩
private abbrev N19 : Hw.NodeId := ⟨19, by decide⟩
private abbrev N20 : Hw.NodeId := ⟨20, by decide⟩
private abbrev N21 : Hw.NodeId := ⟨21, by decide⟩
private abbrev N22 : Hw.NodeId := ⟨22, by decide⟩
private abbrev N23 : Hw.NodeId := ⟨23, by decide⟩
private abbrev N24 : Hw.NodeId := ⟨24, by decide⟩
private abbrev N25 : Hw.NodeId := ⟨25, by decide⟩
private abbrev N26 : Hw.NodeId := ⟨26, by decide⟩
private abbrev N27 : Hw.NodeId := ⟨27, by decide⟩
private abbrev N28 : Hw.NodeId := ⟨28, by decide⟩
private abbrev N29 : Hw.NodeId := ⟨29, by decide⟩
private abbrev N30 : Hw.NodeId := ⟨30, by decide⟩
private abbrev N31 : Hw.NodeId := ⟨31, by decide⟩
private abbrev N32 : Hw.NodeId := ⟨32, by decide⟩
private abbrev N33 : Hw.NodeId := ⟨33, by decide⟩
private abbrev N34 : Hw.NodeId := ⟨34, by decide⟩
private abbrev N35 : Hw.NodeId := ⟨35, by decide⟩
private abbrev N36 : Hw.NodeId := ⟨36, by decide⟩
private abbrev N37 : Hw.NodeId := ⟨37, by decide⟩
private abbrev N38 : Hw.NodeId := ⟨38, by decide⟩
private abbrev N39 : Hw.NodeId := ⟨39, by decide⟩
private abbrev N40 : Hw.NodeId := ⟨40, by decide⟩
private abbrev N41 : Hw.NodeId := ⟨41, by decide⟩
private abbrev N42 : Hw.NodeId := ⟨42, by decide⟩
private abbrev N43 : Hw.NodeId := ⟨43, by decide⟩
private abbrev N44 : Hw.NodeId := ⟨44, by decide⟩
private abbrev N45 : Hw.NodeId := ⟨45, by decide⟩
private abbrev N46 : Hw.NodeId := ⟨46, by decide⟩
private abbrev N47 : Hw.NodeId := ⟨47, by decide⟩
private abbrev N48 : Hw.NodeId := ⟨48, by decide⟩
private abbrev N49 : Hw.NodeId := ⟨49, by decide⟩
private abbrev N50 : Hw.NodeId := ⟨50, by decide⟩
private abbrev N51 : Hw.NodeId := ⟨51, by decide⟩
private abbrev N52 : Hw.NodeId := ⟨52, by decide⟩
private abbrev N53 : Hw.NodeId := ⟨53, by decide⟩
private abbrev N54 : Hw.NodeId := ⟨54, by decide⟩
private abbrev N55 : Hw.NodeId := ⟨55, by decide⟩
private abbrev N56 : Hw.NodeId := ⟨56, by decide⟩
private abbrev N57 : Hw.NodeId := ⟨57, by decide⟩
private abbrev N58 : Hw.NodeId := ⟨58, by decide⟩
private abbrev N59 : Hw.NodeId := ⟨59, by decide⟩
private abbrev N60 : Hw.NodeId := ⟨60, by decide⟩
private abbrev N61 : Hw.NodeId := ⟨61, by decide⟩
private abbrev N62 : Hw.NodeId := ⟨62, by decide⟩
private abbrev N63 : Hw.NodeId := ⟨63, by decide⟩

/-- The same register declarations as `Hw.regDecls`, but as a literal list. -/
def declList (m : Manifest) : List RegDecl :=
[
  ⟨Hw.dreg D0 R0, 32, ((m.initState.doms D0)).regs R0⟩,
  ⟨Hw.dreg D0 R1, 32, ((m.initState.doms D0)).regs R1⟩,
  ⟨Hw.dreg D0 R2, 32, ((m.initState.doms D0)).regs R2⟩,
  ⟨Hw.dreg D0 R3, 32, ((m.initState.doms D0)).regs R3⟩,
  ⟨Hw.dreg D0 R4, 32, ((m.initState.doms D0)).regs R4⟩,
  ⟨Hw.dreg D0 R5, 32, ((m.initState.doms D0)).regs R5⟩,
  ⟨Hw.dreg D0 R6, 32, ((m.initState.doms D0)).regs R6⟩,
  ⟨Hw.dreg D0 R7, 32, ((m.initState.doms D0)).regs R7⟩,
  ⟨Hw.dpc D0, 12, ((m.initState.doms D0)).pc⟩,
  ⟨Hw.dcapV D0 S0, 1, if (((m.initState.doms D0)).caps S0).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S0, 32, ((((m.initState.doms D0)).caps S0).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S0, 1, if ((((m.initState.doms D0)).caps S0).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S0, 4, (((((m.initState.doms D0)).caps S0).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S0, 8, ((m.initState.doms D0)).slotGen S0⟩,
  ⟨Hw.dcapV D0 S1, 1, if (((m.initState.doms D0)).caps S1).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S1, 32, ((((m.initState.doms D0)).caps S1).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S1, 1, if ((((m.initState.doms D0)).caps S1).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S1, 4, (((((m.initState.doms D0)).caps S1).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S1, 8, ((m.initState.doms D0)).slotGen S1⟩,
  ⟨Hw.dcapV D0 S2, 1, if (((m.initState.doms D0)).caps S2).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S2, 32, ((((m.initState.doms D0)).caps S2).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S2, 1, if ((((m.initState.doms D0)).caps S2).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S2, 4, (((((m.initState.doms D0)).caps S2).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S2, 8, ((m.initState.doms D0)).slotGen S2⟩,
  ⟨Hw.dcapV D0 S3, 1, if (((m.initState.doms D0)).caps S3).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S3, 32, ((((m.initState.doms D0)).caps S3).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S3, 1, if ((((m.initState.doms D0)).caps S3).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S3, 4, (((((m.initState.doms D0)).caps S3).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S3, 8, ((m.initState.doms D0)).slotGen S3⟩,
  ⟨Hw.dcapV D0 S4, 1, if (((m.initState.doms D0)).caps S4).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S4, 32, ((((m.initState.doms D0)).caps S4).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S4, 1, if ((((m.initState.doms D0)).caps S4).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S4, 4, (((((m.initState.doms D0)).caps S4).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S4, 8, ((m.initState.doms D0)).slotGen S4⟩,
  ⟨Hw.dcapV D0 S5, 1, if (((m.initState.doms D0)).caps S5).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S5, 32, ((((m.initState.doms D0)).caps S5).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S5, 1, if ((((m.initState.doms D0)).caps S5).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S5, 4, (((((m.initState.doms D0)).caps S5).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S5, 8, ((m.initState.doms D0)).slotGen S5⟩,
  ⟨Hw.dcapV D0 S6, 1, if (((m.initState.doms D0)).caps S6).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S6, 32, ((((m.initState.doms D0)).caps S6).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S6, 1, if ((((m.initState.doms D0)).caps S6).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S6, 4, (((((m.initState.doms D0)).caps S6).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S6, 8, ((m.initState.doms D0)).slotGen S6⟩,
  ⟨Hw.dcapV D0 S7, 1, if (((m.initState.doms D0)).caps S7).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S7, 32, ((((m.initState.doms D0)).caps S7).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S7, 1, if ((((m.initState.doms D0)).caps S7).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S7, 4, (((((m.initState.doms D0)).caps S7).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S7, 8, ((m.initState.doms D0)).slotGen S7⟩,
  ⟨Hw.dcapV D0 S8, 1, if (((m.initState.doms D0)).caps S8).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S8, 32, ((((m.initState.doms D0)).caps S8).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S8, 1, if ((((m.initState.doms D0)).caps S8).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S8, 4, (((((m.initState.doms D0)).caps S8).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S8, 8, ((m.initState.doms D0)).slotGen S8⟩,
  ⟨Hw.dcapV D0 S9, 1, if (((m.initState.doms D0)).caps S9).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S9, 32, ((((m.initState.doms D0)).caps S9).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S9, 1, if ((((m.initState.doms D0)).caps S9).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S9, 4, (((((m.initState.doms D0)).caps S9).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S9, 8, ((m.initState.doms D0)).slotGen S9⟩,
  ⟨Hw.dcapV D0 S10, 1, if (((m.initState.doms D0)).caps S10).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S10, 32, ((((m.initState.doms D0)).caps S10).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S10, 1, if ((((m.initState.doms D0)).caps S10).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S10, 4, (((((m.initState.doms D0)).caps S10).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S10, 8, ((m.initState.doms D0)).slotGen S10⟩,
  ⟨Hw.dcapV D0 S11, 1, if (((m.initState.doms D0)).caps S11).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S11, 32, ((((m.initState.doms D0)).caps S11).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S11, 1, if ((((m.initState.doms D0)).caps S11).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S11, 4, (((((m.initState.doms D0)).caps S11).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S11, 8, ((m.initState.doms D0)).slotGen S11⟩,
  ⟨Hw.dcapV D0 S12, 1, if (((m.initState.doms D0)).caps S12).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S12, 32, ((((m.initState.doms D0)).caps S12).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S12, 1, if ((((m.initState.doms D0)).caps S12).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S12, 4, (((((m.initState.doms D0)).caps S12).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S12, 8, ((m.initState.doms D0)).slotGen S12⟩,
  ⟨Hw.dcapV D0 S13, 1, if (((m.initState.doms D0)).caps S13).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S13, 32, ((((m.initState.doms D0)).caps S13).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S13, 1, if ((((m.initState.doms D0)).caps S13).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S13, 4, (((((m.initState.doms D0)).caps S13).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S13, 8, ((m.initState.doms D0)).slotGen S13⟩,
  ⟨Hw.dcapV D0 S14, 1, if (((m.initState.doms D0)).caps S14).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S14, 32, ((((m.initState.doms D0)).caps S14).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S14, 1, if ((((m.initState.doms D0)).caps S14).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S14, 4, (((((m.initState.doms D0)).caps S14).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S14, 8, ((m.initState.doms D0)).slotGen S14⟩,
  ⟨Hw.dcapV D0 S15, 1, if (((m.initState.doms D0)).caps S15).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D0 S15, 32, ((((m.initState.doms D0)).caps S15).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D0 S15, 1, if ((((m.initState.doms D0)).caps S15).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D0 S15, 4, (((((m.initState.doms D0)).caps S15).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D0 S15, 8, ((m.initState.doms D0)).slotGen S15⟩,
  ⟨Hw.dcellV D0 L0, 1, if (((m.initState.doms D0)).lineage L0).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L0, 14, ((((m.initState.doms D0)).lineage L0).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L1, 1, if (((m.initState.doms D0)).lineage L1).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L1, 14, ((((m.initState.doms D0)).lineage L1).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L2, 1, if (((m.initState.doms D0)).lineage L2).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L2, 14, ((((m.initState.doms D0)).lineage L2).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L3, 1, if (((m.initState.doms D0)).lineage L3).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L3, 14, ((((m.initState.doms D0)).lineage L3).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L4, 1, if (((m.initState.doms D0)).lineage L4).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L4, 14, ((((m.initState.doms D0)).lineage L4).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L5, 1, if (((m.initState.doms D0)).lineage L5).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L5, 14, ((((m.initState.doms D0)).lineage L5).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L6, 1, if (((m.initState.doms D0)).lineage L6).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L6, 14, ((((m.initState.doms D0)).lineage L6).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L7, 1, if (((m.initState.doms D0)).lineage L7).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L7, 14, ((((m.initState.doms D0)).lineage L7).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L8, 1, if (((m.initState.doms D0)).lineage L8).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L8, 14, ((((m.initState.doms D0)).lineage L8).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L9, 1, if (((m.initState.doms D0)).lineage L9).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L9, 14, ((((m.initState.doms D0)).lineage L9).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L10, 1, if (((m.initState.doms D0)).lineage L10).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L10, 14, ((((m.initState.doms D0)).lineage L10).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L11, 1, if (((m.initState.doms D0)).lineage L11).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L11, 14, ((((m.initState.doms D0)).lineage L11).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L12, 1, if (((m.initState.doms D0)).lineage L12).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L12, 14, ((((m.initState.doms D0)).lineage L12).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L13, 1, if (((m.initState.doms D0)).lineage L13).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L13, 14, ((((m.initState.doms D0)).lineage L13).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L14, 1, if (((m.initState.doms D0)).lineage L14).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L14, 14, ((((m.initState.doms D0)).lineage L14).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D0 L15, 1, if (((m.initState.doms D0)).lineage L15).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D0 L15, 14, ((((m.initState.doms D0)).lineage L15).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.drgnV D0 G0, 1, if (((m.initState.doms D0)).regions G0).isSome then 1 else 0⟩,
  ⟨Hw.drgn D0 G0, 42, ((((m.initState.doms D0)).regions G0).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D0 G1, 1, if (((m.initState.doms D0)).regions G1).isSome then 1 else 0⟩,
  ⟨Hw.drgn D0 G1, 42, ((((m.initState.doms D0)).regions G1).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D0 G2, 1, if (((m.initState.doms D0)).regions G2).isSome then 1 else 0⟩,
  ⟨Hw.drgn D0 G2, 42, ((((m.initState.doms D0)).regions G2).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D0 G3, 1, if (((m.initState.doms D0)).regions G3).isSome then 1 else 0⟩,
  ⟨Hw.drgn D0 G3, 42, ((((m.initState.doms D0)).regions G3).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drun D0, 2, Hw.encRun ((m.initState.doms D0)).run⟩,
  ⟨Hw.drunG D0, 2, Hw.encRunG ((m.initState.doms D0)).run⟩,
  ⟨Hw.dsrvV D0, 1, if ((m.initState.doms D0)).serving.isSome then 1 else 0⟩,
  ⟨Hw.dsrv D0, 2, (((m.initState.doms D0)).serving.map fun g => BitVec.ofNat 2 g.val).getD 0⟩,
  ⟨Hw.dcause D0, 32, ((m.initState.doms D0)).cause⟩,
  ⟨Hw.dbudget D0, 32, BitVec.ofNat 32 ((m.initState.doms D0)).budget⟩,
  ⟨Hw.dmaxdon D0, 32, BitVec.ofNat 32 ((m.initState.doms D0)).maxDonation⟩,
  ⟨Hw.drctr D0, 32, BitVec.ofNat 32 (m.initState.cycle.toNat % (m.doms D0).periodP)⟩,
  ⟨Hw.dreg D1 R0, 32, ((m.initState.doms D1)).regs R0⟩,
  ⟨Hw.dreg D1 R1, 32, ((m.initState.doms D1)).regs R1⟩,
  ⟨Hw.dreg D1 R2, 32, ((m.initState.doms D1)).regs R2⟩,
  ⟨Hw.dreg D1 R3, 32, ((m.initState.doms D1)).regs R3⟩,
  ⟨Hw.dreg D1 R4, 32, ((m.initState.doms D1)).regs R4⟩,
  ⟨Hw.dreg D1 R5, 32, ((m.initState.doms D1)).regs R5⟩,
  ⟨Hw.dreg D1 R6, 32, ((m.initState.doms D1)).regs R6⟩,
  ⟨Hw.dreg D1 R7, 32, ((m.initState.doms D1)).regs R7⟩,
  ⟨Hw.dpc D1, 12, ((m.initState.doms D1)).pc⟩,
  ⟨Hw.dcapV D1 S0, 1, if (((m.initState.doms D1)).caps S0).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S0, 32, ((((m.initState.doms D1)).caps S0).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S0, 1, if ((((m.initState.doms D1)).caps S0).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S0, 4, (((((m.initState.doms D1)).caps S0).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S0, 8, ((m.initState.doms D1)).slotGen S0⟩,
  ⟨Hw.dcapV D1 S1, 1, if (((m.initState.doms D1)).caps S1).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S1, 32, ((((m.initState.doms D1)).caps S1).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S1, 1, if ((((m.initState.doms D1)).caps S1).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S1, 4, (((((m.initState.doms D1)).caps S1).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S1, 8, ((m.initState.doms D1)).slotGen S1⟩,
  ⟨Hw.dcapV D1 S2, 1, if (((m.initState.doms D1)).caps S2).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S2, 32, ((((m.initState.doms D1)).caps S2).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S2, 1, if ((((m.initState.doms D1)).caps S2).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S2, 4, (((((m.initState.doms D1)).caps S2).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S2, 8, ((m.initState.doms D1)).slotGen S2⟩,
  ⟨Hw.dcapV D1 S3, 1, if (((m.initState.doms D1)).caps S3).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S3, 32, ((((m.initState.doms D1)).caps S3).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S3, 1, if ((((m.initState.doms D1)).caps S3).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S3, 4, (((((m.initState.doms D1)).caps S3).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S3, 8, ((m.initState.doms D1)).slotGen S3⟩,
  ⟨Hw.dcapV D1 S4, 1, if (((m.initState.doms D1)).caps S4).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S4, 32, ((((m.initState.doms D1)).caps S4).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S4, 1, if ((((m.initState.doms D1)).caps S4).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S4, 4, (((((m.initState.doms D1)).caps S4).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S4, 8, ((m.initState.doms D1)).slotGen S4⟩,
  ⟨Hw.dcapV D1 S5, 1, if (((m.initState.doms D1)).caps S5).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S5, 32, ((((m.initState.doms D1)).caps S5).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S5, 1, if ((((m.initState.doms D1)).caps S5).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S5, 4, (((((m.initState.doms D1)).caps S5).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S5, 8, ((m.initState.doms D1)).slotGen S5⟩,
  ⟨Hw.dcapV D1 S6, 1, if (((m.initState.doms D1)).caps S6).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S6, 32, ((((m.initState.doms D1)).caps S6).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S6, 1, if ((((m.initState.doms D1)).caps S6).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S6, 4, (((((m.initState.doms D1)).caps S6).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S6, 8, ((m.initState.doms D1)).slotGen S6⟩,
  ⟨Hw.dcapV D1 S7, 1, if (((m.initState.doms D1)).caps S7).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S7, 32, ((((m.initState.doms D1)).caps S7).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S7, 1, if ((((m.initState.doms D1)).caps S7).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S7, 4, (((((m.initState.doms D1)).caps S7).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S7, 8, ((m.initState.doms D1)).slotGen S7⟩,
  ⟨Hw.dcapV D1 S8, 1, if (((m.initState.doms D1)).caps S8).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S8, 32, ((((m.initState.doms D1)).caps S8).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S8, 1, if ((((m.initState.doms D1)).caps S8).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S8, 4, (((((m.initState.doms D1)).caps S8).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S8, 8, ((m.initState.doms D1)).slotGen S8⟩,
  ⟨Hw.dcapV D1 S9, 1, if (((m.initState.doms D1)).caps S9).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S9, 32, ((((m.initState.doms D1)).caps S9).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S9, 1, if ((((m.initState.doms D1)).caps S9).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S9, 4, (((((m.initState.doms D1)).caps S9).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S9, 8, ((m.initState.doms D1)).slotGen S9⟩,
  ⟨Hw.dcapV D1 S10, 1, if (((m.initState.doms D1)).caps S10).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S10, 32, ((((m.initState.doms D1)).caps S10).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S10, 1, if ((((m.initState.doms D1)).caps S10).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S10, 4, (((((m.initState.doms D1)).caps S10).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S10, 8, ((m.initState.doms D1)).slotGen S10⟩,
  ⟨Hw.dcapV D1 S11, 1, if (((m.initState.doms D1)).caps S11).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S11, 32, ((((m.initState.doms D1)).caps S11).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S11, 1, if ((((m.initState.doms D1)).caps S11).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S11, 4, (((((m.initState.doms D1)).caps S11).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S11, 8, ((m.initState.doms D1)).slotGen S11⟩,
  ⟨Hw.dcapV D1 S12, 1, if (((m.initState.doms D1)).caps S12).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S12, 32, ((((m.initState.doms D1)).caps S12).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S12, 1, if ((((m.initState.doms D1)).caps S12).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S12, 4, (((((m.initState.doms D1)).caps S12).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S12, 8, ((m.initState.doms D1)).slotGen S12⟩,
  ⟨Hw.dcapV D1 S13, 1, if (((m.initState.doms D1)).caps S13).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S13, 32, ((((m.initState.doms D1)).caps S13).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S13, 1, if ((((m.initState.doms D1)).caps S13).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S13, 4, (((((m.initState.doms D1)).caps S13).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S13, 8, ((m.initState.doms D1)).slotGen S13⟩,
  ⟨Hw.dcapV D1 S14, 1, if (((m.initState.doms D1)).caps S14).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S14, 32, ((((m.initState.doms D1)).caps S14).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S14, 1, if ((((m.initState.doms D1)).caps S14).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S14, 4, (((((m.initState.doms D1)).caps S14).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S14, 8, ((m.initState.doms D1)).slotGen S14⟩,
  ⟨Hw.dcapV D1 S15, 1, if (((m.initState.doms D1)).caps S15).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D1 S15, 32, ((((m.initState.doms D1)).caps S15).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D1 S15, 1, if ((((m.initState.doms D1)).caps S15).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D1 S15, 4, (((((m.initState.doms D1)).caps S15).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D1 S15, 8, ((m.initState.doms D1)).slotGen S15⟩,
  ⟨Hw.dcellV D1 L0, 1, if (((m.initState.doms D1)).lineage L0).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L0, 14, ((((m.initState.doms D1)).lineage L0).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L1, 1, if (((m.initState.doms D1)).lineage L1).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L1, 14, ((((m.initState.doms D1)).lineage L1).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L2, 1, if (((m.initState.doms D1)).lineage L2).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L2, 14, ((((m.initState.doms D1)).lineage L2).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L3, 1, if (((m.initState.doms D1)).lineage L3).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L3, 14, ((((m.initState.doms D1)).lineage L3).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L4, 1, if (((m.initState.doms D1)).lineage L4).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L4, 14, ((((m.initState.doms D1)).lineage L4).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L5, 1, if (((m.initState.doms D1)).lineage L5).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L5, 14, ((((m.initState.doms D1)).lineage L5).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L6, 1, if (((m.initState.doms D1)).lineage L6).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L6, 14, ((((m.initState.doms D1)).lineage L6).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L7, 1, if (((m.initState.doms D1)).lineage L7).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L7, 14, ((((m.initState.doms D1)).lineage L7).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L8, 1, if (((m.initState.doms D1)).lineage L8).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L8, 14, ((((m.initState.doms D1)).lineage L8).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L9, 1, if (((m.initState.doms D1)).lineage L9).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L9, 14, ((((m.initState.doms D1)).lineage L9).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L10, 1, if (((m.initState.doms D1)).lineage L10).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L10, 14, ((((m.initState.doms D1)).lineage L10).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L11, 1, if (((m.initState.doms D1)).lineage L11).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L11, 14, ((((m.initState.doms D1)).lineage L11).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L12, 1, if (((m.initState.doms D1)).lineage L12).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L12, 14, ((((m.initState.doms D1)).lineage L12).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L13, 1, if (((m.initState.doms D1)).lineage L13).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L13, 14, ((((m.initState.doms D1)).lineage L13).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L14, 1, if (((m.initState.doms D1)).lineage L14).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L14, 14, ((((m.initState.doms D1)).lineage L14).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D1 L15, 1, if (((m.initState.doms D1)).lineage L15).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D1 L15, 14, ((((m.initState.doms D1)).lineage L15).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.drgnV D1 G0, 1, if (((m.initState.doms D1)).regions G0).isSome then 1 else 0⟩,
  ⟨Hw.drgn D1 G0, 42, ((((m.initState.doms D1)).regions G0).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D1 G1, 1, if (((m.initState.doms D1)).regions G1).isSome then 1 else 0⟩,
  ⟨Hw.drgn D1 G1, 42, ((((m.initState.doms D1)).regions G1).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D1 G2, 1, if (((m.initState.doms D1)).regions G2).isSome then 1 else 0⟩,
  ⟨Hw.drgn D1 G2, 42, ((((m.initState.doms D1)).regions G2).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D1 G3, 1, if (((m.initState.doms D1)).regions G3).isSome then 1 else 0⟩,
  ⟨Hw.drgn D1 G3, 42, ((((m.initState.doms D1)).regions G3).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drun D1, 2, Hw.encRun ((m.initState.doms D1)).run⟩,
  ⟨Hw.drunG D1, 2, Hw.encRunG ((m.initState.doms D1)).run⟩,
  ⟨Hw.dsrvV D1, 1, if ((m.initState.doms D1)).serving.isSome then 1 else 0⟩,
  ⟨Hw.dsrv D1, 2, (((m.initState.doms D1)).serving.map fun g => BitVec.ofNat 2 g.val).getD 0⟩,
  ⟨Hw.dcause D1, 32, ((m.initState.doms D1)).cause⟩,
  ⟨Hw.dbudget D1, 32, BitVec.ofNat 32 ((m.initState.doms D1)).budget⟩,
  ⟨Hw.dmaxdon D1, 32, BitVec.ofNat 32 ((m.initState.doms D1)).maxDonation⟩,
  ⟨Hw.drctr D1, 32, BitVec.ofNat 32 (m.initState.cycle.toNat % (m.doms D1).periodP)⟩,
  ⟨Hw.dreg D2 R0, 32, ((m.initState.doms D2)).regs R0⟩,
  ⟨Hw.dreg D2 R1, 32, ((m.initState.doms D2)).regs R1⟩,
  ⟨Hw.dreg D2 R2, 32, ((m.initState.doms D2)).regs R2⟩,
  ⟨Hw.dreg D2 R3, 32, ((m.initState.doms D2)).regs R3⟩,
  ⟨Hw.dreg D2 R4, 32, ((m.initState.doms D2)).regs R4⟩,
  ⟨Hw.dreg D2 R5, 32, ((m.initState.doms D2)).regs R5⟩,
  ⟨Hw.dreg D2 R6, 32, ((m.initState.doms D2)).regs R6⟩,
  ⟨Hw.dreg D2 R7, 32, ((m.initState.doms D2)).regs R7⟩,
  ⟨Hw.dpc D2, 12, ((m.initState.doms D2)).pc⟩,
  ⟨Hw.dcapV D2 S0, 1, if (((m.initState.doms D2)).caps S0).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S0, 32, ((((m.initState.doms D2)).caps S0).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S0, 1, if ((((m.initState.doms D2)).caps S0).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S0, 4, (((((m.initState.doms D2)).caps S0).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S0, 8, ((m.initState.doms D2)).slotGen S0⟩,
  ⟨Hw.dcapV D2 S1, 1, if (((m.initState.doms D2)).caps S1).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S1, 32, ((((m.initState.doms D2)).caps S1).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S1, 1, if ((((m.initState.doms D2)).caps S1).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S1, 4, (((((m.initState.doms D2)).caps S1).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S1, 8, ((m.initState.doms D2)).slotGen S1⟩,
  ⟨Hw.dcapV D2 S2, 1, if (((m.initState.doms D2)).caps S2).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S2, 32, ((((m.initState.doms D2)).caps S2).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S2, 1, if ((((m.initState.doms D2)).caps S2).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S2, 4, (((((m.initState.doms D2)).caps S2).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S2, 8, ((m.initState.doms D2)).slotGen S2⟩,
  ⟨Hw.dcapV D2 S3, 1, if (((m.initState.doms D2)).caps S3).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S3, 32, ((((m.initState.doms D2)).caps S3).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S3, 1, if ((((m.initState.doms D2)).caps S3).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S3, 4, (((((m.initState.doms D2)).caps S3).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S3, 8, ((m.initState.doms D2)).slotGen S3⟩,
  ⟨Hw.dcapV D2 S4, 1, if (((m.initState.doms D2)).caps S4).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S4, 32, ((((m.initState.doms D2)).caps S4).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S4, 1, if ((((m.initState.doms D2)).caps S4).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S4, 4, (((((m.initState.doms D2)).caps S4).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S4, 8, ((m.initState.doms D2)).slotGen S4⟩,
  ⟨Hw.dcapV D2 S5, 1, if (((m.initState.doms D2)).caps S5).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S5, 32, ((((m.initState.doms D2)).caps S5).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S5, 1, if ((((m.initState.doms D2)).caps S5).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S5, 4, (((((m.initState.doms D2)).caps S5).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S5, 8, ((m.initState.doms D2)).slotGen S5⟩,
  ⟨Hw.dcapV D2 S6, 1, if (((m.initState.doms D2)).caps S6).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S6, 32, ((((m.initState.doms D2)).caps S6).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S6, 1, if ((((m.initState.doms D2)).caps S6).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S6, 4, (((((m.initState.doms D2)).caps S6).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S6, 8, ((m.initState.doms D2)).slotGen S6⟩,
  ⟨Hw.dcapV D2 S7, 1, if (((m.initState.doms D2)).caps S7).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S7, 32, ((((m.initState.doms D2)).caps S7).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S7, 1, if ((((m.initState.doms D2)).caps S7).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S7, 4, (((((m.initState.doms D2)).caps S7).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S7, 8, ((m.initState.doms D2)).slotGen S7⟩,
  ⟨Hw.dcapV D2 S8, 1, if (((m.initState.doms D2)).caps S8).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S8, 32, ((((m.initState.doms D2)).caps S8).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S8, 1, if ((((m.initState.doms D2)).caps S8).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S8, 4, (((((m.initState.doms D2)).caps S8).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S8, 8, ((m.initState.doms D2)).slotGen S8⟩,
  ⟨Hw.dcapV D2 S9, 1, if (((m.initState.doms D2)).caps S9).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S9, 32, ((((m.initState.doms D2)).caps S9).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S9, 1, if ((((m.initState.doms D2)).caps S9).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S9, 4, (((((m.initState.doms D2)).caps S9).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S9, 8, ((m.initState.doms D2)).slotGen S9⟩,
  ⟨Hw.dcapV D2 S10, 1, if (((m.initState.doms D2)).caps S10).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S10, 32, ((((m.initState.doms D2)).caps S10).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S10, 1, if ((((m.initState.doms D2)).caps S10).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S10, 4, (((((m.initState.doms D2)).caps S10).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S10, 8, ((m.initState.doms D2)).slotGen S10⟩,
  ⟨Hw.dcapV D2 S11, 1, if (((m.initState.doms D2)).caps S11).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S11, 32, ((((m.initState.doms D2)).caps S11).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S11, 1, if ((((m.initState.doms D2)).caps S11).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S11, 4, (((((m.initState.doms D2)).caps S11).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S11, 8, ((m.initState.doms D2)).slotGen S11⟩,
  ⟨Hw.dcapV D2 S12, 1, if (((m.initState.doms D2)).caps S12).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S12, 32, ((((m.initState.doms D2)).caps S12).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S12, 1, if ((((m.initState.doms D2)).caps S12).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S12, 4, (((((m.initState.doms D2)).caps S12).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S12, 8, ((m.initState.doms D2)).slotGen S12⟩,
  ⟨Hw.dcapV D2 S13, 1, if (((m.initState.doms D2)).caps S13).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S13, 32, ((((m.initState.doms D2)).caps S13).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S13, 1, if ((((m.initState.doms D2)).caps S13).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S13, 4, (((((m.initState.doms D2)).caps S13).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S13, 8, ((m.initState.doms D2)).slotGen S13⟩,
  ⟨Hw.dcapV D2 S14, 1, if (((m.initState.doms D2)).caps S14).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S14, 32, ((((m.initState.doms D2)).caps S14).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S14, 1, if ((((m.initState.doms D2)).caps S14).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S14, 4, (((((m.initState.doms D2)).caps S14).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S14, 8, ((m.initState.doms D2)).slotGen S14⟩,
  ⟨Hw.dcapV D2 S15, 1, if (((m.initState.doms D2)).caps S15).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D2 S15, 32, ((((m.initState.doms D2)).caps S15).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D2 S15, 1, if ((((m.initState.doms D2)).caps S15).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D2 S15, 4, (((((m.initState.doms D2)).caps S15).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D2 S15, 8, ((m.initState.doms D2)).slotGen S15⟩,
  ⟨Hw.dcellV D2 L0, 1, if (((m.initState.doms D2)).lineage L0).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L0, 14, ((((m.initState.doms D2)).lineage L0).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L1, 1, if (((m.initState.doms D2)).lineage L1).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L1, 14, ((((m.initState.doms D2)).lineage L1).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L2, 1, if (((m.initState.doms D2)).lineage L2).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L2, 14, ((((m.initState.doms D2)).lineage L2).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L3, 1, if (((m.initState.doms D2)).lineage L3).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L3, 14, ((((m.initState.doms D2)).lineage L3).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L4, 1, if (((m.initState.doms D2)).lineage L4).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L4, 14, ((((m.initState.doms D2)).lineage L4).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L5, 1, if (((m.initState.doms D2)).lineage L5).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L5, 14, ((((m.initState.doms D2)).lineage L5).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L6, 1, if (((m.initState.doms D2)).lineage L6).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L6, 14, ((((m.initState.doms D2)).lineage L6).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L7, 1, if (((m.initState.doms D2)).lineage L7).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L7, 14, ((((m.initState.doms D2)).lineage L7).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L8, 1, if (((m.initState.doms D2)).lineage L8).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L8, 14, ((((m.initState.doms D2)).lineage L8).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L9, 1, if (((m.initState.doms D2)).lineage L9).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L9, 14, ((((m.initState.doms D2)).lineage L9).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L10, 1, if (((m.initState.doms D2)).lineage L10).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L10, 14, ((((m.initState.doms D2)).lineage L10).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L11, 1, if (((m.initState.doms D2)).lineage L11).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L11, 14, ((((m.initState.doms D2)).lineage L11).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L12, 1, if (((m.initState.doms D2)).lineage L12).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L12, 14, ((((m.initState.doms D2)).lineage L12).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L13, 1, if (((m.initState.doms D2)).lineage L13).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L13, 14, ((((m.initState.doms D2)).lineage L13).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L14, 1, if (((m.initState.doms D2)).lineage L14).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L14, 14, ((((m.initState.doms D2)).lineage L14).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D2 L15, 1, if (((m.initState.doms D2)).lineage L15).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D2 L15, 14, ((((m.initState.doms D2)).lineage L15).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.drgnV D2 G0, 1, if (((m.initState.doms D2)).regions G0).isSome then 1 else 0⟩,
  ⟨Hw.drgn D2 G0, 42, ((((m.initState.doms D2)).regions G0).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D2 G1, 1, if (((m.initState.doms D2)).regions G1).isSome then 1 else 0⟩,
  ⟨Hw.drgn D2 G1, 42, ((((m.initState.doms D2)).regions G1).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D2 G2, 1, if (((m.initState.doms D2)).regions G2).isSome then 1 else 0⟩,
  ⟨Hw.drgn D2 G2, 42, ((((m.initState.doms D2)).regions G2).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D2 G3, 1, if (((m.initState.doms D2)).regions G3).isSome then 1 else 0⟩,
  ⟨Hw.drgn D2 G3, 42, ((((m.initState.doms D2)).regions G3).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drun D2, 2, Hw.encRun ((m.initState.doms D2)).run⟩,
  ⟨Hw.drunG D2, 2, Hw.encRunG ((m.initState.doms D2)).run⟩,
  ⟨Hw.dsrvV D2, 1, if ((m.initState.doms D2)).serving.isSome then 1 else 0⟩,
  ⟨Hw.dsrv D2, 2, (((m.initState.doms D2)).serving.map fun g => BitVec.ofNat 2 g.val).getD 0⟩,
  ⟨Hw.dcause D2, 32, ((m.initState.doms D2)).cause⟩,
  ⟨Hw.dbudget D2, 32, BitVec.ofNat 32 ((m.initState.doms D2)).budget⟩,
  ⟨Hw.dmaxdon D2, 32, BitVec.ofNat 32 ((m.initState.doms D2)).maxDonation⟩,
  ⟨Hw.drctr D2, 32, BitVec.ofNat 32 (m.initState.cycle.toNat % (m.doms D2).periodP)⟩,
  ⟨Hw.dreg D3 R0, 32, ((m.initState.doms D3)).regs R0⟩,
  ⟨Hw.dreg D3 R1, 32, ((m.initState.doms D3)).regs R1⟩,
  ⟨Hw.dreg D3 R2, 32, ((m.initState.doms D3)).regs R2⟩,
  ⟨Hw.dreg D3 R3, 32, ((m.initState.doms D3)).regs R3⟩,
  ⟨Hw.dreg D3 R4, 32, ((m.initState.doms D3)).regs R4⟩,
  ⟨Hw.dreg D3 R5, 32, ((m.initState.doms D3)).regs R5⟩,
  ⟨Hw.dreg D3 R6, 32, ((m.initState.doms D3)).regs R6⟩,
  ⟨Hw.dreg D3 R7, 32, ((m.initState.doms D3)).regs R7⟩,
  ⟨Hw.dpc D3, 12, ((m.initState.doms D3)).pc⟩,
  ⟨Hw.dcapV D3 S0, 1, if (((m.initState.doms D3)).caps S0).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S0, 32, ((((m.initState.doms D3)).caps S0).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S0, 1, if ((((m.initState.doms D3)).caps S0).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S0, 4, (((((m.initState.doms D3)).caps S0).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S0, 8, ((m.initState.doms D3)).slotGen S0⟩,
  ⟨Hw.dcapV D3 S1, 1, if (((m.initState.doms D3)).caps S1).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S1, 32, ((((m.initState.doms D3)).caps S1).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S1, 1, if ((((m.initState.doms D3)).caps S1).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S1, 4, (((((m.initState.doms D3)).caps S1).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S1, 8, ((m.initState.doms D3)).slotGen S1⟩,
  ⟨Hw.dcapV D3 S2, 1, if (((m.initState.doms D3)).caps S2).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S2, 32, ((((m.initState.doms D3)).caps S2).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S2, 1, if ((((m.initState.doms D3)).caps S2).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S2, 4, (((((m.initState.doms D3)).caps S2).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S2, 8, ((m.initState.doms D3)).slotGen S2⟩,
  ⟨Hw.dcapV D3 S3, 1, if (((m.initState.doms D3)).caps S3).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S3, 32, ((((m.initState.doms D3)).caps S3).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S3, 1, if ((((m.initState.doms D3)).caps S3).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S3, 4, (((((m.initState.doms D3)).caps S3).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S3, 8, ((m.initState.doms D3)).slotGen S3⟩,
  ⟨Hw.dcapV D3 S4, 1, if (((m.initState.doms D3)).caps S4).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S4, 32, ((((m.initState.doms D3)).caps S4).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S4, 1, if ((((m.initState.doms D3)).caps S4).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S4, 4, (((((m.initState.doms D3)).caps S4).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S4, 8, ((m.initState.doms D3)).slotGen S4⟩,
  ⟨Hw.dcapV D3 S5, 1, if (((m.initState.doms D3)).caps S5).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S5, 32, ((((m.initState.doms D3)).caps S5).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S5, 1, if ((((m.initState.doms D3)).caps S5).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S5, 4, (((((m.initState.doms D3)).caps S5).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S5, 8, ((m.initState.doms D3)).slotGen S5⟩,
  ⟨Hw.dcapV D3 S6, 1, if (((m.initState.doms D3)).caps S6).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S6, 32, ((((m.initState.doms D3)).caps S6).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S6, 1, if ((((m.initState.doms D3)).caps S6).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S6, 4, (((((m.initState.doms D3)).caps S6).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S6, 8, ((m.initState.doms D3)).slotGen S6⟩,
  ⟨Hw.dcapV D3 S7, 1, if (((m.initState.doms D3)).caps S7).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S7, 32, ((((m.initState.doms D3)).caps S7).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S7, 1, if ((((m.initState.doms D3)).caps S7).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S7, 4, (((((m.initState.doms D3)).caps S7).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S7, 8, ((m.initState.doms D3)).slotGen S7⟩,
  ⟨Hw.dcapV D3 S8, 1, if (((m.initState.doms D3)).caps S8).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S8, 32, ((((m.initState.doms D3)).caps S8).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S8, 1, if ((((m.initState.doms D3)).caps S8).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S8, 4, (((((m.initState.doms D3)).caps S8).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S8, 8, ((m.initState.doms D3)).slotGen S8⟩,
  ⟨Hw.dcapV D3 S9, 1, if (((m.initState.doms D3)).caps S9).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S9, 32, ((((m.initState.doms D3)).caps S9).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S9, 1, if ((((m.initState.doms D3)).caps S9).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S9, 4, (((((m.initState.doms D3)).caps S9).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S9, 8, ((m.initState.doms D3)).slotGen S9⟩,
  ⟨Hw.dcapV D3 S10, 1, if (((m.initState.doms D3)).caps S10).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S10, 32, ((((m.initState.doms D3)).caps S10).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S10, 1, if ((((m.initState.doms D3)).caps S10).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S10, 4, (((((m.initState.doms D3)).caps S10).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S10, 8, ((m.initState.doms D3)).slotGen S10⟩,
  ⟨Hw.dcapV D3 S11, 1, if (((m.initState.doms D3)).caps S11).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S11, 32, ((((m.initState.doms D3)).caps S11).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S11, 1, if ((((m.initState.doms D3)).caps S11).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S11, 4, (((((m.initState.doms D3)).caps S11).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S11, 8, ((m.initState.doms D3)).slotGen S11⟩,
  ⟨Hw.dcapV D3 S12, 1, if (((m.initState.doms D3)).caps S12).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S12, 32, ((((m.initState.doms D3)).caps S12).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S12, 1, if ((((m.initState.doms D3)).caps S12).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S12, 4, (((((m.initState.doms D3)).caps S12).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S12, 8, ((m.initState.doms D3)).slotGen S12⟩,
  ⟨Hw.dcapV D3 S13, 1, if (((m.initState.doms D3)).caps S13).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S13, 32, ((((m.initState.doms D3)).caps S13).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S13, 1, if ((((m.initState.doms D3)).caps S13).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S13, 4, (((((m.initState.doms D3)).caps S13).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S13, 8, ((m.initState.doms D3)).slotGen S13⟩,
  ⟨Hw.dcapV D3 S14, 1, if (((m.initState.doms D3)).caps S14).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S14, 32, ((((m.initState.doms D3)).caps S14).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S14, 1, if ((((m.initState.doms D3)).caps S14).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S14, 4, (((((m.initState.doms D3)).caps S14).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S14, 8, ((m.initState.doms D3)).slotGen S14⟩,
  ⟨Hw.dcapV D3 S15, 1, if (((m.initState.doms D3)).caps S15).isSome then 1 else 0⟩,
  ⟨Hw.dcapKind D3 S15, 32, ((((m.initState.doms D3)).caps S15).map fun c => Hw.encKind c.kind).getD 0⟩,
  ⟨Hw.dcapLinV D3 S15, 1, if ((((m.initState.doms D3)).caps S15).bind (·.lineage)).isSome then 1 else 0⟩,
  ⟨Hw.dcapLin D3 S15, 4, (((((m.initState.doms D3)).caps S15).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0⟩,
  ⟨Hw.dgen D3 S15, 8, ((m.initState.doms D3)).slotGen S15⟩,
  ⟨Hw.dcellV D3 L0, 1, if (((m.initState.doms D3)).lineage L0).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L0, 14, ((((m.initState.doms D3)).lineage L0).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L1, 1, if (((m.initState.doms D3)).lineage L1).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L1, 14, ((((m.initState.doms D3)).lineage L1).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L2, 1, if (((m.initState.doms D3)).lineage L2).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L2, 14, ((((m.initState.doms D3)).lineage L2).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L3, 1, if (((m.initState.doms D3)).lineage L3).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L3, 14, ((((m.initState.doms D3)).lineage L3).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L4, 1, if (((m.initState.doms D3)).lineage L4).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L4, 14, ((((m.initState.doms D3)).lineage L4).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L5, 1, if (((m.initState.doms D3)).lineage L5).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L5, 14, ((((m.initState.doms D3)).lineage L5).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L6, 1, if (((m.initState.doms D3)).lineage L6).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L6, 14, ((((m.initState.doms D3)).lineage L6).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L7, 1, if (((m.initState.doms D3)).lineage L7).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L7, 14, ((((m.initState.doms D3)).lineage L7).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L8, 1, if (((m.initState.doms D3)).lineage L8).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L8, 14, ((((m.initState.doms D3)).lineage L8).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L9, 1, if (((m.initState.doms D3)).lineage L9).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L9, 14, ((((m.initState.doms D3)).lineage L9).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L10, 1, if (((m.initState.doms D3)).lineage L10).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L10, 14, ((((m.initState.doms D3)).lineage L10).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L11, 1, if (((m.initState.doms D3)).lineage L11).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L11, 14, ((((m.initState.doms D3)).lineage L11).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L12, 1, if (((m.initState.doms D3)).lineage L12).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L12, 14, ((((m.initState.doms D3)).lineage L12).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L13, 1, if (((m.initState.doms D3)).lineage L13).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L13, 14, ((((m.initState.doms D3)).lineage L13).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L14, 1, if (((m.initState.doms D3)).lineage L14).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L14, 14, ((((m.initState.doms D3)).lineage L14).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.dcellV D3 L15, 1, if (((m.initState.doms D3)).lineage L15).isSome then 1 else 0⟩,
  ⟨Hw.dcellPar D3 L15, 14, ((((m.initState.doms D3)).lineage L15).map fun c => Hw.encRef c.parent).getD 0⟩,
  ⟨Hw.drgnV D3 G0, 1, if (((m.initState.doms D3)).regions G0).isSome then 1 else 0⟩,
  ⟨Hw.drgn D3 G0, 42, ((((m.initState.doms D3)).regions G0).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D3 G1, 1, if (((m.initState.doms D3)).regions G1).isSome then 1 else 0⟩,
  ⟨Hw.drgn D3 G1, 42, ((((m.initState.doms D3)).regions G1).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D3 G2, 1, if (((m.initState.doms D3)).regions G2).isSome then 1 else 0⟩,
  ⟨Hw.drgn D3 G2, 42, ((((m.initState.doms D3)).regions G2).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drgnV D3 G3, 1, if (((m.initState.doms D3)).regions G3).isSome then 1 else 0⟩,
  ⟨Hw.drgn D3 G3, 42, ((((m.initState.doms D3)).regions G3).map Hw.encRegion).getD 0⟩,
  ⟨Hw.drun D3, 2, Hw.encRun ((m.initState.doms D3)).run⟩,
  ⟨Hw.drunG D3, 2, Hw.encRunG ((m.initState.doms D3)).run⟩,
  ⟨Hw.dsrvV D3, 1, if ((m.initState.doms D3)).serving.isSome then 1 else 0⟩,
  ⟨Hw.dsrv D3, 2, (((m.initState.doms D3)).serving.map fun g => BitVec.ofNat 2 g.val).getD 0⟩,
  ⟨Hw.dcause D3, 32, ((m.initState.doms D3)).cause⟩,
  ⟨Hw.dbudget D3, 32, BitVec.ofNat 32 ((m.initState.doms D3)).budget⟩,
  ⟨Hw.dmaxdon D3, 32, BitVec.ofNat 32 ((m.initState.doms D3)).maxDonation⟩,
  ⟨Hw.drctr D3, 32, BitVec.ofNat 32 (m.initState.cycle.toNat % (m.doms D3).periodP)⟩,
  ⟨Hw.gcallee Gt0, 2, BitVec.ofNat 2 ((m.initState.gates Gt0)).config.callee.val⟩,
  ⟨Hw.gentry Gt0, 12, ((m.initState.gates Gt0)).config.entry⟩,
  ⟨Hw.gactV Gt0, 1, if ((m.initState.gates Gt0)).act.isSome then 1 else 0⟩,
  ⟨Hw.gcaller Gt0, 2, (((m.initState.gates Gt0)).act.map fun x => BitVec.ofNat 2 x.caller.val).getD 0⟩,
  ⟨Hw.gcallerRd Gt0, 3, (((m.initState.gates Gt0)).act.map fun x => BitVec.ofNat 3 x.callerRd.val).getD 0⟩,
  ⟨Hw.gsreg Gt0 R0, 32, (((m.initState.gates Gt0)).act.map fun x => x.savedRegs R0).getD 0⟩,
  ⟨Hw.gsreg Gt0 R1, 32, (((m.initState.gates Gt0)).act.map fun x => x.savedRegs R1).getD 0⟩,
  ⟨Hw.gsreg Gt0 R2, 32, (((m.initState.gates Gt0)).act.map fun x => x.savedRegs R2).getD 0⟩,
  ⟨Hw.gsreg Gt0 R3, 32, (((m.initState.gates Gt0)).act.map fun x => x.savedRegs R3).getD 0⟩,
  ⟨Hw.gsreg Gt0 R4, 32, (((m.initState.gates Gt0)).act.map fun x => x.savedRegs R4).getD 0⟩,
  ⟨Hw.gsreg Gt0 R5, 32, (((m.initState.gates Gt0)).act.map fun x => x.savedRegs R5).getD 0⟩,
  ⟨Hw.gsreg Gt0 R6, 32, (((m.initState.gates Gt0)).act.map fun x => x.savedRegs R6).getD 0⟩,
  ⟨Hw.gsreg Gt0 R7, 32, (((m.initState.gates Gt0)).act.map fun x => x.savedRegs R7).getD 0⟩,
  ⟨Hw.gspc Gt0, 12, (((m.initState.gates Gt0)).act.map (·.savedPc)).getD 0⟩,
  ⟨Hw.gssrvV Gt0, 1, if (((m.initState.gates Gt0)).act.bind (·.savedServing)).isSome then 1 else 0⟩,
  ⟨Hw.gssrv Gt0, 2, ((((m.initState.gates Gt0)).act.bind (·.savedServing)).map fun x => BitVec.ofNat 2 x.val).getD 0⟩,
  ⟨Hw.gdepth Gt0, 3, (((m.initState.gates Gt0)).act.map fun x => BitVec.ofNat 3 x.depth).getD 0⟩,
  ⟨Hw.gdon Gt0, 32, (((m.initState.gates Gt0)).act.map fun x => BitVec.ofNat 32 x.donated).getD 0⟩,
  ⟨Hw.gcallee Gt1, 2, BitVec.ofNat 2 ((m.initState.gates Gt1)).config.callee.val⟩,
  ⟨Hw.gentry Gt1, 12, ((m.initState.gates Gt1)).config.entry⟩,
  ⟨Hw.gactV Gt1, 1, if ((m.initState.gates Gt1)).act.isSome then 1 else 0⟩,
  ⟨Hw.gcaller Gt1, 2, (((m.initState.gates Gt1)).act.map fun x => BitVec.ofNat 2 x.caller.val).getD 0⟩,
  ⟨Hw.gcallerRd Gt1, 3, (((m.initState.gates Gt1)).act.map fun x => BitVec.ofNat 3 x.callerRd.val).getD 0⟩,
  ⟨Hw.gsreg Gt1 R0, 32, (((m.initState.gates Gt1)).act.map fun x => x.savedRegs R0).getD 0⟩,
  ⟨Hw.gsreg Gt1 R1, 32, (((m.initState.gates Gt1)).act.map fun x => x.savedRegs R1).getD 0⟩,
  ⟨Hw.gsreg Gt1 R2, 32, (((m.initState.gates Gt1)).act.map fun x => x.savedRegs R2).getD 0⟩,
  ⟨Hw.gsreg Gt1 R3, 32, (((m.initState.gates Gt1)).act.map fun x => x.savedRegs R3).getD 0⟩,
  ⟨Hw.gsreg Gt1 R4, 32, (((m.initState.gates Gt1)).act.map fun x => x.savedRegs R4).getD 0⟩,
  ⟨Hw.gsreg Gt1 R5, 32, (((m.initState.gates Gt1)).act.map fun x => x.savedRegs R5).getD 0⟩,
  ⟨Hw.gsreg Gt1 R6, 32, (((m.initState.gates Gt1)).act.map fun x => x.savedRegs R6).getD 0⟩,
  ⟨Hw.gsreg Gt1 R7, 32, (((m.initState.gates Gt1)).act.map fun x => x.savedRegs R7).getD 0⟩,
  ⟨Hw.gspc Gt1, 12, (((m.initState.gates Gt1)).act.map (·.savedPc)).getD 0⟩,
  ⟨Hw.gssrvV Gt1, 1, if (((m.initState.gates Gt1)).act.bind (·.savedServing)).isSome then 1 else 0⟩,
  ⟨Hw.gssrv Gt1, 2, ((((m.initState.gates Gt1)).act.bind (·.savedServing)).map fun x => BitVec.ofNat 2 x.val).getD 0⟩,
  ⟨Hw.gdepth Gt1, 3, (((m.initState.gates Gt1)).act.map fun x => BitVec.ofNat 3 x.depth).getD 0⟩,
  ⟨Hw.gdon Gt1, 32, (((m.initState.gates Gt1)).act.map fun x => BitVec.ofNat 32 x.donated).getD 0⟩,
  ⟨Hw.gcallee Gt2, 2, BitVec.ofNat 2 ((m.initState.gates Gt2)).config.callee.val⟩,
  ⟨Hw.gentry Gt2, 12, ((m.initState.gates Gt2)).config.entry⟩,
  ⟨Hw.gactV Gt2, 1, if ((m.initState.gates Gt2)).act.isSome then 1 else 0⟩,
  ⟨Hw.gcaller Gt2, 2, (((m.initState.gates Gt2)).act.map fun x => BitVec.ofNat 2 x.caller.val).getD 0⟩,
  ⟨Hw.gcallerRd Gt2, 3, (((m.initState.gates Gt2)).act.map fun x => BitVec.ofNat 3 x.callerRd.val).getD 0⟩,
  ⟨Hw.gsreg Gt2 R0, 32, (((m.initState.gates Gt2)).act.map fun x => x.savedRegs R0).getD 0⟩,
  ⟨Hw.gsreg Gt2 R1, 32, (((m.initState.gates Gt2)).act.map fun x => x.savedRegs R1).getD 0⟩,
  ⟨Hw.gsreg Gt2 R2, 32, (((m.initState.gates Gt2)).act.map fun x => x.savedRegs R2).getD 0⟩,
  ⟨Hw.gsreg Gt2 R3, 32, (((m.initState.gates Gt2)).act.map fun x => x.savedRegs R3).getD 0⟩,
  ⟨Hw.gsreg Gt2 R4, 32, (((m.initState.gates Gt2)).act.map fun x => x.savedRegs R4).getD 0⟩,
  ⟨Hw.gsreg Gt2 R5, 32, (((m.initState.gates Gt2)).act.map fun x => x.savedRegs R5).getD 0⟩,
  ⟨Hw.gsreg Gt2 R6, 32, (((m.initState.gates Gt2)).act.map fun x => x.savedRegs R6).getD 0⟩,
  ⟨Hw.gsreg Gt2 R7, 32, (((m.initState.gates Gt2)).act.map fun x => x.savedRegs R7).getD 0⟩,
  ⟨Hw.gspc Gt2, 12, (((m.initState.gates Gt2)).act.map (·.savedPc)).getD 0⟩,
  ⟨Hw.gssrvV Gt2, 1, if (((m.initState.gates Gt2)).act.bind (·.savedServing)).isSome then 1 else 0⟩,
  ⟨Hw.gssrv Gt2, 2, ((((m.initState.gates Gt2)).act.bind (·.savedServing)).map fun x => BitVec.ofNat 2 x.val).getD 0⟩,
  ⟨Hw.gdepth Gt2, 3, (((m.initState.gates Gt2)).act.map fun x => BitVec.ofNat 3 x.depth).getD 0⟩,
  ⟨Hw.gdon Gt2, 32, (((m.initState.gates Gt2)).act.map fun x => BitVec.ofNat 32 x.donated).getD 0⟩,
  ⟨Hw.gcallee Gt3, 2, BitVec.ofNat 2 ((m.initState.gates Gt3)).config.callee.val⟩,
  ⟨Hw.gentry Gt3, 12, ((m.initState.gates Gt3)).config.entry⟩,
  ⟨Hw.gactV Gt3, 1, if ((m.initState.gates Gt3)).act.isSome then 1 else 0⟩,
  ⟨Hw.gcaller Gt3, 2, (((m.initState.gates Gt3)).act.map fun x => BitVec.ofNat 2 x.caller.val).getD 0⟩,
  ⟨Hw.gcallerRd Gt3, 3, (((m.initState.gates Gt3)).act.map fun x => BitVec.ofNat 3 x.callerRd.val).getD 0⟩,
  ⟨Hw.gsreg Gt3 R0, 32, (((m.initState.gates Gt3)).act.map fun x => x.savedRegs R0).getD 0⟩,
  ⟨Hw.gsreg Gt3 R1, 32, (((m.initState.gates Gt3)).act.map fun x => x.savedRegs R1).getD 0⟩,
  ⟨Hw.gsreg Gt3 R2, 32, (((m.initState.gates Gt3)).act.map fun x => x.savedRegs R2).getD 0⟩,
  ⟨Hw.gsreg Gt3 R3, 32, (((m.initState.gates Gt3)).act.map fun x => x.savedRegs R3).getD 0⟩,
  ⟨Hw.gsreg Gt3 R4, 32, (((m.initState.gates Gt3)).act.map fun x => x.savedRegs R4).getD 0⟩,
  ⟨Hw.gsreg Gt3 R5, 32, (((m.initState.gates Gt3)).act.map fun x => x.savedRegs R5).getD 0⟩,
  ⟨Hw.gsreg Gt3 R6, 32, (((m.initState.gates Gt3)).act.map fun x => x.savedRegs R6).getD 0⟩,
  ⟨Hw.gsreg Gt3 R7, 32, (((m.initState.gates Gt3)).act.map fun x => x.savedRegs R7).getD 0⟩,
  ⟨Hw.gspc Gt3, 12, (((m.initState.gates Gt3)).act.map (·.savedPc)).getD 0⟩,
  ⟨Hw.gssrvV Gt3, 1, if (((m.initState.gates Gt3)).act.bind (·.savedServing)).isSome then 1 else 0⟩,
  ⟨Hw.gssrv Gt3, 2, ((((m.initState.gates Gt3)).act.bind (·.savedServing)).map fun x => BitVec.ofNat 2 x.val).getD 0⟩,
  ⟨Hw.gdepth Gt3, 3, (((m.initState.gates Gt3)).act.map fun x => BitVec.ofNat 3 x.depth).getD 0⟩,
  ⟨Hw.gdon Gt3, 32, (((m.initState.gates Gt3)).act.map fun x => BitVec.ofNat 32 x.donated).getD 0⟩,
  ⟨"mov_v", 1, if m.initState.mover.isSome then 1 else 0⟩,
  ⟨"mov_src", 14, (m.initState.mover.map fun x => Hw.encRef x.src).getD 0⟩,
  ⟨"mov_dst", 14, (m.initState.mover.map fun x => Hw.encRef x.dst).getD 0⟩,
  ⟨"mov_srccur", 12, (m.initState.mover.map (·.srcCur)).getD 0⟩,
  ⟨"mov_dstcur", 12, (m.initState.mover.map (·.dstCur)).getD 0⟩,
  ⟨"mov_rem", 13, (m.initState.mover.map fun x => BitVec.ofNat 13 x.remaining).getD 0⟩,
  ⟨"mov_owner", 2, (m.initState.mover.map fun x => BitVec.ofNat 2 x.owner.val).getD 0⟩,
  ⟨"mov_status", 12, (m.initState.mover.map (·.statusAddr)).getD 0⟩,
  ⟨"if_v", 1, if m.initState.inflight.isSome then 1 else 0⟩,
  ⟨"if_dom", 2, (m.initState.inflight.map fun x => BitVec.ofNat 2 x.dom.val).getD 0⟩,
  ⟨"if_word", 32, (m.initState.inflight.map (·.word)).getD 0⟩,
  ⟨"if_cl", 8, (m.initState.inflight.map fun x => BitVec.ofNat 8 x.cyclesLeft).getD 0⟩,
  ⟨"cycle", 32, m.initState.cycle⟩,
  ⟨Hw.rvJ N0, 6, 0⟩,
  ⟨Hw.rvV N0, 1, 0⟩,
  ⟨Hw.rvR N0, 1, 0⟩,
  ⟨Hw.rvJ N1, 6, 0⟩,
  ⟨Hw.rvV N1, 1, 0⟩,
  ⟨Hw.rvR N1, 1, 0⟩,
  ⟨Hw.rvJ N2, 6, 0⟩,
  ⟨Hw.rvV N2, 1, 0⟩,
  ⟨Hw.rvR N2, 1, 0⟩,
  ⟨Hw.rvJ N3, 6, 0⟩,
  ⟨Hw.rvV N3, 1, 0⟩,
  ⟨Hw.rvR N3, 1, 0⟩,
  ⟨Hw.rvJ N4, 6, 0⟩,
  ⟨Hw.rvV N4, 1, 0⟩,
  ⟨Hw.rvR N4, 1, 0⟩,
  ⟨Hw.rvJ N5, 6, 0⟩,
  ⟨Hw.rvV N5, 1, 0⟩,
  ⟨Hw.rvR N5, 1, 0⟩,
  ⟨Hw.rvJ N6, 6, 0⟩,
  ⟨Hw.rvV N6, 1, 0⟩,
  ⟨Hw.rvR N6, 1, 0⟩,
  ⟨Hw.rvJ N7, 6, 0⟩,
  ⟨Hw.rvV N7, 1, 0⟩,
  ⟨Hw.rvR N7, 1, 0⟩,
  ⟨Hw.rvJ N8, 6, 0⟩,
  ⟨Hw.rvV N8, 1, 0⟩,
  ⟨Hw.rvR N8, 1, 0⟩,
  ⟨Hw.rvJ N9, 6, 0⟩,
  ⟨Hw.rvV N9, 1, 0⟩,
  ⟨Hw.rvR N9, 1, 0⟩,
  ⟨Hw.rvJ N10, 6, 0⟩,
  ⟨Hw.rvV N10, 1, 0⟩,
  ⟨Hw.rvR N10, 1, 0⟩,
  ⟨Hw.rvJ N11, 6, 0⟩,
  ⟨Hw.rvV N11, 1, 0⟩,
  ⟨Hw.rvR N11, 1, 0⟩,
  ⟨Hw.rvJ N12, 6, 0⟩,
  ⟨Hw.rvV N12, 1, 0⟩,
  ⟨Hw.rvR N12, 1, 0⟩,
  ⟨Hw.rvJ N13, 6, 0⟩,
  ⟨Hw.rvV N13, 1, 0⟩,
  ⟨Hw.rvR N13, 1, 0⟩,
  ⟨Hw.rvJ N14, 6, 0⟩,
  ⟨Hw.rvV N14, 1, 0⟩,
  ⟨Hw.rvR N14, 1, 0⟩,
  ⟨Hw.rvJ N15, 6, 0⟩,
  ⟨Hw.rvV N15, 1, 0⟩,
  ⟨Hw.rvR N15, 1, 0⟩,
  ⟨Hw.rvJ N16, 6, 0⟩,
  ⟨Hw.rvV N16, 1, 0⟩,
  ⟨Hw.rvR N16, 1, 0⟩,
  ⟨Hw.rvJ N17, 6, 0⟩,
  ⟨Hw.rvV N17, 1, 0⟩,
  ⟨Hw.rvR N17, 1, 0⟩,
  ⟨Hw.rvJ N18, 6, 0⟩,
  ⟨Hw.rvV N18, 1, 0⟩,
  ⟨Hw.rvR N18, 1, 0⟩,
  ⟨Hw.rvJ N19, 6, 0⟩,
  ⟨Hw.rvV N19, 1, 0⟩,
  ⟨Hw.rvR N19, 1, 0⟩,
  ⟨Hw.rvJ N20, 6, 0⟩,
  ⟨Hw.rvV N20, 1, 0⟩,
  ⟨Hw.rvR N20, 1, 0⟩,
  ⟨Hw.rvJ N21, 6, 0⟩,
  ⟨Hw.rvV N21, 1, 0⟩,
  ⟨Hw.rvR N21, 1, 0⟩,
  ⟨Hw.rvJ N22, 6, 0⟩,
  ⟨Hw.rvV N22, 1, 0⟩,
  ⟨Hw.rvR N22, 1, 0⟩,
  ⟨Hw.rvJ N23, 6, 0⟩,
  ⟨Hw.rvV N23, 1, 0⟩,
  ⟨Hw.rvR N23, 1, 0⟩,
  ⟨Hw.rvJ N24, 6, 0⟩,
  ⟨Hw.rvV N24, 1, 0⟩,
  ⟨Hw.rvR N24, 1, 0⟩,
  ⟨Hw.rvJ N25, 6, 0⟩,
  ⟨Hw.rvV N25, 1, 0⟩,
  ⟨Hw.rvR N25, 1, 0⟩,
  ⟨Hw.rvJ N26, 6, 0⟩,
  ⟨Hw.rvV N26, 1, 0⟩,
  ⟨Hw.rvR N26, 1, 0⟩,
  ⟨Hw.rvJ N27, 6, 0⟩,
  ⟨Hw.rvV N27, 1, 0⟩,
  ⟨Hw.rvR N27, 1, 0⟩,
  ⟨Hw.rvJ N28, 6, 0⟩,
  ⟨Hw.rvV N28, 1, 0⟩,
  ⟨Hw.rvR N28, 1, 0⟩,
  ⟨Hw.rvJ N29, 6, 0⟩,
  ⟨Hw.rvV N29, 1, 0⟩,
  ⟨Hw.rvR N29, 1, 0⟩,
  ⟨Hw.rvJ N30, 6, 0⟩,
  ⟨Hw.rvV N30, 1, 0⟩,
  ⟨Hw.rvR N30, 1, 0⟩,
  ⟨Hw.rvJ N31, 6, 0⟩,
  ⟨Hw.rvV N31, 1, 0⟩,
  ⟨Hw.rvR N31, 1, 0⟩,
  ⟨Hw.rvJ N32, 6, 0⟩,
  ⟨Hw.rvV N32, 1, 0⟩,
  ⟨Hw.rvR N32, 1, 0⟩,
  ⟨Hw.rvJ N33, 6, 0⟩,
  ⟨Hw.rvV N33, 1, 0⟩,
  ⟨Hw.rvR N33, 1, 0⟩,
  ⟨Hw.rvJ N34, 6, 0⟩,
  ⟨Hw.rvV N34, 1, 0⟩,
  ⟨Hw.rvR N34, 1, 0⟩,
  ⟨Hw.rvJ N35, 6, 0⟩,
  ⟨Hw.rvV N35, 1, 0⟩,
  ⟨Hw.rvR N35, 1, 0⟩,
  ⟨Hw.rvJ N36, 6, 0⟩,
  ⟨Hw.rvV N36, 1, 0⟩,
  ⟨Hw.rvR N36, 1, 0⟩,
  ⟨Hw.rvJ N37, 6, 0⟩,
  ⟨Hw.rvV N37, 1, 0⟩,
  ⟨Hw.rvR N37, 1, 0⟩,
  ⟨Hw.rvJ N38, 6, 0⟩,
  ⟨Hw.rvV N38, 1, 0⟩,
  ⟨Hw.rvR N38, 1, 0⟩,
  ⟨Hw.rvJ N39, 6, 0⟩,
  ⟨Hw.rvV N39, 1, 0⟩,
  ⟨Hw.rvR N39, 1, 0⟩,
  ⟨Hw.rvJ N40, 6, 0⟩,
  ⟨Hw.rvV N40, 1, 0⟩,
  ⟨Hw.rvR N40, 1, 0⟩,
  ⟨Hw.rvJ N41, 6, 0⟩,
  ⟨Hw.rvV N41, 1, 0⟩,
  ⟨Hw.rvR N41, 1, 0⟩,
  ⟨Hw.rvJ N42, 6, 0⟩,
  ⟨Hw.rvV N42, 1, 0⟩,
  ⟨Hw.rvR N42, 1, 0⟩,
  ⟨Hw.rvJ N43, 6, 0⟩,
  ⟨Hw.rvV N43, 1, 0⟩,
  ⟨Hw.rvR N43, 1, 0⟩,
  ⟨Hw.rvJ N44, 6, 0⟩,
  ⟨Hw.rvV N44, 1, 0⟩,
  ⟨Hw.rvR N44, 1, 0⟩,
  ⟨Hw.rvJ N45, 6, 0⟩,
  ⟨Hw.rvV N45, 1, 0⟩,
  ⟨Hw.rvR N45, 1, 0⟩,
  ⟨Hw.rvJ N46, 6, 0⟩,
  ⟨Hw.rvV N46, 1, 0⟩,
  ⟨Hw.rvR N46, 1, 0⟩,
  ⟨Hw.rvJ N47, 6, 0⟩,
  ⟨Hw.rvV N47, 1, 0⟩,
  ⟨Hw.rvR N47, 1, 0⟩,
  ⟨Hw.rvJ N48, 6, 0⟩,
  ⟨Hw.rvV N48, 1, 0⟩,
  ⟨Hw.rvR N48, 1, 0⟩,
  ⟨Hw.rvJ N49, 6, 0⟩,
  ⟨Hw.rvV N49, 1, 0⟩,
  ⟨Hw.rvR N49, 1, 0⟩,
  ⟨Hw.rvJ N50, 6, 0⟩,
  ⟨Hw.rvV N50, 1, 0⟩,
  ⟨Hw.rvR N50, 1, 0⟩,
  ⟨Hw.rvJ N51, 6, 0⟩,
  ⟨Hw.rvV N51, 1, 0⟩,
  ⟨Hw.rvR N51, 1, 0⟩,
  ⟨Hw.rvJ N52, 6, 0⟩,
  ⟨Hw.rvV N52, 1, 0⟩,
  ⟨Hw.rvR N52, 1, 0⟩,
  ⟨Hw.rvJ N53, 6, 0⟩,
  ⟨Hw.rvV N53, 1, 0⟩,
  ⟨Hw.rvR N53, 1, 0⟩,
  ⟨Hw.rvJ N54, 6, 0⟩,
  ⟨Hw.rvV N54, 1, 0⟩,
  ⟨Hw.rvR N54, 1, 0⟩,
  ⟨Hw.rvJ N55, 6, 0⟩,
  ⟨Hw.rvV N55, 1, 0⟩,
  ⟨Hw.rvR N55, 1, 0⟩,
  ⟨Hw.rvJ N56, 6, 0⟩,
  ⟨Hw.rvV N56, 1, 0⟩,
  ⟨Hw.rvR N56, 1, 0⟩,
  ⟨Hw.rvJ N57, 6, 0⟩,
  ⟨Hw.rvV N57, 1, 0⟩,
  ⟨Hw.rvR N57, 1, 0⟩,
  ⟨Hw.rvJ N58, 6, 0⟩,
  ⟨Hw.rvV N58, 1, 0⟩,
  ⟨Hw.rvR N58, 1, 0⟩,
  ⟨Hw.rvJ N59, 6, 0⟩,
  ⟨Hw.rvV N59, 1, 0⟩,
  ⟨Hw.rvR N59, 1, 0⟩,
  ⟨Hw.rvJ N60, 6, 0⟩,
  ⟨Hw.rvV N60, 1, 0⟩,
  ⟨Hw.rvR N60, 1, 0⟩,
  ⟨Hw.rvJ N61, 6, 0⟩,
  ⟨Hw.rvV N61, 1, 0⟩,
  ⟨Hw.rvR N61, 1, 0⟩,
  ⟨Hw.rvJ N62, 6, 0⟩,
  ⟨Hw.rvV N62, 1, 0⟩,
  ⟨Hw.rvR N62, 1, 0⟩,
  ⟨Hw.rvJ N63, 6, 0⟩,
  ⟨Hw.rvV N63, 1, 0⟩,
  ⟨Hw.rvR N63, 1, 0⟩
]

set_option maxRecDepth 200000 in
set_option maxHeartbeats 16000000 in
/-- The literal declaration list is definitionally equal to `Hw.regDecls`. -/
theorem regDecls_eq_declList (m : Manifest) : regDecls m = declList m := rfl

theorem declList_length (m : Manifest) : (declList m).length = 825 := by
  rw [← regDecls_eq_declList, regDecls_length]

theorem declList_names_nodup (m : Manifest) : ((declList m).map (·.name)).Nodup := by
  rw [← regDecls_eq_declList]
  exact names_nodup m

set_option maxRecDepth 100000 in
set_option maxHeartbeats 1000000 in
/-- Fast reset lookup over the explicit declaration list. -/
theorem reset_lookup_decl (m : Manifest) (i : Nat) (hi : i < 825) :
    (Hw.core m).reset.regs ((declList m)[i]'(declList_length m ▸ hi)).name
        ((declList m)[i]'(declList_length m ▸ hi)).width
      = ((declList m)[i]'(declList_length m ▸ hi)).init := by
  rw [reset_regs_eq, regDecls_eq_declList]
  exact foldl_set_get (declList m) (declList_names_nodup m) _ i (declList_length m ▸ hi)

end Machines.Lnp64u.Theorems.RMC
