-- Copyright (c) 2026 Kevin Baragona
-- SPDX-License-Identifier: Apache-2.0
import Machines.Lnp64mini.Harness
import Loom.Hw.Dsl

/-!
# LNP64mini production-scale multiclock adoption

This module puts the real LNP64mini Design in a named System and exports a
best-effort retirement-PC telemetry stream to an independently clocked
observer.  Telemetry backpressure never stalls or changes the core: when the
bounded channel is full, only the observation is skipped.  This is the first
large-machine client of `CertifiedSystem`; it is deliberately technology
neutral and selects no FPGA primitive, ASIC macro, or synthesis tool.
-/

namespace Machines.Lnp64mini.Multiclock

open Loom.Hw
open Machines.Lnp64mini

def telemetry : Chan 64 :=
  { name := "retire_pc", depth := 2, policy := .exchange }
def telemetrySource : Chan.SourceEndpoint 64 := telemetry.source
def telemetrySink : Chan.SinkEndpoint 64 := telemetry.sink

def coreClock : ClockHandle := .named "core_clk"
def observerClock : ClockHandle := .named "observer_clk"

private def telemetryRule : Rule :=
  ⟨"publish_retire_pc",
    .ite telemetrySource.canSend (telemetrySource.send traceRdPcReg.rd) .skip⟩

/-- The original machine with one best-effort telemetry action. Channel
endpoint state and ports are generated when the System declares the channel. -/
def coreBody : Design :=
  { design with
    name := "lnp64mini_multiclock_core"
    rules := design.rules ++ [telemetryRule] }

/-- Proof-facing name for the source-adapted Design generated by
`SystemBuilder.channel`; it is not application assembly input. -/
private def instrumentedCore : Design := telemetry.withSource coreBody

def observedPc : Reg 64 := ⟨"observed_pc"⟩
def observedCount : Reg 64 := ⟨"observed_count"⟩

private def observerBody : Design where
  name := "lnp64mini_retire_observer"
  regs := [observedPc.decl, observedCount.decl]
  mems := []
  rules := [⟨"consume",
    .ite telemetrySink.hasData
      (.seq (observedPc.set telemetrySink.data)
        (.seq (observedCount.set (.add observedCount.rd (.lit 1))) telemetrySink.consume))
      .skip⟩]
  outputs := [observedPc.name, observedCount.name]

/-! The application-facing observer uses the readable hardware layer. This is
an ordinary synchronous island; the channel realization remains a separate
system-level choice. -/
namespace ObserverHardware

hardware lnp64mini_retire_observer where
  output reg observed_pc : 64
  output reg observed_count : 64

  rule «consume» :=
    if telemetrySink.hasData then {
      observed_pc <- telemetrySink.data,
      observed_count <- observed_count + 1,
      consume telemetrySink
    }

end ObserverHardware

/-- Syntax lowering preserves the original observer Design exactly, including
the right-associated write/consume order. -/
theorem observerHardware_eq : ObserverHardware.design = observerBody := rfl

/-- Public composition handle for the ordinary observer island. Its body is
kept separately named so the system command can resolve it fail-closed. -/
def observerDesign : Design := ObserverHardware.design

/-- Proof-facing name for the generated sink-adapted observer. -/
private def observer : Design := telemetry.withSink observerBody

def coreHandle : IslandHandle := .named "core" coreBody coreClock
def observerHandle : IslandHandle := .named "observer" observerBody observerClock
def telemetryRoute : ChannelRoute 64 :=
  telemetry.between coreHandle observerHandle

def builder : SystemBuilder :=
  System.empty
    |>.addIsland coreHandle
    |>.addIsland observerHandle
    |>.addChannel telemetryRoute
    |>.withClockRel .asynchronous

set_option maxRecDepth 100000 in
set_option maxHeartbeats 1000000 in
/-- Readable application declaration for the production-scale topology.  It
uses the same ordinary single-clock Designs and selects only Loom's portable,
technology-neutral crossing profile.  The legacy-shaped builder remains below
as an exact lowering oracle until downstream names migrate. -/
system authoredSystem where
  clock core_clk
  clock observer_clk
  clocks Clock.asynchronous
  reset Reset.together
  channel retire_pc : 64 depth 2 policy Chan.exchange
  island core on core_clk := coreBody
  island observer on observer_clk := observerDesign
  connect retire_pc from core to observer
  realize retire_pc with Cdc.grayFifo

set_option maxRecDepth 100000 in
theorem authoredSystem_eq_builder : authoredSystem = builder.certify (by decide) := rfl

set_option maxRecDepth 100000 in
def system : System := builder.certify (by decide)

theorem authoredSystem_eq_system : authoredSystem = system :=
  authoredSystem_eq_builder

set_option maxRecDepth 100000 in
theorem instrumentedCore_compilerReady :
    Compile.designWFCheck instrumentedCore = true := by rfl

set_option maxRecDepth 100000 in
theorem instrumentedCore_simulatorReady : instrumentedCore.fastWFB = true := by
  rfl

private def coreIsland : SystemIsland :=
  ⟨"core", "core_clk", instrumentedCore⟩

private def observerIsland : SystemIsland :=
  ⟨"observer", "observer_clk", observer⟩

set_option maxRecDepth 100000 in
set_option maxHeartbeats 1000000 in
theorem system_stockReady : system.stockCheck = true := by rfl

set_option maxRecDepth 100000 in
def application : System.Application system :=
  system.realizePortable system_stockReady

abbrev certified : CertifiedSystem system := application.certified

/-- Production-scale compiler-only multiclock artifact. This is the same
LNP64mini System used by certified schedule replay, not a parallel example. -/
abbrev certifiedArtifact : System.CertifiedRealizedSystem system certified :=
  application.artifact

theorem certifiedArtifact_bytes :
    certifiedArtifact.renderedUTF8 = certifiedArtifact.renderedVerilog.toUTF8 :=
  certifiedArtifact.renderedUTF8_eq

private theorem observerFound :
    system.findIsland? "observer" = some observerIsland := by
  simp [system, builder, observerIsland, observer, System.empty,
    SystemBuilder.addIsland, SystemBuilder.addChannel, SystemBuilder.channel,
    telemetryRoute, coreHandle, observerHandle, IslandHandle.named,
    IslandHandle.toSystemIsland, coreClock, observerClock, ClockHandle.named,
    Chan.between,
    SystemBuilder.withClockRel,
    SystemBuilder.findIsland?, System.findIsland?_certify]

def smokeSchedule : SchedulePrefix := #[
  coreClock.tick, coreClock.tick,
  observerClock.tick, observerClock.tick]

def smokeState : application.State := application.run smokeSchedule

/-- The production-scale replay retains the certified simulator/semantics
relation after independently scheduled events. Runtime payload checks belong
in the compiled runner rather than kernel-reducing the whole large core. -/
theorem smoke_observer_agrees :
    Agree observer
      (smokeState.fastIsland "observer" observerIsland observerFound)
      (smokeState.semantic.island "observer") :=
  smokeState.islandsAgree "observer" observerIsland observerFound

end Machines.Lnp64mini.Multiclock
