# Generated by Loom.Hw.DebugMap — DO NOT HAND EDIT.
# Reader half of the BSCAN debug map; source test/jtag_lib.tcl first.
# map 'lnp64mini_dual_bscan', taps=6
proc debug_trace_rd_pc_lo {} { return [rd 47] }
proc debug_trace_rd_wb_lo {} { return [rd 48] }
proc debug_fault_pc {} { return [expr {((0) | (([rd 49]) << 0)) | (([rd 50]) << 32)}] }
proc debug_fault_cause {} { return [rd 51] }
proc debug_fault_cur {} { return [rd 52] }
proc debug_running_and_halted {} { return [rd 54] }
proc debug_read_all {} {
  puts [format {trace_rd_pc_lo = 0x%08x} [debug_trace_rd_pc_lo]]
  puts [format {trace_rd_wb_lo = 0x%08x} [debug_trace_rd_wb_lo]]
  puts [format {fault_pc = 0x%016x} [debug_fault_pc]]
  puts [format {fault_cause = 0x%02x} [debug_fault_cause]]
  puts [format {fault_cur = 0x%02x} [debug_fault_cur]]
  puts [format {running_and_halted = 0x%01x} [debug_running_and_halted]]
}
