#!/usr/bin/env python3
"""Generate a balanced Lean SSA witness from canonical Loom µVerilog.

This tool is intentionally untrusted: its output is accepted only when Lean's
kernel checks the renderer and semantic certificates generated around it.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def write_if_changed(path: Path, text: str) -> None:
    """Preserve mtimes so checked generated modules support incremental builds."""
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)


def rhs(text: str) -> str:
    patterns = [
        (r"(\d+)'d(\d+)", lambda m: f".lit {m[1]} {m[2]}"),
        (r"~([A-Za-z_]\w*)", lambda m: f".not {q(m[1])}"),
        (r"\$signed\((\w+)\) < \$signed\((\w+)\)",
         lambda m: f".slt {q(m[1])} {q(m[2])}"),
        (r"\{\{(\d+)\{(\w+)\[(\d+)\]\}\}, (\w+)\}",
         lambda m: f".sext {m[1]} {q(m[2])} {m[3]}" if m[2] == m[4]
         else (_ for _ in ()).throw(ValueError("mismatched sext operand"))),
        (r"(\w+)\[(\d+):(\d+)\]",
         lambda m: f".slice {q(m[1])} {m[2]} {m[3]}"),
        (r"(\w+)\[(\w+)\]", lambda m: f".memRead {q(m[1])} {q(m[2])}"),
        (r"(\w+) \? (\w+) : (\w+)",
         lambda m: f".mux {q(m[1])} {q(m[2])} {q(m[3])}"),
    ]
    operators = {"&": "and", "|": "or", "^": "xor", "+": "add",
                 "-": "sub", "<<": "shl", ">>": "shr", "==": "eq",
                 "<": "ult"}
    for token in ("<<", ">>", "==", "&", "|", "^", "+", "-", "<"):
        escaped = re.escape(token)
        patterns.append((rf"(\w+) {escaped} (\w+)",
                         lambda m, op=operators[token]:
                         f".bin .{op} {q(m[1])} {q(m[2])}"))
    patterns.append((r"([A-Za-z_]\w*)", lambda m: f".ident {q(m[1])}"))
    for pattern, build in patterns:
        match = re.fullmatch(pattern, text)
        if match:
            return build(match)
    raise ValueError(f"unsupported RHS: {text}")


def balanced(names: list[str], empty: str) -> str:
    if not names:
        return empty
    level = names
    while len(level) > 1:
        nxt = []
        for i in range(0, len(level), 2):
            nxt.append(level[i] if i + 1 == len(level)
                       else f".node ({level[i]}) ({level[i + 1]})")
        level = nxt
    return level[0]


def balanced_proof(names: list[str]) -> str:
    """Compose already named leaf equalities without reopening their proofs."""
    level = [f"congrArg Rope.leaf {name}" for name in names]
    if not level:
        return "rfl"
    while len(level) > 1:
        nxt = []
        for i in range(0, len(level), 2):
            nxt.append(level[i] if i + 1 == len(level)
                       else f"Rope.node_congr ({level[i]}) ({level[i + 1]})")
        level = nxt
    return level[0]


def chunks(values: list, size: int) -> list[list]:
    return [values[i:i + size] for i in range(0, len(values), size)] or [[]]


def prelude(imports: list[str], namespace: str) -> list[str]:
    return (["-- Generated by scripts/gen_release_witness.py; DO NOT EDIT."] +
            [f"import {module}" for module in imports] +
            ["", f"namespace {namespace}", "",
             "open Loom.Release Loom.Release.SSA", "",
             "set_option maxRecDepth 1000000", "set_option maxHeartbeats 0", ""])


def wire_block_declarations(blocks: list[list[dict]], first: int = 0) -> list[str]:
    out: list[str] = []
    for offset, block in enumerate(blocks):
        index = first + offset
        name = f"wireBlock{index:04d}"
        disk_name = f"diskWireBlock{index:04d}"
        proof_name = f"renderWireBlock{index:04d}"
        entries = [f"  {{ width := {w['width']}, name := {q(w['name'])}, rhs := {w['rhs']} }}"
                   for w in block]
        out += [f"def {name} : List Wire := [", ",\n".join(entries), "]", ""]
        disk_entries = ",\n".join(f"  {q(w['line'])}" for w in block)
        out += [f"def {disk_name} : List String := [", disk_entries, "]", "",
                f"theorem {proof_name} :",
                f"    {name}.map Wire.render = {disk_name} := rfl", ""]
    return out


def parse(path: Path) -> dict:
    lines = path.read_text().splitlines()
    module = re.fullmatch(r"module (\w+)\(", lines[0]).group(1)
    i = 2
    assert lines[1] == "  input wire clk,"
    assert lines[i].startswith("  input wire rst")
    outputs = []
    i += 1
    while lines[i] != ");":
        match = re.fullmatch(r"  output wire \[(\d+):0\] (\w+),?", lines[i])
        outputs.append({"name": match[2], "width": int(match[1]) + 1})
        i += 1
    i += 1
    regs = []
    while i < len(lines) and (match := re.fullmatch(
            r"  reg \[(\d+):0\] (\w+);", lines[i])):
        regs.append({"name": match[2], "width": int(match[1]) + 1})
        i += 1
    mems = []
    while i < len(lines) and (match := re.fullmatch(
            r"  reg \[(\d+):0\] (\w+) \[0:(\d+)\];", lines[i])):
        size = int(match[3]) + 1
        aw = size.bit_length() - 1
        assert 1 << aw == size
        mems.append({"name": match[2], "dataWidth": int(match[1]) + 1,
                     "addrWidth": aw, "init": [], "initLines": [],
                     "writes": []})
        i += 1
    prefix = lines[:i]
    for mem in mems:
        assert lines[i] == "  initial begin"
        i += 1
        for address in range(1 << mem["addrWidth"]):
            match = re.fullmatch(
                rf"    {re.escape(mem['name'])}\[{address}\] = "
                rf"{mem['dataWidth']}'d(\d+);", lines[i])
            if not match:
                raise ValueError(f"bad init line {i + 1}: {lines[i]}")
            mem["init"].append(int(match[1]))
            mem["initLines"].append(lines[i])
            i += 1
        assert lines[i] == "  end"
        i += 1
    wires = []
    while i < len(lines) and (match := re.fullmatch(
            r"  wire \[(\d+):0\] (\w+) = (.*);", lines[i])):
        wires.append({"width": int(match[1]) + 1, "name": match[2],
                      "rhs": rhs(match[3]), "line": lines[i]})
        i += 1
    suffix_start = i
    assert lines[i] == "  always @(posedge clk) begin"; i += 1
    assert lines[i] == "    if (rst) begin"; i += 1
    for reg in regs:
        match = re.fullmatch(
            rf"      {re.escape(reg['name'])} <= {reg['width']}'d(\d+);", lines[i])
        reg["init"] = int(match[1]); i += 1
    assert lines[i] == "    end else begin"; i += 1
    for reg in regs:
        match = re.fullmatch(rf"      {re.escape(reg['name'])} <= (\w+);", lines[i])
        reg["next"] = match[1]; i += 1
    by_name = {mem["name"]: mem for mem in mems}
    while lines[i].startswith("      if ("):
        match = re.fullmatch(r"      if \((\w+)\) (\w+)\[(\w+)\] <= (\w+);", lines[i])
        by_name[match[2]]["writes"].append(
            {"en": match[1], "addr": match[3], "data": match[4]})
        i += 1
    assert lines[i] == "    end"; i += 1
    assert lines[i] == "  end"; i += 1
    for out in outputs:
        match = re.fullmatch(rf"  assign {re.escape(out['name'])} = (\w+);", lines[i])
        out["value"] = match[1]; i += 1
    assert lines[i:] == ["endmodule"]
    return {"name": module, "regs": regs, "mems": mems,
            "wires": wires, "outs": outputs, "prefix": prefix,
            "suffix": lines[suffix_start:]}


def emit(data: dict, output: Path, block_size: int) -> None:
    out = prelude(["Loom.Release.Certificate"], "Loom.GeneratedRelease")
    wire_names = []
    wire_disk_names = []
    wire_proof_names = []
    for index, block in enumerate(chunks(data["wires"], block_size)):
        name = f"wireBlock{index:04d}"
        disk_name = f"diskWireBlock{index:04d}"
        proof_name = f"renderWireBlock{index:04d}"
        wire_names.append(name)
        wire_disk_names.append(disk_name)
        wire_proof_names.append(proof_name)
        entries = [f"  {{ width := {w['width']}, name := {q(w['name'])}, rhs := {w['rhs']} }}"
                   for w in block]
        out += [f"def {name} : List Wire := [", ",\n".join(entries), "]", ""]
        disk_entries = ",\n".join(f"  {q(w['line'])}" for w in block)
        out += [f"def {disk_name} : List String := [", disk_entries, "]", "",
                f"theorem {proof_name} :",
                f"    {name}.map Wire.render = {disk_name} := rfl", ""]
    out += ["def wireTree : Rope (List Wire) :=",
            "  " + balanced(wire_names, ".leaf []").replace(
                "wireBlock", ".leaf wireBlock"), "",
            "def diskWireTree : Rope (List String) :=",
            "  " + balanced(wire_disk_names, ".leaf []").replace(
                "diskWireBlock", ".leaf diskWireBlock"), "",
            "theorem renderWireTree :",
            "    wireTree.map (fun wires => wires.map Wire.render) = diskWireTree := by",
            "  unfold wireTree diskWireTree",
            "  exact " + balanced_proof(wire_proof_names), ""]
    mem_names = []
    for mi, mem in enumerate(data["mems"]):
        init_names = []
        for bi, block in enumerate(chunks(mem["init"], block_size)):
            name = f"mem{mi}Init{bi:04d}"
            init_names.append(name)
            out += [f"def {name} : List Nat := [{', '.join(map(str, block))}]", ""]
        tree = balanced(init_names, ".leaf []").replace("mem", ".leaf mem")
        writes = ", ".join(
            f"{{ en := {q(w['en'])}, addr := {q(w['addr'])}, data := {q(w['data'])} }}"
            for w in mem["writes"])
        name = f"mem{mi}"
        mem_names.append(name)
        out += [f"def {name} : Mem where", f"  name := {q(mem['name'])}",
                f"  addrWidth := {mem['addrWidth']}", f"  dataWidth := {mem['dataWidth']}",
                f"  init := {tree}", f"  writes := [{writes}]", ""]
    regs = ",\n".join(
        f"  {{ name := {q(r['name'])}, width := {r['width']}, init := {r['init']}, next := {q(r['next'])} }}"
        for r in data["regs"])
    outs = ",\n".join(
        f"  {{ name := {q(o['name'])}, width := {o['width']}, value := {q(o['value'])} }}"
        for o in data["outs"])
    out += ["def program : Program where", f"  name := {q(data['name'])}",
            "  regs := [", regs, "  ]", f"  mems := [{', '.join(mem_names)}]",
            "  wires := wireTree", "  outs := [", outs, "  ]", "",
            "#guard program.elaborate |>.isSome", "", "end Loom.GeneratedRelease", ""]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out))


def emit_program_tail(out: list[str], data: dict, block_size: int,
                      namespace: str) -> None:
    """Append memory data and the complete concrete program to a root module."""
    mem_names = []
    disk_mem_names = []
    render_mem_proofs = []
    for mi, mem in enumerate(data["mems"]):
        init_names = []
        disk_init_names = []
        render_init_proofs = []
        init_blocks = chunks(mem["init"], block_size)
        line_blocks = chunks(mem["initLines"], block_size)
        for bi, (block, line_block) in enumerate(zip(init_blocks, line_blocks)):
            name = f"mem{mi}Init{bi:04d}"
            disk_name = f"diskMem{mi}Init{bi:04d}"
            proof_name = f"renderMem{mi}Init{bi:04d}"
            init_names.append(name)
            disk_init_names.append(disk_name)
            render_init_proofs.append(proof_name)
            out += [f"def {name} : List Nat := [{', '.join(map(str, block))}]", ""]
        tree = balanced(init_names, ".leaf []").replace("mem", ".leaf mem")
        writes = ", ".join(
            f"{{ en := {q(w['en'])}, addr := {q(w['addr'])}, data := {q(w['data'])} }}"
            for w in mem["writes"])
        name = f"mem{mi}"
        mem_names.append(name)
        out += [f"def {name} : Mem where", f"  name := {q(mem['name'])}",
                f"  addrWidth := {mem['addrWidth']}", f"  dataWidth := {mem['dataWidth']}",
                f"  init := {tree}", f"  writes := [{writes}]", ""]
        for bi, line_block in enumerate(line_blocks):
            disk_name = disk_init_names[bi]
            proof_name = render_init_proofs[bi]
            disk_entries = ",\n".join(f"  {q(line)}" for line in line_block)
            out += [f"def {disk_name} : List String := [", disk_entries, "]", "",
                    f"theorem {proof_name} :",
                    f"    {name}.renderInitLines {bi * block_size} " +
                      f"{init_names[bi]} = {disk_name} := rfl", ""]
        disk_init_tree = f"diskMem{mi}InitTree"
        out += [f"def {disk_init_tree} : Rope (List String) :=",
                "  " + balanced(disk_init_names, ".leaf []").replace(
                    "diskMem", ".leaf diskMem"), "",
                f"theorem renderMem{mi}InitTree :",
                f"    {name}.init.mapWithOffset {name}.renderInitLines 0 = " +
                  f"{disk_init_tree} := by",
                f"  unfold {name} {disk_init_tree}",
                "  exact " + balanced_proof(render_init_proofs), ""]
        disk_mem = f"diskMem{mi}Tree"
        disk_mem_names.append(disk_mem)
        render_mem_proofs.append(f"renderMem{mi}Tree")
        out += [f"def diskMem{mi}Start : List String := [\"  initial begin\"]",
                f"def diskMem{mi}End : List String := [\"  end\"]", "",
                f"def {disk_mem} : Rope (List String) :=",
                f"  .node (.leaf diskMem{mi}Start)",
                f"    (.node {disk_init_tree} (.leaf diskMem{mi}End))", "",
                f"theorem renderMem{mi}Tree : {name}.renderTree = {disk_mem} := by",
                f"  unfold SSA.Mem.renderTree {disk_mem} diskMem{mi}Start diskMem{mi}End",
                f"  exact Rope.node_congr rfl (Rope.node_congr renderMem{mi}InitTree rfl)", ""]
    regs = ",\n".join(
        f"  {{ name := {q(r['name'])}, width := {r['width']}, init := {r['init']}, next := {q(r['next'])} }}"
        for r in data["regs"])
    outs = ",\n".join(
        f"  {{ name := {q(o['name'])}, width := {o['width']}, value := {q(o['value'])} }}"
        for o in data["outs"])
    out += ["def program : Program where", f"  name := {q(data['name'])}",
            "  regs := [", regs, "  ]", f"  mems := [{', '.join(mem_names)}]",
            "  wires := wireTree", "  outs := [", outs, "  ]", ""]

    prefix_entries = ",\n".join(f"  {q(line)}" for line in data["prefix"])
    suffix_entries = ",\n".join(f"  {q(line)}" for line in data["suffix"])
    if not disk_mem_names:
        disk_mems = ".leaf []"
        mem_proof = "rfl"
    elif len(disk_mem_names) == 1:
        disk_mems = disk_mem_names[0]
        mem_proof = render_mem_proofs[0]
    else:
        # `SSA.renderMemTrees` is right-associated, unlike the balanced wire tree.
        disk_mems = disk_mem_names[-1]
        mem_proof = render_mem_proofs[-1]
        for disk_name, proof_name in reversed(list(zip(
                disk_mem_names[:-1], render_mem_proofs[:-1]))):
            disk_mems = f".node {disk_name} ({disk_mems})"
            mem_proof = f"Rope.node_congr {proof_name} ({mem_proof})"
    out += ["def diskPrefix : List String := [", prefix_entries, "]", "",
            "def diskSuffix : List String := [", suffix_entries, "]", "",
            "def diskMemTrees : Rope (List String) :=", f"  {disk_mems}", "",
            "theorem renderMemTrees : SSA.renderMemTrees program.mems = " +
              "diskMemTrees := by",
            "  unfold program SSA.renderMemTrees diskMemTrees",
            f"  exact {mem_proof}", "",
            "theorem renderPrefix : program.renderPrefix = diskPrefix := rfl", "",
            "theorem renderSuffix : program.renderSuffix = diskSuffix := rfl", "",
            "def diskTree : Rope (List String) :=",
            "  .node (.leaf diskPrefix)",
            "    (.node diskMemTrees (.node diskWireTree (.leaf diskSuffix)))", "",
            "theorem renderTree : program.renderTree = diskTree := by",
            "  unfold SSA.Program.renderTree diskTree",
            "  exact Rope.node_congr (congrArg Rope.leaf renderPrefix) " +
              "(Rope.node_congr renderMemTrees " +
              "(Rope.node_congr renderWireTree " +
              "(congrArg Rope.leaf renderSuffix)))", "",
            "theorem exactBytes : program.renderTree.flattenBytes = " +
              "diskTree.flattenBytes := Rope.flattenBytes_congr renderTree", "",
            f"end {namespace}", ""]


def emit_batched(data: dict, output: Path, block_size: int,
                 batch_blocks: int, design_expr: str | None = None,
                 design_imports: list[str] | None = None) -> None:
    """Emit bounded leaf modules and a small constant-only composition root."""
    try:
        relative = output.resolve().relative_to(Path.cwd().resolve())
    except ValueError as error:
        raise ValueError("batched output must be beneath the current directory") from error
    root_module = ".".join(relative.with_suffix("").parts)
    artifact = re.sub(r"\W", "", output.parent.name)
    namespace = f"Loom.GeneratedRelease.{artifact}"
    blocks = chunks(data["wires"], block_size)
    output.parent.mkdir(parents=True, exist_ok=True)
    batch_modules = []
    for batch_index, start in enumerate(range(0, len(blocks), batch_blocks)):
        module = ".".join(relative.parent.parts + (f"Batch{batch_index:03d}",))
        batch_modules.append(module)
        batch_path = output.parent / f"Batch{batch_index:03d}.lean"
        batch = prelude(["Loom.Release.SSA"], namespace)
        batch += wire_block_declarations(
            blocks[start:start + batch_blocks], first=start)
        batch += [f"end {namespace}", ""]
        write_if_changed(batch_path, "\n".join(batch))

    expected_batches = {f"Batch{i:03d}.lean" for i in range(len(batch_modules))}
    for stale in output.parent.glob("Batch*.lean"):
        if stale.name not in expected_batches:
            stale.unlink()

    names = [f"wireBlock{i:04d}" for i in range(len(blocks))]
    disk_names = [f"diskWireBlock{i:04d}" for i in range(len(blocks))]
    proofs = [f"renderWireBlock{i:04d}" for i in range(len(blocks))]
    out = prelude(["Loom.Release.Certificate"] + batch_modules, namespace)
    out += ["def wireTree : Rope (List Wire) :=",
            "  " + balanced(names, ".leaf []").replace(
                "wireBlock", ".leaf wireBlock"), "",
            "def diskWireTree : Rope (List String) :=",
            "  " + balanced(disk_names, ".leaf []").replace(
                "diskWireBlock", ".leaf diskWireBlock"), "",
            "theorem renderWireTree :",
            "    wireTree.map (fun wires => wires.map Wire.render) = diskWireTree := by",
            "  unfold wireTree diskWireTree",
            "  exact " + balanced_proof(proofs), ""]
    emit_program_tail(out, data, block_size, namespace)
    write_if_changed(output, "\n".join(out))
    manifest = output.parent / "modules.txt"
    write_if_changed(manifest, "\n".join(batch_modules + [root_module]) + "\n")

    if design_expr is not None:
        imports = design_imports or []
        cert_data = output.parent / "CertData.lean"
        cert_prefix = (f"import {root_module}\n" +
                       "import Loom.Release.NamedCertificate\n" +
                       "".join(f"import {module}\n" for module in imports) +
                       f"namespace {namespace}\nopen Loom.Release\n" +
                       "set_option maxRecDepth 1000000\n" +
                       "set_option maxHeartbeats 0\n" +
                       f"def design := {design_expr}\n" +
                       "def cert : Named.ModuleCert design := ")
        cert_suffix = ("\n" +
                       "theorem accepted : ssaNamedMatches design program cert = true := " +
                       "by decide +kernel\n" +
                       f"end {namespace}\n")
        cert_gen = (["-- Generated by scripts/gen_release_witness.py; DO NOT EDIT."] +
                    [f"import {module}" for module in
                     [root_module, "Tools.ReleaseCertGen"] + imports] +
                    ["", "unsafe def main : IO Unit := do",
                     f"  let design := {design_expr}",
                     "  let some cert := Tools.ReleaseCertGen.synthesize design " +
                       f"{namespace}.program",
                     "    | throw (IO.userError \"certificate synthesis failed\")",
                     f"  IO.FS.writeFile {q(str(cert_data))} <|",
                     f"    {q(cert_prefix)} ++ Tools.ReleaseCertGen.toLean cert ++",
                     f"      {q(cert_suffix)}", ""])
        write_if_changed(output.parent / "CertGen.lean", "\n".join(cert_gen))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--block-size", type=int, default=512)
    parser.add_argument("--batch-blocks", type=int, default=0,
                        help="write this many leaves per imported batch module")
    parser.add_argument("--design-expr",
                        help="Lean design expression for certificate generation")
    parser.add_argument("--design-import", action="append", default=[],
                        help="module imported by the generated certificate driver")
    args = parser.parse_args()
    data = parse(args.input)
    if args.batch_blocks:
        emit_batched(data, args.output, args.block_size, args.batch_blocks,
                     args.design_expr, args.design_import)
    else:
        emit(data, args.output, args.block_size)


if __name__ == "__main__":
    main()
