#!/usr/bin/env python3
# Copyright (c) 2026 Kevin Baragona
# SPDX-License-Identifier: Apache-2.0 OR SHL-2.1
#
# Generate the board tcl for a flat .hex program.
#
# The `.hex` is the single source for the board program; generated Tcl embeds
# the assembler output rather than maintaining another transcription.
#
# --check regenerates and diffs instead of writing, which is how the staleness
# gate can see a tcl that drifted from its program.

import argparse
import pathlib
import sys

DATA_BASE = 0x10000000
TEXT_BASE = 0x1000


def words(hexfile):
    out = []
    for line in pathlib.Path(hexfile).read_text().splitlines():
        t = line.strip()
        if t:
            out.append(int(t, 16))
    return out


def render(hexfile, bit, name, expect=None):
    ws = words(hexfile)
    base = DATA_BASE + TEXT_BASE
    L = []
    A = L.append
    A(f"# {name}.tcl -- GENERATED by scripts/gen_board_prog.py from")
    A(f"# {hexfile}. Do not edit: re-run the generator instead. The program")
    A("# words below are the assembler's output, not a transcription of it.")
    A("source [file join [file dirname [info script]] board_env.tcl]")
    A("source $LOOM_JTAG_LIB")
    A("connect")
    A('targets -set -filter {name =~ "xc7z*"}')
    A(f"fpga -file {bit}")
    A("after 2000")
    A('puts "ID=[format 0x%08x [rd 0]]"')
    A("set h1 [rd 2]; after 200; set h2 [rd 2]")
    A('puts "HB_TICKING=[expr {$h2 != $h1}]"')
    A(f"# --- load {len(ws)} words at DDR 0x{base:08x} (DATA_BASE + TEXT_BASE) ---")
    A("# addr-8: the auto-increment latches the POST-increment address, so the")
    A("# write lands one word later than the address written.")
    for i, w in enumerate(ws):
        a = base + i * 8
        A(f"wr 40 [expr {{0x{a:08x} - 8}}]; wr 41 0x{w & 0xffffffff:08x}; "
          f"wr 42 0x{(w >> 32) & 0xffffffff:08x}")
    A("# read the first and last word back, so a load that silently did not")
    A("# land is reported here rather than as a mystery trap later")
    A(f"wr 40 0x{base:08x}; wr 43 1; after 10")
    A(f'puts "W0=[format 0x%08x%08x [rd 46] [rd 45]]  (want 0x{ws[0]:016x})"')
    last = base + (len(ws) - 1) * 8
    A(f"wr 40 0x{last:08x}; wr 43 1; after 10")
    A(f'puts "WLAST=[format 0x%08x%08x [rd 46] [rd 45]]  (want 0x{ws[-1]:016x})"')
    A("# --- reset (starts the zeroing sweep), then start ---")
    A("wr 13 1")
    A("after 300")
    A("wr 13 2")
    A("for {set i 0} {$i < 200} {incr i} {")
    A("  set stx [rd 20]")
    A("  if {$stx & 2} break")
    A("  after 100")
    A("}")
    A('puts "STATUS=[format 0x%x [rd 20]]"')
    A('puts "RETIRE=[rd 21]"')
    A('puts "PC=[rd 22]"')
    A('puts "TRAP=[format 0x%x [rd 40]]"')
    A("for {set i 1} {$i <= 9} {incr i} {")
    A("  wr 14 $i; after 5")
    A('  puts "r$i=[expr {([rd 24]<<32) | [rd 23]}]"')
    A("}")
    if expect is not None:
        A(f'puts "EXPECT_r1={expect}"')
    A(f'puts "{name.upper()}_DONE"')
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("hexfile")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--bit", default="$LOOM_OXC7_DIR/out/lnp64mini_top.bit")
    ap.add_argument("--name", default=None)
    ap.add_argument("--expect-r1", default=None,
                    help="expected checksum, embedded so the board prints what it "
                         "should have produced next to what it did")
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff instead of writing")
    a = ap.parse_args()

    name = a.name or pathlib.Path(a.out).stem
    txt = render(a.hexfile, a.bit, name, a.expect_r1)
    out = pathlib.Path(a.out)

    if a.check:
        if not out.exists():
            print(f"gen_board_prog: {out} does not exist")
            return 1
        if out.read_text() != txt:
            print(f"gen_board_prog: STALE — {out} does not match a fresh "
                  f"generation from {a.hexfile}")
            return 1
        print(f"gen_board_prog: ok — {out} matches {a.hexfile}")
        return 0

    out.write_text(txt)
    print(f"gen_board_prog: wrote {out} ({len(words(a.hexfile))} program words)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
