#!/usr/bin/env python3
"""UNTRUSTED certificate generator for Loom/Dp/Cert/Check.lean benchmarks.

Generates the pigeonhole CNF php(n) (n pigeons, n-1 holes) and a hinted
RUP certificate for it by Davis-Putnam variable elimination: every
resolvent is RUP w.r.t. its two parents, so each step carries exactly two
hints. Output is Lean source (pasted into Tests/CheckBench.lean).

Nothing here is trusted: the Lean kernel re-checks every step via
`Loom.Dp.Cert.Check.check` under plain `decide`.

Usage: gen_php_cert.py N [--emit]
"""
import sys
from itertools import combinations

def php(n):
    """Pigeonhole n pigeons into n-1 holes. Vars 1..n*(n-1): x(p,h)."""
    holes = n - 1
    var = lambda p, h: p * holes + h + 1  # p,h 0-based
    clauses = []
    for p in range(n):
        clauses.append(frozenset((var(p, h), True) for h in range(holes)))
    for h in range(holes):
        for p, q in combinations(range(n), 2):
            clauses.append(frozenset([(var(p, h), False), (var(q, h), False)]))
    return clauses, n * holes

def dp_cert(clauses, nvars):
    """DP elimination; steps [(clause, hints)] with hints as positions in
    the checker's accumulated formula (learned clauses prepended, newest
    first, originals last — see Check.lean `check`)."""
    norig = len(clauses)
    all_clauses = list(clauses)           # cumulative, oldest first
    def hpos(idx):
        k = len(all_clauses) - norig      # learned so far
        return k + idx if idx < norig else k - 1 - (idx - norig)
    active = set(range(len(clauses)))
    seen = {c: i for i, c in enumerate(clauses)}
    steps = []
    for v in range(1, nvars + 1):
        pos = [i for i in active if (v, True) in all_clauses[i]]
        neg = [i for i in active if (v, False) in all_clauses[i]]
        for i in pos:
            for j in neg:
                r = (all_clauses[i] - {(v, True)}) | (all_clauses[j] - {(v, False)})
                if any((w, not b) in r for (w, b) in r):
                    continue  # tautology
                if r in seen:
                    continue
                hints = [hpos(i), hpos(j)]   # positions before adding r
                idx = len(all_clauses)
                seen[r] = idx
                all_clauses.append(r)
                active.add(idx)
                steps.append((r, hints))
                if not r:
                    return steps, all_clauses
        active -= set(pos) | set(neg)
    raise RuntimeError("no empty clause derived")

# --- validator: mirrors Check.lean's reduce/runHints/check exactly ---
def reduce(tau, clause):
    unit = None
    for (v, b) in clause:
        if v in tau:
            if tau[v] == b:
                return ("stuck", None)
        else:
            if unit is not None and unit != (v, b):
                return ("stuck", None)
            unit = (v, b)
    return ("conflict", None) if unit is None else ("unit", unit)

def check(formula, steps):
    F = [list(c) for c in formula]
    for (clause, hints) in steps:
        tau = {v: (not b) for (v, b) in clause}
        ok = False
        for i in hints:
            kind, lit = reduce(tau, F[i])
            if kind == "conflict":
                ok = True
                break
            if kind == "unit":
                tau[lit[0]] = lit[1]
            else:
                return False
        if not ok:
            return False
        if not clause:
            return True
        F.insert(0, list(clause))
    return False

def lean_clause(c):
    lits = sorted(c)
    return "[" + ", ".join(f"({v}, {'true' if b else 'false'})" for v, b in lits) + "]"

def emit(n):
    clauses, nvars = php(n)
    steps, _ = dp_cert(clauses, nvars)
    assert check(clauses, steps), "generated certificate failed validation"
    nlits = sum(len(c) for c, _ in steps)
    print(f"-- php{n}->{n-1}: {nvars} vars, {len(clauses)} clauses, "
          f"{len(steps)} DP-resolution steps ({nlits} literals). "
          f"Generated by scripts/gen_php_cert.py (untrusted).")
    print(f"def php{n} : Cnf := [")
    print(",\n".join("  " + lean_clause(c) for c in clauses))
    print("]")
    print(f"\ndef php{n}Cert : List Step := [")
    print(",\n".join(f"  .add {lean_clause(c)} {h}" for c, h in steps))
    print("]")

if __name__ == "__main__":
    n = int(sys.argv[1])
    if "--emit" in sys.argv:
        emit(n)
    else:
        clauses, nvars = php(n)
        steps, _ = dp_cert(clauses, nvars)
        ok = check(clauses, steps)
        nlits = sum(len(c) for c, _ in steps)
        print(f"php{n}: {nvars} vars, {len(clauses)} clauses, "
              f"{len(steps)} steps, {nlits} cert literals, valid={ok}")
