#!/usr/bin/env python3
# Copyright (c) 2026 Kevin Baragona
# SPDX-License-Identifier: Apache-2.0
"""Generator for Machines/Lnp64u/Theorems/RMCResetTab.lean (NOT run in CI).

Emits one lemma per register-name family of the LNP64-u core: the reset
value of every register of `Hw.core m` for a symbolic manifest, each arm
instantiating `RMC.reset_lookup` at the register's index in `regDecls m`.
This is the missing input of `RMC.absDom_reset` / `RMC.coupled_reset`.

Layout constants (verified against Hw/Enc.lean's regDecls order on
2026-07-03; any drift fails to typecheck, it cannot silently misprove):

  domain block  137*d : reg r -> +r | pc +8 | cap s: v +9+5s, kind +10+5s,
                lin_v +11+5s, lin +12+5s, gen +13+5s | cell l: v +89+2l,
                par +90+2l | rgn r: v +121+2r, rgn +122+2r | run 129,
                run_g 130, srv_v 131, srv 132, cause 133, budget 134,
                maxdon 135, rctr 136
  gate block    548 + 18*g : callee +0, entry +1, act_v +2, caller +3,
                callerrd +4, sreg r +5+r, spc +13, ssrv_v +14, ssrv +15,
                depth +16, don +17
  globals       620..632 (mov_v, mov_src, mov_dst, mov_srccur, mov_dstcur,
                mov_rem, mov_owner, mov_status, if_v, if_dom, if_word,
                if_cl, cycle)
  rv engine     633 + 3*i (j/v/r)   [hidden; abs ignores them]

STATUS / WHY NOT LANDED: the generated file typechecks arm-by-arm but is
too slow for CI as a single file (~600 arms at 5-20 s/arm: every arm's
defeq check makes the elaborator walk the `regDecls m` spine, re-reducing
the flatMap/append chain).  Before landing, apply the declList
optimization:

  private def declList (m : Manifest) : List RegDecl := [ <825 literals> ]
  private theorem regDecls_eq (m : Manifest) : regDecls m = declList m := rfl

(one ~40 s rfl, like RMCReset.names_stable), restate the lookups against
the literal list (getElem then walks plain cons cells instead of
re-evaluating flatMap per arm), and split the output into per-block files
so lake parallelizes them.  See RMCAbs.lean for the hand-landed cheap arms
(globals + gate config) consumed by the abs_reset field lemmas.
"""

D = 137   # domain block stride
G = 18    # gate block stride

HDR = """import Machines.Lnp64u.Theorems.RMCReset

/-! # R-MC support: the reset lookup table (GENERATED by
scripts/gen_rmc_reset_tab.py -- edit the generator, not this file) -/

namespace Machines.Lnp64u.Theorems.RMC

open Machines.Lnp64u Loom.Hw Machines.Lnp64u.Hw

"""

out = [HDR]

def fam(thm_name, binders, name_expr, width, rhs, arms):
    lines = ["set_option maxRecDepth 200000 in",
             "set_option maxHeartbeats 16000000 in",
             f"theorem {thm_name} (m : Manifest) : ∀ {binders},",
             f"    (Hw.core m).reset.regs ({name_expr}) {width}",
             f"      = {rhs}"]
    for pats, idx in arms:
        lines.append(f"  | {', '.join(pats)} => reset_lookup m {idx} (by omega)")
    lines.append("")
    out.append("\n".join(lines))

def fp(v):
    return f"⟨{v}, _⟩"

ds = "m.initState.doms d"
fam("reset_dreg", "(d : DomainId) (r : RegId)", "Hw.dreg d r", 32,
    f"({ds}).regs r",
    [((fp(d), fp(r)), D*d + r) for d in range(4) for r in range(8)])
fam("reset_dpc", "(d : DomainId)", "Hw.dpc d", 12,
    f"({ds}).pc",
    [((fp(d),), D*d + 8) for d in range(4)])
fam("reset_dcapV", "(d : DomainId) (s : Slot)", "Hw.dcapV d s", 1,
    f"(if (({ds}).caps s).isSome then 1 else 0)",
    [((fp(d), fp(s)), D*d + 9 + 5*s) for d in range(4) for s in range(16)])
fam("reset_dcapKind", "(d : DomainId) (s : Slot)", "Hw.dcapKind d s", 32,
    f"((({ds}).caps s).map fun c => encKind c.kind).getD 0",
    [((fp(d), fp(s)), D*d + 10 + 5*s) for d in range(4) for s in range(16)])
fam("reset_dcapLinV", "(d : DomainId) (s : Slot)", "Hw.dcapLinV d s", 1,
    f"(if ((({ds}).caps s).bind (·.lineage)).isSome then 1 else 0)",
    [((fp(d), fp(s)), D*d + 11 + 5*s) for d in range(4) for s in range(16)])
fam("reset_dcapLin", "(d : DomainId) (s : Slot)", "Hw.dcapLin d s", 4,
    f"(((({ds}).caps s).bind (·.lineage)).map fun l => BitVec.ofNat 4 l.val).getD 0",
    [((fp(d), fp(s)), D*d + 12 + 5*s) for d in range(4) for s in range(16)])
fam("reset_dgen", "(d : DomainId) (s : Slot)", "Hw.dgen d s", 8,
    f"({ds}).slotGen s",
    [((fp(d), fp(s)), D*d + 13 + 5*s) for d in range(4) for s in range(16)])
fam("reset_dcellV", "(d : DomainId) (l : LineageId)", "Hw.dcellV d l", 1,
    f"(if (({ds}).lineage l).isSome then 1 else 0)",
    [((fp(d), fp(l)), D*d + 89 + 2*l) for d in range(4) for l in range(16)])
fam("reset_dcellPar", "(d : DomainId) (l : LineageId)", "Hw.dcellPar d l", 14,
    f"((({ds}).lineage l).map fun c => encRef c.parent).getD 0",
    [((fp(d), fp(l)), D*d + 90 + 2*l) for d in range(4) for l in range(16)])
fam("reset_drgnV", "(d : DomainId) (r : RegionId)", "Hw.drgnV d r", 1,
    f"(if (({ds}).regions r).isSome then 1 else 0)",
    [((fp(d), fp(r)), D*d + 121 + 2*r) for d in range(4) for r in range(4)])
fam("reset_drgn", "(d : DomainId) (r : RegionId)", "Hw.drgn d r", 42,
    f"((({ds}).regions r).map encRegion).getD 0",
    [((fp(d), fp(r)), D*d + 122 + 2*r) for d in range(4) for r in range(4)])
tail = [("drun", 129, 2, f"encRun ({ds}).run"),
        ("drunG", 130, 2, f"encRunG ({ds}).run"),
        ("dsrvV", 131, 1, f"(if ({ds}).serving.isSome then 1 else 0)"),
        ("dsrv", 132, 2, f"((({ds}).serving.map fun g => BitVec.ofNat 2 g.val).getD 0)"),
        ("dcause", 133, 32, f"({ds}).cause"),
        ("dbudget", 134, 32, f"BitVec.ofNat 32 ({ds}).budget"),
        ("dmaxdon", 135, 32, f"BitVec.ofNat 32 ({ds}).maxDonation"),
        ("drctr", 136, 32, "BitVec.ofNat 32 (m.initState.cycle % (m.doms d).periodP)")]
for nm, off, w, rhs in tail:
    fam(f"reset_{nm}", "(d : DomainId)", f"Hw.{nm} d", w, rhs,
        [((fp(d),), D*d + off) for d in range(4)])

gs = "m.initState.gates g"
gfams = [("gcaller", 3, 2, f"((({gs}).act.map fun x => BitVec.ofNat 2 x.caller.val).getD 0)"),
         ("gcallerRd", 4, 3, f"((({gs}).act.map fun x => BitVec.ofNat 3 x.callerRd.val).getD 0)"),
         ("gspc", 13, 12, f"((({gs}).act.map (·.savedPc)).getD 0)"),
         ("gssrvV", 14, 1, f"(if (({gs}).act.bind (·.savedServing)).isSome then 1 else 0)"),
         ("gssrv", 15, 2, f"(((({gs}).act.bind (·.savedServing)).map fun x => BitVec.ofNat 2 x.val).getD 0)"),
         ("gdepth", 16, 3, f"((({gs}).act.map fun x => BitVec.ofNat 3 x.depth).getD 0)"),
         ("gdon", 17, 32, f"((({gs}).act.map fun x => BitVec.ofNat 32 x.donated).getD 0)")]
for nm, off, w, rhs in gfams:
    fam(f"reset_{nm}", "(g : GateId)", f"Hw.{nm} g", w, rhs,
        [((fp(g),), 548 + G*g + off) for g in range(4)])
fam("reset_gsreg", "(g : GateId) (r : RegId)", "Hw.gsreg g r", 32,
    f"((({gs}).act.map fun x => x.savedRegs r).getD 0)",
    [((fp(g), fp(r)), 548 + G*g + 5 + r) for g in range(4) for r in range(8)])

glob = [("mov_src", 621, 14, "((m.initState.mover.map fun x => encRef x.src).getD 0)"),
        ("mov_dst", 622, 14, "((m.initState.mover.map fun x => encRef x.dst).getD 0)"),
        ("mov_srccur", 623, 12, "((m.initState.mover.map (·.srcCur)).getD 0)"),
        ("mov_dstcur", 624, 12, "((m.initState.mover.map (·.dstCur)).getD 0)"),
        ("mov_rem", 625, 13, "((m.initState.mover.map fun x => BitVec.ofNat 13 x.remaining).getD 0)"),
        ("mov_owner", 626, 2, "((m.initState.mover.map fun x => BitVec.ofNat 2 x.owner.val).getD 0)"),
        ("mov_status", 627, 12, "((m.initState.mover.map (·.statusAddr)).getD 0)"),
        ("if_dom", 629, 2, "((m.initState.inflight.map fun x => BitVec.ofNat 2 x.dom.val).getD 0)"),
        ("if_word", 630, 32, "((m.initState.inflight.map (·.word)).getD 0)"),
        ("if_cl", 631, 8, "((m.initState.inflight.map fun x => BitVec.ofNat 8 x.cyclesLeft).getD 0)")]
for nm, idx, w, rhs in glob:
    out.append(f"""set_option maxRecDepth 200000 in
set_option maxHeartbeats 16000000 in
theorem reset_{nm.replace("_", "")} (m : Manifest) :
    (Hw.core m).reset.regs "{nm}" {w} = {rhs} :=
  reset_lookup m {idx} (by omega)
""")

out.append("end Machines.Lnp64u.Theorems.RMC\n")

if __name__ == "__main__":
    path = "Machines/Lnp64u/Theorems/RMCResetTab.lean"
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("generated", sum(o.count("=>") for o in out), "arms ->", path)
