-- Copyright (c) 2026 Kevin Baragona
-- SPDX-License-Identifier: Apache-2.0
import Tools.ReleaseCertGen
import Tools.RuntimeSsa
import Loom.Release.ActionStateDag
import Machines.Acc8.Core
import Machines.Acc8.Iss
import Machines.Lnp64u.Hw.Core
import Machines.Lnp64u.Hw.Demo

/-! Native untrusted generator for action-wide release certificates. -/

open Loom.Hw

private def writeIfChanged (path : System.FilePath) (contents : String) : IO Unit := do
  try
    if (← IO.FS.readFile path) == contents then return
  catch _ => pure ()
  if let some parent := path.parent then IO.FS.createDirAll parent
  IO.FS.writeFile path contents

private def source (namespaceName : String) (registers : List RegDecl) (cert :
    Loom.Release.Symbolic.ActionWide.RulesCert) : Option (String × String) := do
  let rendered ← Tools.ReleaseCertGen.actionWideRulesToLean registers cert
  let leanSource := "-- Generated by Tools.ActionWideGen; DO NOT EDIT.\n" ++
  "import Loom.Release.ActionWideRegister\n\n" ++
  "namespace " ++ namespaceName ++ "\n\n" ++
  "open Loom.Release\n\n" ++
  "def actionWideRegisterData : String :=\n" ++
  "  include_str \"ActionWideRegisterData.txt\"\n\n" ++
  "end " ++ namespaceName ++ "\n"
  pure (leanSource, rendered.data)

private unsafe def generate (makeDesign : Unit → Design) (namespaceName : String)
    (runtime output : System.FilePath) : IO UInt32 := do
  let started ← IO.monoMsNow
  let program ← Tools.RuntimeSsa.load runtime
  let loaded ← IO.monoMsNow
  IO.eprintln s!"runtime-load={loaded - started}ms"
  let design := makeDesign ()
  let designed ← IO.monoMsNow
  IO.eprintln s!"design={designed - loaded}ms"
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let generated ← IO.monoMsNow
  let some (contents, data) := source namespaceName design.regs cert
    | IO.eprintln "action-wide certificate encoding failed"; return 1
  let dataPath := output.parent.getD "." / "ActionWideRegisterData.txt"
  writeIfChanged dataPath data
  writeIfChanged output contents
  let written ← IO.monoMsNow
  IO.println (s!"runtime-load={loaded - started}ms " ++
    s!"design={designed - loaded}ms certificate={generated - designed}ms " ++
    s!"write={written - generated}ms")
  return 0

private def joinBlockSource (rootImport namespaceName designExpr : String)
    (fuel blockCount : Nat)
    (cert : Loom.Release.Symbolic.ActionWide.RulesCert) : String :=
  let joins := Tools.ReleaseCertGen.actionWideJoins cert
  let blocks := (List.range blockCount).map fun index =>
    joins.drop (index * 128) |>.take 128
  let declarations := String.intercalate "\n" <| blocks.zipIdx.map fun (block, index) =>
    "def joinProbe" ++ toString index ++
      " : List Symbolic.ActionWide.Join :=\n" ++
      Tools.ReleaseCertGen.actionWideJoinBlockToLean block ++ "\n\n" ++
    "theorem joinProbeAccepted" ++ toString index ++ " :\n" ++
      "    Symbolic.ActionWide.joinBlockMatchesFuel indexedWireTree wireTable\n" ++
      "      design.regs.toArray " ++ toString fuel ++ " joinProbe" ++
      toString index ++ " = true := kernel_decide\n"
  "-- Generated join-block feasibility probe; DO NOT EDIT.\n" ++
  "import " ++ rootImport ++ "\n" ++
  "import Loom.Release.ActionWideRegister\n" ++
  "import Loom.Release.KernelDecide\n" ++
  "import Machines.Lnp64u.Hw.Core\n" ++
  "import Machines.Lnp64u.Hw.Demo\n\n" ++
  "namespace " ++ namespaceName ++ "\n\n" ++
  "open Loom.Release\n\n" ++
  "private abbrev design := " ++ designExpr ++ "\n\n" ++
  "set_option maxRecDepth 1000000\n" ++
  "set_option maxHeartbeats 0\n\n" ++
  declarations ++ "\n" ++
  "end " ++ namespaceName ++ "\n"

private unsafe def generateJoinBlock (makeDesign : Unit → Design)
    (rootImport namespaceName designExpr : String)
    (runtime output : System.FilePath) (blockCount : Nat := 1) : IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := makeDesign ()
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let joins := Tools.ReleaseCertGen.actionWideJoins cert
  let joinCount := joins.length
  let perRule := cert.map fun rule => Tools.ReleaseCertGen.actionWideJoins [rule] |>.length
  let mut exact := 0
  let mut ordered := 0
  let mut previous : Option Nat := none
  for join in joins do
    match join.output with
    | .wire number =>
        if previous.all (· < number) then ordered := ordered + 1
        previous := some number
        if let some wire := program.wires[number]? then
          if let some (.mux guard yes no) := wire.rhs.toIndexed? then
            if guard == join.guard && yes == join.thenInput &&
                no == join.elseInput then
              exact := exact + 1
    | .reg _ => pure ()
  IO.eprintln s!"action-wide joins={joinCount}; emitting {blockCount} blocks"
  IO.eprintln s!"action-wide rules={cert.length}; joins/rule={perRule}"
  IO.eprintln s!"action-wide exact={exact}; monotonically-ordered={ordered}"
  writeIfChanged output (joinBlockSource rootImport namespaceName designExpr
    (program.wires.size + 1) blockCount cert)
  return 0

private def pad3 (number : Nat) : String :=
  let value := toString number
  if number < 10 then "00" ++ value
  else if number < 100 then "0" ++ value
  else value

private def pad4 (number : Nat) : String :=
  let value := toString number
  if number < 10 then "000" ++ value
  else if number < 100 then "00" ++ value
  else if number < 1000 then "0" ++ value
  else value

private def localJoinBlockSource (blockIndex : Nat)
    (joins : List Loom.Release.Symbolic.ActionWide.Join) : String :=
  let batchIndex := blockIndex / 4
  let suffix := pad4 blockIndex
  "-- Generated local join-block feasibility probe; DO NOT EDIT.\n" ++
  "import GeneratedRelease.Lnp64u.Batch" ++ pad3 batchIndex ++ "\n" ++
  "import Loom.Release.ActionWideJoin\n" ++
  "import Loom.Release.KernelDecide\n" ++
  "\n" ++
  "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
  "open Loom.Release\n\n" ++
  "set_option maxRecDepth 1000000\n\n" ++
  Tools.ReleaseCertGen.actionWideNamedJoinBlockToLean
    ("actionJoinBlock" ++ suffix) joins ++ "\n\n" ++
  "set_option maxRecDepth 1000000\n" ++
  "set_option maxHeartbeats 0\n\n" ++
  "theorem actionJoinBlockAccepted" ++ suffix ++ " :\n" ++
  "    Symbolic.ActionWide.localJoinBlockMatches " ++
    toString (blockIndex * 128) ++ " indexedWireBlock" ++
    suffix ++ " actionJoinBlock" ++ suffix ++
    " = true := kernel_decide\n\n" ++
  "end Loom.GeneratedRelease.Lnp64u\n"

private unsafe def generateLocalJoinBlock (runtime output : System.FilePath)
    (blockIndex : Nat) : IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let joins := (Tools.ReleaseCertGen.actionWideJoins cert).filter fun join =>
    match join.output with
    | .wire number => number / 128 == blockIndex
    | .reg _ => false
  IO.eprintln s!"local join block {blockIndex}: {joins.length} joins"
  writeIfChanged output (localJoinBlockSource blockIndex joins)
  return 0

private unsafe def generateLocalJoinBlocks (runtime outputDir : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let blockCount := (program.wires.size + 127) / 128
  let mut groups : Array (List Loom.Release.Symbolic.ActionWide.Join) :=
    Array.replicate blockCount []
  for join in Tools.ReleaseCertGen.actionWideJoins cert do
    if let .wire number := join.output then
      let blockIndex := number / 128
      if blockIndex < groups.size then
        groups := groups.modify blockIndex (join :: ·)
  IO.FS.createDirAll outputDir
  let mut emitted := 0
  let mut modules : List String := []
  for blockIndex in List.range groups.size do
    let joins := groups[blockIndex]!.reverse
    if !joins.isEmpty then
      let suffix := pad4 blockIndex
      let path := outputDir / s!"ActionJoinBlock{suffix}.lean"
      writeIfChanged path (localJoinBlockSource blockIndex joins)
      modules := s!"GeneratedRelease.Lnp64u.ActionJoinBlock{suffix}" :: modules
      emitted := emitted + 1
  writeIfChanged (outputDir / "action-join-modules.txt")
    (String.intercalate "\n" modules.reverse ++ "\n")
  IO.eprintln s!"emitted {emitted} nonempty local join blocks"
  return 0

private unsafe def generateNamedCertificate (runtime output : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let mut importedBlocks : Std.HashSet Nat := {}
  for join in Tools.ReleaseCertGen.actionWideJoins cert do
    if let .wire number := join.output then
      importedBlocks := importedBlocks.insert (number / 128)
  let imports := (List.range ((program.wires.size + 127) / 128)).filterMap
    fun blockIndex => if importedBlocks.contains blockIndex then
      some ("import GeneratedRelease.Lnp64u.ActionJoinBlock" ++ pad4 blockIndex)
    else none
  let source := "-- Generated bounded typed action certificate; DO NOT EDIT.\n" ++
    String.intercalate "\n" imports ++
    "\nimport Loom.Release.ActionWideRegister\n\n" ++
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Release\n\n" ++
    "set_option maxRecDepth 1000000\n\n" ++
    Tools.ReleaseCertGen.actionWideNamedCertificateToLean cert ++ "\n" ++
    "end Loom.GeneratedRelease.Lnp64u\n"
  writeIfChanged output source
  return 0

private def evaluateCert (registers : Array RegDecl) :
    Array Loom.Release.Symbolic.Ref → List Nat →
      Loom.Release.Symbolic.ActionWide.ActionCert →
      Option Loom.Release.Symbolic.ActionWide.Result
  | refs, _, .skip | refs, _, .memWrite =>
      some { refs, changed := [] }
  | refs, needed, .write index value =>
      if index ∉ needed then some { refs, changed := [] }
      else if index < refs.size then
        some { refs := refs.set! index value, changed := [index] }
      else none
  | refs, needed, .seq summary left right => do
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededInputs
        right.summary needed
      let leftResult ← evaluateCert registers refs leftNeeded left
      let rightResult ← evaluateCert registers leftResult.refs needed right
      pure { refs := rightResult.refs
             changed := Loom.Release.Symbolic.ActionWide.changedOutputs
               summary needed }
  | refs, needed, .ite summary _ joins thenCert elseCert => do
      let changed := Loom.Release.Symbolic.ActionWide.changedOutputs summary needed
      let thenResult ← evaluateCert registers refs changed thenCert
      let elseResult ← evaluateCert registers refs changed elseCert
      let mut output := refs
      if joins.length != changed.length then failure
      for (index, join) in changed.zip joins do
        let source ← registers[index]?
        guard (join.index == index && join.width == source.width)
        guard (thenResult.refs[index]?.isSome && elseResult.refs[index]?.isSome)
        output := output.set! index join.output
      pure { refs := output, changed }

private def actionCertNodeCount :
    Loom.Release.Symbolic.ActionWide.ActionCert → Nat
  | .skip | .memWrite | .write .. => 1
  | .seq _ left right | .ite _ _ _ left right =>
      actionCertNodeCount left + actionCertNodeCount right + 1

private def sourceActionNodeCount : Loom.Hw.Act → Nat
  | .skip | .memWrite .. | .write .. => 1
  | .seq left right | .ite _ left right =>
      sourceActionNodeCount left + sourceActionNodeCount right + 1

private def sourceExprNodeCount : {width : Nat} → Loom.Hw.Expr width → Nat
  | _, .lit _ | _, .reg _ _ => 1
  | _, .memRead _ _ address | _, .not address | _, .slice address _ _
  | _, .zext address _ | _, .sext address _ =>
      sourceExprNodeCount address + 1
  | _, .and left right | _, .or left right | _, .xor left right
  | _, .add left right | _, .sub left right | _, .shl left right
  | _, .shr left right | _, .eq left right | _, .ult left right
  | _, .slt left right =>
      sourceExprNodeCount left + sourceExprNodeCount right + 1
  | _, .mux condition yes no =>
      sourceExprNodeCount condition + sourceExprNodeCount yes +
        sourceExprNodeCount no + 1

private structure ExprStats where
  checks : Nat := 0
  nodes : Nat := 0
  maximum : Nat := 0

private def ExprStats.add (stats : ExprStats) (nodes : Nat) : ExprStats :=
  { checks := stats.checks + 1
    nodes := stats.nodes + nodes
    maximum := max stats.maximum nodes }

private def actionExprStats : Loom.Hw.Act → List Nat →
    Loom.Release.Symbolic.ActionWide.ActionCert → ExprStats
  | .skip, _, _ | .memWrite .., _, _ => {}
  | .write _ _ value, needed, .write index _ =>
      if index ∈ needed then
        ({} : ExprStats).add (sourceExprNodeCount value)
      else {}
  | .seq left right, needed, .seq _ leftCert rightCert =>
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededInputs
        rightCert.summary needed
      let leftStats := actionExprStats left leftNeeded leftCert
      let rightStats := actionExprStats right needed rightCert
      { checks := leftStats.checks + rightStats.checks
        nodes := leftStats.nodes + rightStats.nodes
        maximum := max leftStats.maximum rightStats.maximum }
  | .ite condition thenAction elseAction, needed,
      .ite summary _ _ thenCert elseCert =>
      let changed := Loom.Release.Symbolic.ActionWide.changedOutputs summary needed
      let conditionNodes := sourceExprNodeCount condition
      let thenStats := actionExprStats thenAction changed thenCert
      let elseStats := actionExprStats elseAction changed elseCert
      { checks := thenStats.checks + elseStats.checks + 1
        nodes := thenStats.nodes + elseStats.nodes + conditionNodes
        maximum := max conditionNodes (max thenStats.maximum elseStats.maximum) }
  | _, _, _ => {}

private def rulesExprStats : List Loom.Hw.Rule → List Nat →
    Loom.Release.Symbolic.ActionWide.RulesCert → ExprStats
  | [], _, _ => {}
  | rule :: rules, needed, cert :: certs =>
      let headNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
        certs needed
      let head := actionExprStats rule.body headNeeded cert
      let tail := rulesExprStats rules needed certs
      { checks := head.checks + tail.checks
        nodes := head.nodes + tail.nodes
        maximum := max head.maximum tail.maximum }
  | _, _, _ => {}

private unsafe def reportCoreStats (runtime : System.FilePath) : IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let stats := rulesExprStats design.rules (List.range design.regs.length) cert
  IO.println s!"actions={cert.foldl (fun n c => n + actionCertNodeCount c) 0}"
  IO.println s!"expression-checks={stats.checks}"
  IO.println s!"expression-nodes={stats.nodes}"
  IO.println s!"maximum-expression-nodes={stats.maximum}"
  let core := Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest
  IO.println s!"core-source-actions={sourceActionNodeCount core}"
  match core with
  | .ite _ countdown issue =>
      IO.println s!"core-countdown-actions={sourceActionNodeCount countdown}"
      IO.println s!"core-issue-actions={sourceActionNodeCount issue}"
  | _ => pure ()
  IO.println s!"retire-actions={sourceActionNodeCount Machines.Lnp64u.Hw.retireAct}"
  IO.println s!"rv-init-actions={sourceActionNodeCount Machines.Lnp64u.Hw.rvInit}"
  IO.println s!"rv-step-actions={sourceActionNodeCount Machines.Lnp64u.Hw.rvStep}"
  for domain in List.finRange Machines.Lnp64u.numDomains do
    IO.println s!"issue-{domain.val}-actions={sourceActionNodeCount
      (Machines.Lnp64u.Hw.issueFor Machines.Lnp64u.Demo.sysManifest domain)}"
    IO.println s!"retire-{domain.val}-actions={sourceActionNodeCount
      (Machines.Lnp64u.Hw.retireFor domain)}"
  return 0

private structure CoreCut where
  name : String
  source : String
  sourceValue : Act
  cert : String
  certValue : Loom.Release.Symbolic.ActionWide.ActionCert
  input : Array Loom.Release.Symbolic.Ref
  needed : List Nat
  size : Nat

private structure CoreCutState where
  retireNext : Nat := 0
  issueNext : Nat := 0
  revokeNext : Nat := 0
  cuts : Array CoreCut := #[]

private abbrev CoreCutM := StateT CoreCutState Option

private partial def collectCoreCuts (registers : Array RegDecl)
    (issueOrder : Array Machines.Lnp64u.DomainId)
    (source : Act) (cert : Loom.Release.Symbolic.ActionWide.ActionCert)
    (input : Array Loom.Release.Symbolic.Ref) (needed : List Nat)
    (certExpr : String) : CoreCutM (Nat × Loom.Release.Symbolic.ActionWide.Result) := do
  let size := sourceActionNodeCount source
  let state ← get
  let selected : Option (String × String × CoreCutState) :=
    if size == 15389 && state.retireNext < Machines.Lnp64u.numDomains then
      let domain := state.retireNext
      some ("retire" ++ toString domain,
        "Machines.Lnp64u.Hw.retireFor ⟨" ++ toString domain ++
          ", by decide⟩",
        { state with retireNext := state.retireNext + 1 })
    else if size == 2967 && state.issueNext < issueOrder.size then
      let domain := (issueOrder[state.issueNext]!).val
      some ("issue" ++ toString domain,
        "Machines.Lnp64u.Hw.issueFor Machines.Lnp64u.Demo.sysManifest ⟨" ++
          toString domain ++ ", by decide⟩",
        { state with issueNext := state.issueNext + 1 })
    else if size == 513 && state.revokeNext < 2 then
      let suffix := if state.revokeNext == 0 then "Init" else "Step"
      some ("rv" ++ suffix, "Machines.Lnp64u.Hw.rv" ++ suffix,
        { state with revokeNext := state.revokeNext + 1 })
    else none
  if let some (name, sourceExpr, nextState) := selected then
    let some result := evaluateCert registers input needed cert | failure
    let cut : CoreCut :=
      { name, source := sourceExpr, sourceValue := source, cert := certExpr,
        certValue := cert, input, needed, size }
    set { nextState with cuts := nextState.cuts.push cut }
    return (size, result)
  match source, cert with
  | .seq left right, .seq _ leftCert rightCert =>
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededInputs
        rightCert.summary needed
      let leftCertExpr := "Symbolic.ActionWide.ActionCert.seqLeft (" ++
        certExpr ++ ")"
      let rightCertExpr := "Symbolic.ActionWide.ActionCert.seqRight (" ++
        certExpr ++ ")"
      let (_, leftResult) ← collectCoreCuts registers issueOrder left leftCert input
        leftNeeded leftCertExpr
      let _ ← collectCoreCuts registers issueOrder right rightCert leftResult.refs
        needed rightCertExpr
      let some result := evaluateCert registers input needed cert | failure
      return (size, result)

  | .ite _ thenAction elseAction, .ite summary _ _ thenCert elseCert =>
      let changed := Loom.Release.Symbolic.ActionWide.changedOutputs summary needed
      let thenCertExpr := "Symbolic.ActionWide.ActionCert.iteThen (" ++
        certExpr ++ ")"
      let elseCertExpr := "Symbolic.ActionWide.ActionCert.iteElse (" ++
        certExpr ++ ")"
      let _ ← collectCoreCuts registers issueOrder thenAction thenCert input changed
        thenCertExpr
      let _ ← collectCoreCuts registers issueOrder elseAction elseCert input changed
        elseCertExpr
      let some result := evaluateCert registers input needed cert | failure
      return (size, result)
  | _, _ =>
      let some result := evaluateCert registers input needed cert | failure
      return (size, result)

private def cutRegistersToLean (registers : Array RegDecl) : String :=
  "#[" ++ String.intercalate ", " (registers.toList.map fun register =>
    "{ name := " ++ reprStr register.name ++ ", width := " ++
      toString register.width ++ ", init := BitVec.ofNat " ++
      toString register.width ++ " " ++ toString register.init.toNat ++ " }") ++
    "]"

private def cutSparseDeltaToLean
    (before after : Array Loom.Release.Symbolic.Ref) : String := Id.run do
  let mut expression := "Symbolic.ActionWide.SparseRefs.empty"
  for index in List.range (min before.size after.size) do
    if before[index]? != after[index]? then
      if let some afterRef := after[index]? then
        expression := "(" ++ expression ++ ").write " ++ toString index ++
          " (" ++ Tools.ReleaseCertGen.actionWideRefToLean afterRef ++ ")"
  pure expression

private def cutIndicesToBits (indices : List Nat) : Nat :=
  indices.foldl (fun bits index => bits ||| (1 <<< index)) 0

private def runtimeCheckpoints (program : Tools.RuntimeSsa.Program)
    (threshold : Nat := 64) : List Nat := Id.run do
  let mut counts := Array.replicate program.wires.size 0
  for wire in program.wires do
    for operand in wire.rhs.strings do
      if let some number := Loom.Release.Symbolic.wireNumber? operand then
        if number < counts.size then
          counts := counts.set! number (counts[number]! + 1)
  for register in program.regs do
    if let some number := Loom.Release.Symbolic.wireNumber? register.next then
      if number < counts.size then
        counts := counts.set! number (counts[number]! + 1)
  pure <| (List.range counts.size).filter fun number =>
    decide (counts[number]! >= threshold)

/-! ### Hash-consed state-DAG prototype

The generator chooses node numbers and traversal traces, but all of this data
is an untrusted witness. `ActionStateDag` checks the numbered trie transitions
inside the kernel. -/

private structure DagSpan where
  output : Nat := 0
  actionStart : Nat := 0
  actionEnd : Nat := 0
  writeStart : Nat := 0
  writeEnd : Nat := 0

private structure DagBuild where
  nodes : Array Loom.Release.Symbolic.ActionWide.RefStateNode :=
    #[.empty]
  nodeIds : Std.HashMap String Nat := {}
  writes : Std.HashMap String Nat := {}
  actionRoots : Array Nat := #[]
  writeRoots : Array Nat := #[]
  spans : Array DagSpan := #[]

private abbrev DagM := StateT DagBuild Option

private def dagNodeKey
    (node : Loom.Release.Symbolic.ActionWide.RefStateNode) : String :=
  reprStr node

private def dagWriteKey (depth input index : Nat)
    (value : Loom.Release.Symbolic.Ref) : String :=
  toString depth ++ ":" ++ toString input ++ ":" ++ toString index ++ ":" ++
    reprStr value

private def appendDagNode
    (node : Loom.Release.Symbolic.ActionWide.RefStateNode) : DagM Nat := do
  let state ← get
  if let some number := state.nodeIds.get? (dagNodeKey node) then
    return number
  let number := state.nodes.size
  set { state with nodes := state.nodes.push node }
  modify fun state =>
    { state with nodeIds := state.nodeIds.insert (dagNodeKey node) number }
  pure number

private partial def dagWrite (depth input index : Nat)
    (value : Loom.Release.Symbolic.Ref) : DagM Nat := do
  let key := dagWriteKey depth input index value
  if let some output := (← get).writes.get? key then return output
  let output ← if depth == 0 then
    appendDagNode (.leaf value)
  else do
    let state ← get
    let some node := state.nodes[input]? | failure
    let (oldZero, oldOne) := match node with
      | .empty => (0, 0)
      | .branch zeroChild oneChild => (zeroChild, oneChild)
      | .leaf _ => (0, 0)
    let bit := index.testBit (depth - 1)
    if bit then
      let newOne ← dagWrite (depth - 1) oldOne index value
      appendDagNode (.branch oldZero newOne)
    else
      let newZero ← dagWrite (depth - 1) oldZero index value
      appendDagNode (.branch newZero oldOne)
  let state ← get
  set { state with writes := state.writes.insert key output }
  pure output

private def recordDagWrite (root : Nat) : DagM Unit :=
  modify fun state => { state with writeRoots := state.writeRoots.push root }

private def recordDagAction (root : Nat) : DagM Unit :=
  modify fun state => { state with actionRoots := state.actionRoots.push root }

private partial def evaluateDag (source : Act) (input needed : Nat)
    (cert : Loom.Release.Symbolic.ActionWide.ActionCert) : DagM Nat := do
  let initialState ← get
  let spanIndex := initialState.spans.size
  let actionStart := initialState.actionRoots.size
  let writeStart := initialState.writeRoots.size
  set { initialState with spans := initialState.spans.push {} }
  let output ← match source, cert with
    | .skip, .skip | .memWrite .., .memWrite => pure input
    | .write _ _ _, .write index value =>
        if needed.testBit index then
          let root ← dagWrite 10 input index value
          recordDagWrite root
          pure root
        else pure input
    | .seq left right, .seq _ leftCert rightCert => do
        let leftNeeded := Loom.Release.Symbolic.ActionWide.neededBitsBefore
          rightCert.summary needed
        let middle ← evaluateDag left input leftNeeded leftCert
        evaluateDag right middle needed rightCert
    | .ite _ thenAction elseAction,
        .ite summary _ joins thenCert elseCert => do
        let changed := Loom.Release.Symbolic.ActionWide.changedBitsAt summary needed
        let _ ← evaluateDag thenAction input changed thenCert
        let _ ← evaluateDag elseAction input changed elseCert
        let mut root := input
        let mut remaining := changed
        for join in joins do
          guard (remaining.testBit join.index)
          root ← dagWrite 10 root join.index join.output
          recordDagWrite root
          remaining := remaining ^^^ (1 <<< join.index)
        guard (remaining == 0)
        pure root
    | _, _ => failure
  recordDagAction output
  let finalState ← get
  let span : DagSpan :=
    { output, actionStart, actionEnd := finalState.actionRoots.size,
      writeStart, writeEnd := finalState.writeRoots.size }
  set { finalState with spans := finalState.spans.set! spanIndex span }
  pure output

private def dagInitialRoot (registers : Array RegDecl)
    (input : Array Loom.Release.Symbolic.Ref) : DagM Nat := do
  let mut root := 0
  for index in [:min registers.size input.size] do
    let some register := registers[index]? | failure
    let some value := input[index]? | failure
    if value != .reg register.name then
      root ← dagWrite 10 root index value
  pure root

private structure DagLeafSpec where
  source : String
  cert : String
  trace : String
  input : Nat
  needed : Nat
  output : Nat
  actionRoots : Array Nat
  writeRoots : Array Nat
  size : Nat
  deriving Inhabited

/-- Render the compact write-root witness for one bounded action leaf. The
result is untrusted source data; `checkDagAction_sound` validates it. -/
private partial def dagTraceToLean (source : Act)
    (cert : Loom.Release.Symbolic.ActionWide.ActionCert) (needed : Nat)
    (writeRoots : Array Nat) (cursor : Nat := 0) : Option (String × Nat) := do
  match source, cert with
  | .skip, .skip | .memWrite .., .memWrite =>
      pure ("Symbolic.ActionWide.DagActionTrace.atom none", cursor)
  | .write _ _ _, .write index _ =>
      if needed.testBit index then
        let root ← writeRoots[cursor]?
        pure ("Symbolic.ActionWide.DagActionTrace.atom (some " ++
          toString root ++ ")", cursor + 1)
      else
        pure ("Symbolic.ActionWide.DagActionTrace.atom none", cursor)
  | .seq left right, .seq _ leftCert rightCert =>
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededBitsBefore
        rightCert.summary needed
      let (leftTrace, afterLeft) ← dagTraceToLean left leftCert leftNeeded
        writeRoots cursor
      let (rightTrace, afterRight) ← dagTraceToLean right rightCert needed
        writeRoots afterLeft
      pure ("Symbolic.ActionWide.DagActionTrace.seq (" ++ leftTrace ++
        ") (" ++ rightTrace ++ ")", afterRight)
  | .ite _ thenAction elseAction,
      .ite summary _ joins thenCert elseCert =>
      let changed := Loom.Release.Symbolic.ActionWide.changedBitsAt summary needed
      let (thenTrace, afterThen) ← dagTraceToLean thenAction thenCert changed
        writeRoots cursor
      let (elseTrace, afterElse) ← dagTraceToLean elseAction elseCert changed
        writeRoots afterThen
      let joinRoots := (writeRoots.extract afterElse
        (afterElse + joins.length)).toList
      guard (joinRoots.length == joins.length)
      let rootsText := "[" ++
        String.intercalate ", " (joinRoots.map toString) ++ "]"
      pure ("Symbolic.ActionWide.DagActionTrace.ite (" ++ thenTrace ++
        ") (" ++ elseTrace ++ ") " ++ rootsText,
        afterElse + joins.length)
  | _, _ => none

private partial def collectDagLeaves (spans : Array DagSpan)
    (allActionRoots allWriteRoots : Array Nat) (source : Act)
    (cert : Loom.Release.Symbolic.ActionWide.ActionCert) (input needed : Nat)
    (sourceExpr certExpr : String) (limit cursor : Nat) :
    Option (Nat × Nat × Array DagLeafSpec) := do
  let span ← spans[cursor]?
  let size := sourceActionNodeCount source
  if size ≤ limit then
    let writeRoots := allWriteRoots.extract span.writeStart span.writeEnd
    let (trace, afterTrace) ← dagTraceToLean source cert needed writeRoots
    guard (afterTrace == writeRoots.size)
    let leaf : DagLeafSpec :=
      { source := sourceExpr, cert := certExpr, trace, input, needed,
        output := span.output,
        actionRoots := allActionRoots.extract span.actionStart span.actionEnd,
        writeRoots,
        size }
    return (cursor + size, span.output, #[leaf])
  match source, cert with
  | .seq left right, .seq _ leftCert rightCert =>
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededBitsBefore
        rightCert.summary needed
      let leftSourceExpr := "Symbolic.ActionWide.seqLeftAction (" ++
        sourceExpr ++ ")"
      let rightSourceExpr := "Symbolic.ActionWide.seqRightAction (" ++
        sourceExpr ++ ")"
      let leftCertExpr := "Symbolic.ActionWide.ActionCert.seqLeft (" ++
        certExpr ++ ")"
      let rightCertExpr := "Symbolic.ActionWide.ActionCert.seqRight (" ++
        certExpr ++ ")"
      let (afterLeft, middle, leftLeaves) ← collectDagLeaves spans
        allActionRoots allWriteRoots left leftCert input leftNeeded
        leftSourceExpr leftCertExpr limit (cursor + 1)
      let (afterRight, output, rightLeaves) ← collectDagLeaves spans
        allActionRoots allWriteRoots right rightCert middle needed
        rightSourceExpr rightCertExpr limit afterLeft
      guard (afterRight == cursor + size)
      pure (afterRight, output, leftLeaves ++ rightLeaves)
  | .ite _ thenAction elseAction, .ite summary _ _ thenCert elseCert =>
      let changed := Loom.Release.Symbolic.ActionWide.changedBitsAt summary needed
      let thenSourceExpr := "Symbolic.ActionWide.iteThenAction (" ++
        sourceExpr ++ ")"
      let elseSourceExpr := "Symbolic.ActionWide.iteElseAction (" ++
        sourceExpr ++ ")"
      let thenCertExpr := "Symbolic.ActionWide.ActionCert.iteThen (" ++
        certExpr ++ ")"
      let elseCertExpr := "Symbolic.ActionWide.ActionCert.iteElse (" ++
        certExpr ++ ")"
      let (afterThen, _, thenLeaves) ← collectDagLeaves spans allActionRoots
        allWriteRoots thenAction thenCert input changed thenSourceExpr
        thenCertExpr limit (cursor + 1)
      let (afterElse, _, elseLeaves) ← collectDagLeaves spans allActionRoots
        allWriteRoots elseAction elseCert input changed elseSourceExpr
        elseCertExpr limit afterThen
      guard (afterElse == cursor + size)
      pure (afterElse, span.output, thenLeaves ++ elseLeaves)
  | _, _ => failure

private def dagRefToLean : Loom.Release.Symbolic.Ref → String
  | .wire number => "Symbolic.Ref.wire " ++ toString number
  | .reg name => "Symbolic.Ref.reg " ++ reprStr name

private def dagNodeToLean :
    Loom.Release.Symbolic.ActionWide.RefStateNode → String
  | .empty => "Symbolic.ActionWide.RefStateNode.empty"
  | .leaf value => "Symbolic.ActionWide.RefStateNode.leaf (" ++
      dagRefToLean value ++ ")"
  | .branch zeroChild oneChild =>
      "Symbolic.ActionWide.RefStateNode.branch " ++ toString zeroChild ++ " " ++
        toString oneChild

private partial def balancedDagRopeExpr : List String → String
  | [] => "Symbolic.ActionWide.RefStateNode.empty |> List.singleton |> Rope.leaf"
  | [name] => name
  | names =>
      let rec pair : List String → List String
        | left :: right :: rest =>
            ("(Rope.node " ++ left ++ " " ++ right ++ ")") :: pair rest
        | [last] => [last]
        | [] => []
      balancedDagRopeExpr (pair names)

private unsafe def generateCoreDagProbe (runtime output : System.FilePath)
    (cutIndex : Nat) : IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some certs := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program | return 1
  let registers := design.regs.toArray
  let initial := registers.map fun register =>
    Loom.Release.Symbolic.Ref.reg register.name
  let some refillCert := certs[0]? | return 1
  let needed := List.range registers.size
  let refillNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    certs.tail needed
  let some refillResult := evaluateCert registers initial refillNeeded refillCert
    | return 1
  let some coreCert := certs[1]? | return 1
  let coreNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    (certs.drop 2) needed
  let issueOrder := (Machines.Lnp64u.Hw.schedOrder
    Machines.Lnp64u.Demo.sysManifest).toArray
  let some (_, cutsState) := (collectCoreCuts registers issueOrder
      (Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest) coreCert
      refillResult.refs coreNeeded "actionCertNode15158").run {}
    | return 1
  let some cut := cutsState.cuts[cutIndex]? | return 1
  let neededBits := cutIndicesToBits cut.needed
  let some (inputRoot, initialState) :=
      (dagInitialRoot registers cut.input).run {} | return 1
  let some (outputRoot, finalState) :=
      (evaluateDag cut.sourceValue inputRoot neededBits cut.certValue).run
        initialState | return 1
  let leafLimit := 128
  let some (afterLeaves, leafOutput, leaves) := collectDagLeaves finalState.spans
      finalState.actionRoots finalState.writeRoots cut.sourceValue cut.certValue
      inputRoot neededBits cut.source cut.cert leafLimit 0 | return 1
  unless afterLeaves == cut.size && leafOutput == outputRoot do return 1
  let leafSize := 64
  let chunks := finalState.nodes.toList.toChunks leafSize
  let leafNames := (List.range chunks.length).map fun index =>
    "dagStateLeaf" ++ pad4 index
  let mut leafDeclarations : Array String := #[]
  for (index, chunk) in (List.range chunks.length).zip chunks do
    leafDeclarations := leafDeclarations.push <| "def dagStateLeaf" ++ pad4 index ++
      " : Rope (List Symbolic.ActionWide.RefStateNode) := Rope.leaf [" ++
      String.intercalate ", " (chunk.map dagNodeToLean) ++ "]\n"
  let mut resolverDeclarations : Array String := #[]
  for index in List.range chunks.length do
    let some path := Loom.Release.Symbolic.balancedPath? chunks.length index
      | return 1
    let pathText := "[" ++ String.intercalate ", "
      (path.map fun bit => if bit then "true" else "false") ++ "]"
    resolverDeclarations := resolverDeclarations.push <|
      "theorem dagStateResolveLeaf" ++ pad4 index ++ " (offset : Nat) :\n" ++
      "    dagStateNodes.resolve? ⟨" ++ pathText ++ ", offset⟩ =\n" ++
      "      (dagStateLeaf" ++ pad4 index ++
      ").resolve? ⟨[], offset⟩ := rfl\n"
  let dataBatchSize := 128
  let nodeBatches := leafDeclarations.toList.toChunks dataBatchSize
  let resolverBatches := resolverDeclarations.toList.toChunks dataBatchSize
  let modulePrefix := "GeneratedRelease.Lnp64u.DagCut" ++ pad3 cutIndex
  let nodeImports := String.intercalate "\n" <|
    (List.range nodeBatches.length).map fun index =>
      "import " ++ modulePrefix ++ "Nodes" ++ pad3 index
  let resolverImports := String.intercalate "\n" <|
    (List.range resolverBatches.length).map fun index =>
      "import " ++ modulePrefix ++ "Resolvers" ++ pad3 index
  let dataText :=
    "-- Generated hash-consed action-state witness; DO NOT EDIT.\n" ++
    nodeImports ++ "\n\n" ++
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Hw Loom.Release\n\nnoncomputable section\n\n" ++
    "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\n" ++
    "def dagStateNodes := " ++ balancedDagRopeExpr leafNames ++ "\n\n" ++
    "def dagStateTable : Symbolic.ActionWide.RefStateTable := " ++
      "{ leafSize := " ++ toString leafSize ++ ", leafCount := " ++
      toString chunks.length ++ ", emptyRoot := 0 }\n" ++
    "def dagInputRoot : Nat := " ++ toString inputRoot ++ "\n" ++
    "def dagOutputRoot : Nat := " ++ toString outputRoot ++ "\n\n" ++
    "def dagCutRegisters : Array RegDecl := " ++
      cutRegistersToLean registers ++ "\n" ++
    "noncomputable def dagCutInput : Symbolic.ActionWide.SparseRefs := " ++
      cutSparseDeltaToLean initial cut.input ++ "\n\n" ++
    "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
  let dataModule := modulePrefix ++ "Data"
  -- Compact checks are ordinary independent declarations, so Lean can verify
  -- a sizeable batch asynchronously while sharing the imported SSA tables.
  let proofLeafBatchSize := 8
  let proofLeafBatches := leaves.toList.toChunks proofLeafBatchSize
  let leafImports := String.intercalate "\n" <|
    (List.range proofLeafBatches.length).map fun index =>
      "import GeneratedRelease.Lnp64u.DagCut" ++ pad3 cutIndex ++
        "Leaf" ++ pad3 index
  let leafRegistrations := String.intercalate "\n" <|
    (List.range leaves.size).map fun index =>
      let leaf := leaves[index]!
      "dag_action_leaf dagCutLeaf" ++ pad3 index ++ "Evidence " ++
        toString leaf.size ++ " " ++ toString leaf.writeRoots.size
  let proofText :=
    "-- Generated hash-consed action-state proof; DO NOT EDIT.\n" ++
    "import " ++ dataModule ++ "\n" ++
    resolverImports ++ "\n" ++
    leafImports ++ "\n" ++
    "import GeneratedRelease.Lnp64u.FastIndexedRoot\n" ++
    "import GeneratedRelease.Lnp64u.ActionCert\n" ++
    "import Loom.Release.SymbolicDecide\n" ++
    "import Machines.Lnp64u.Hw.Core\n" ++
    "import Machines.Lnp64u.Hw.Demo\n" ++
    "import Machines.Lnp64u.Theorems.ReleaseOrder\n\n" ++
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Hw Loom.Release\n\nnoncomputable section\n\n" ++
    "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\n" ++
    "indexed_expr_checkpoints " ++
      String.intercalate " " (runtimeCheckpoints program |>.map toString) ++
      "\n" ++
    "dag_action_roots " ++
      String.intercalate " " (finalState.actionRoots.toList.map toString) ++
      "\n" ++
    "dag_write_roots " ++
      String.intercalate " " (finalState.writeRoots.toList.map toString) ++
      "\n" ++ leafRegistrations ++ "\n\n" ++
    "theorem dagCutEvidence :\n" ++
    "    Symbolic.ActionWide.DagBitSparseEvidence " ++
      "fastIndexedWireTree fastWireTable dagStateNodes dagStateTable " ++
      "dagCutRegisters (" ++ cut.source ++ ") dagInputRoot " ++
      toString neededBits ++ " (" ++ cut.cert ++ ") dagOutputRoot :=\n" ++
    "  dag_sparse_evidence_decide\n\n" ++
    "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
  let dataPath := System.FilePath.mk
    ((output.toString.dropEnd 5).toString ++ "Data.lean")
  let basePath := (output.toString.dropEnd 5).toString
  for (index, batch) in (List.range nodeBatches.length).zip nodeBatches do
    let nodeText :=
      "-- Generated hash-consed action-state node shard; DO NOT EDIT.\n" ++
      "import Loom.Release.ActionStateDag\n\n" ++
      "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
      "open Loom.Hw Loom.Release\n\nnoncomputable section\n\n" ++
      "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\n" ++
      String.intercalate "\n" batch ++ "\n" ++
      "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged (System.FilePath.mk <| basePath ++ "Nodes" ++
      pad3 index ++ ".lean") nodeText
  writeIfChanged dataPath dataText
  for (index, batch) in (List.range resolverBatches.length).zip resolverBatches do
    let resolverText :=
      "-- Generated hash-consed action-state resolver shard; DO NOT EDIT.\n" ++
      "import " ++ dataModule ++ "\n\n" ++
      "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
      "open Loom.Hw Loom.Release\n\nnoncomputable section\n\n" ++
      "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\n" ++
      String.intercalate "\n" batch ++ "\n" ++
      "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged (System.FilePath.mk <| basePath ++ "Resolvers" ++
      pad3 index ++ ".lean") resolverText
  for (batchIndex, batch) in
      (List.range proofLeafBatches.length).zip proofLeafBatches do
    let mut theoremTexts : Array String := #[]
    for (localIndex, leaf) in (List.range batch.length).zip batch do
      let index := batchIndex * proofLeafBatchSize + localIndex
      let traceName := "dagCutLeaf" ++ pad3 index ++ "Trace"
      let checkName := "dagCutLeaf" ++ pad3 index ++ "Check"
      theoremTexts := theoremTexts.push <|
        "def " ++ traceName ++
          " : Symbolic.ActionWide.DagActionTrace :=\n  " ++ leaf.trace ++
          "\n\n" ++
        "theorem " ++ checkName ++ " :\n" ++
        "    Symbolic.ActionWide.checkDagAction fastIndexedWireTree " ++
          "fastWireTable dagStateNodes dagStateTable dagCutRegisters (" ++
          leaf.source ++ ") " ++ toString leaf.input ++ " " ++
          toString leaf.needed ++ " (" ++ leaf.cert ++ ") " ++ traceName ++
          " = some " ++ toString leaf.output ++ " := by\n" ++
        "  rfl\n\n" ++
        "theorem dagCutLeaf" ++ pad3 index ++ "Evidence :\n" ++
        "    Symbolic.ActionWide.DagBitSparseEvidence fastIndexedWireTree " ++
          "fastWireTable dagStateNodes dagStateTable dagCutRegisters (" ++
          leaf.source ++ ") " ++ toString leaf.input ++ " " ++
          toString leaf.needed ++ " (" ++ leaf.cert ++ ") " ++
          toString leaf.output ++ " :=\n" ++
        "  Symbolic.ActionWide.checkDagAction_sound " ++ checkName ++ "\n"
    let leafText :=
      "-- Generated independent DAG action leaves; DO NOT EDIT.\n" ++
      "import " ++ dataModule ++ "\n" ++
      "import GeneratedRelease.Lnp64u.FastIndexedRoot\n" ++
      "import GeneratedRelease.Lnp64u.ActionCert\n" ++
      "import Machines.Lnp64u.Hw.Core\n" ++
      "import Machines.Lnp64u.Hw.Demo\n" ++
      "import Machines.Lnp64u.Theorems.ReleaseOrder\n\n" ++
      "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
      "open Loom.Hw Loom.Release\n\nnoncomputable section\n\n" ++
      "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n" ++
      "\n" ++
      String.intercalate "\n" theoremTexts.toList ++ "\n" ++
      "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
    let leafPath := System.FilePath.mk ((output.toString.dropEnd 5).toString ++
      "Leaf" ++ pad3 batchIndex ++ ".lean")
    writeIfChanged leafPath leafText
  writeIfChanged output proofText
  IO.eprintln (s!"dag cut {cutIndex}: actions={finalState.actionRoots.size} " ++
    s!"writes={finalState.writeRoots.size} nodes={finalState.nodes.size} " ++
    s!"nodeShards={nodeBatches.length} resolverShards={resolverBatches.length} " ++
    s!"leaves={leaves.size} leafModules={proofLeafBatches.length}")
  return 0

private unsafe def generateCoreCuts (runtime outputDir : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some certs := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program | return 1
  let registers := design.regs.toArray
  let checkpoints := runtimeCheckpoints program
  let initial := registers.map fun register =>
    Loom.Release.Symbolic.Ref.reg register.name
  let some refillCert := certs[0]? | return 1
  let needed := List.range registers.size
  let refillNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    certs.tail needed
  let some refillResult := evaluateCert registers initial refillNeeded refillCert
    | return 1
  let some coreCert := certs[1]? | return 1
  let coreNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    (certs.drop 2) needed
  let issueOrder := (Machines.Lnp64u.Hw.schedOrder
    Machines.Lnp64u.Demo.sysManifest).toArray
  let some (_, state) := (collectCoreCuts registers issueOrder
      (Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest) coreCert
      refillResult.refs coreNeeded "actionCertNode15158").run {}
    | return 1
  unless state.retireNext == 4 && state.issueNext == 4 &&
      state.revokeNext == 2 && state.cuts.size == 10 do
    IO.eprintln (s!"unexpected cut coverage: retire={state.retireNext} " ++
      s!"issue={state.issueNext} revoke={state.revokeNext} total={state.cuts.size}")
    return 1
  IO.FS.createDirAll outputDir
  for index in [:state.cuts.size] do
    let some cut := state.cuts[index]? | return 1
    let suffix := pad3 index
    let source := "-- Generated independent core-action certificate; DO NOT EDIT.\n" ++
      "import GeneratedRelease.Lnp64u.FastIndexedRoot\n" ++
      "import GeneratedRelease.Lnp64u.ActionCert\n" ++
      "import Loom.Release.SymbolicDecide\n" ++
      "import Machines.Lnp64u.Hw.Core\n" ++
      "import Machines.Lnp64u.Hw.Demo\n\n" ++
      "import Machines.Lnp64u.Theorems.ReleaseOrder\n\n" ++
      "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
      "open Loom.Hw Loom.Release\n\nnoncomputable section\n\n" ++
      "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\n" ++
      "indexed_expr_checkpoints " ++
        String.intercalate " " (checkpoints.map toString) ++ "\n\n" ++
      "def cutRegisters" ++ suffix ++ " : Array RegDecl := " ++
        cutRegistersToLean registers ++ "\n" ++
      "noncomputable def cutInput" ++ suffix ++
        " : Symbolic.ActionWide.SparseRefs := " ++
        cutSparseDeltaToLean initial cut.input ++
        "\n" ++
      "def cutCert" ++ suffix ++ " : Symbolic.ActionWide.ActionCert := " ++
        cut.cert ++ "\n\n" ++
      "theorem " ++ cut.name ++ "Evidence :\n" ++
      "    ∃ result, Symbolic.ActionWide.BitSparseEvidence fastIndexedWireTree " ++
        "fastWireTable cutRegisters" ++ suffix ++ " (" ++ cut.source ++ ") " ++
        "cutInput" ++ suffix ++ " " ++ toString (cutIndicesToBits cut.needed) ++
        " cutCert" ++ suffix ++ " result :=\n" ++
      "  sparse_evidence_exists\n\n" ++
      "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged (outputDir / ("CoreCut" ++ suffix ++ ".lean")) source
    IO.println s!"cut {suffix} {cut.name}: {cut.size} actions"
  return 0

private def resultToLean (result : Loom.Release.Symbolic.ActionWide.Result) :
    String :=
  "{ refs := " ++ Tools.ReleaseCertGen.actionWideRefsToLean result.refs ++
    ", changed := [" ++ String.intercalate ", "
      (result.changed.map toString) ++ "] }"

private structure EvidenceBuild where
  source : String
  cert : String
  input : String
  needed : String
  result : String
  evidence : String
  locals : Array String := #[]
  size : Nat

private def transportEvidence (build : EvidenceBuild) (source input needed cert :
    String) : String :=
  "(Symbolic.ActionWide.SparseEvidence.transport " ++
    "(action := " ++ build.source ++ ") (action' := " ++ source ++ ") " ++
    "(refs := " ++ build.input ++ ") (refs' := " ++ input ++ ") " ++
    "(needed := " ++ build.needed ++ ") (needed' := " ++ needed ++ ") " ++
    "(cert := " ++ build.cert ++ ") (cert' := " ++ cert ++ ") " ++
    "(result := " ++ build.result ++ ") (result' := " ++ build.result ++ ") " ++
    "rfl rfl (kernel_decide) (kernel_decide) rfl (" ++
    build.evidence ++ "))"

private structure EvidenceGenState where
  next : Nat := 0
  resultNext : Nat := 0
  aliasNext : Nat := 0
  neededNext : Nat := 0
  declarations : Array String := #[]

private abbrev EvidenceGenM := StateT EvidenceGenState Option

private def emitEvidenceResult (expression : String) :
    EvidenceGenM (String × String) := do
  let state ← get
  let name := "actionResult" ++ toString state.resultNext
  let declaration := "  let " ++ name ++
    " : Symbolic.ActionWide.SparseResult := " ++ expression ++ "\n"
  set ({ next := state.next, resultNext := state.resultNext + 1
         aliasNext := state.aliasNext, neededNext := state.neededNext
         declarations := state.declarations } : EvidenceGenState)
  pure (name, declaration)

private def emitEvidenceAliases (source cert : String) :
    EvidenceGenM (String × String × String) := do
  let state ← get
  let suffix := toString state.aliasNext
  let sourceName := "actionSourceAlias" ++ suffix
  let certName := "actionCertAlias" ++ suffix
  let declaration :=
    "  let " ++ sourceName ++ " : Act := " ++ source ++ "\n" ++
    "  let " ++ certName ++
      " : Symbolic.ActionWide.ActionCert := " ++ cert ++ "\n"
  set ({ next := state.next, resultNext := state.resultNext
         aliasNext := state.aliasNext + 1, neededNext := state.neededNext
         declarations := state.declarations } : EvidenceGenState)
  pure (sourceName, certName, declaration)

private def emitEvidenceNeeded (expression : String) :
    EvidenceGenM (String × String) := do
  let state ← get
  let name := "actionNeeded" ++ toString state.neededNext
  let declaration := "  let " ++ name ++
    " : List Nat := " ++ expression ++ "\n"
  set ({ next := state.next, resultNext := state.resultNext
         aliasNext := state.aliasNext, neededNext := state.neededNext + 1
         declarations := state.declarations } : EvidenceGenState)
  pure (name, declaration)

private def refsDeltaToLean (base : String)
    (before after : Array Loom.Release.Symbolic.Ref) : String := Id.run do
  let mut expression := base
  for index in List.range (min before.size after.size) do
    if let some beforeRef := before[index]? then
      if let some afterRef := after[index]? then
        if beforeRef != afterRef then
          expression := "(" ++ expression ++ ").set! " ++ toString index ++
            " (" ++ Tools.ReleaseCertGen.actionWideRefToLean afterRef ++ ")"
  pure expression

private def sparseDeltaToLean (base : String)
    (before after : Array Loom.Release.Symbolic.Ref) : String := Id.run do
  let mut expression := base
  for index in List.range (min before.size after.size) do
    if let some beforeRef := before[index]? then
      if let some afterRef := after[index]? then
        if beforeRef != afterRef then
          expression := "(" ++ expression ++ ").write " ++ toString index ++
            " (" ++ Tools.ReleaseCertGen.actionWideRefToLean afterRef ++ ")"
  pure expression

private def registersToLean (registers : Array RegDecl) : String :=
  "#[" ++ String.intercalate ", " (registers.toList.map fun register =>
    "{ name := " ++ reprStr register.name ++ ", width := " ++
      toString register.width ++ ", init := BitVec.ofNat " ++
      toString register.width ++ " " ++ toString register.init.toNat ++ " }") ++
    "]"

private def indicesToBits (indices : List Nat) : Nat :=
  indices.foldl (fun bits index => bits ||| (1 <<< index)) 0

private def evidenceType (source input needed cert result : String) : String :=
  "Symbolic.ActionWide.SparseEvidence indexedWireTree wireTable " ++
    "actionRegisters (" ++ source ++ ") (" ++ input ++ ") (" ++
    needed ++ ") (" ++ cert ++ ") (" ++ result ++ ")"

private def mergeLocals (left right : Array String) : Array String :=
  right.foldl (fun merged declaration =>
    if merged.contains declaration then merged else merged.push declaration) left

private def emitEvidenceContext (source cert input needed : String)
    (locals : Array String) :
    EvidenceGenM (String × String × String × String) := do
  let state ← get
  let suffix := toString state.aliasNext
  let name := "actionContext" ++ suffix
  let declaration :=
    "noncomputable def " ++ name ++ " : ActionEvidenceContext :=\n" ++
    String.join locals.toList ++
    "  { source := " ++ source ++ ", cert := " ++ cert ++
      ", input := " ++ input ++ ", needed := " ++ needed ++ " }\n"
  set ({ next := state.next, resultNext := state.resultNext
         aliasNext := state.aliasNext + 1, neededNext := state.neededNext
         declarations := state.declarations.push declaration } : EvidenceGenState)
  pure (name ++ ".source", name ++ ".cert", name ++ ".input",
    name ++ ".needed")

private def emitEvidenceBoundary (build : EvidenceBuild) (direct := false) :
    EvidenceGenM EvidenceBuild := do
  let state ← get
  let suffix := toString state.next
  let dataName := "segmentData" ++ suffix
  let theoremName := "segmentEvidence" ++ suffix
  let proof := if direct then
      " := (.direct (kernel_decide))\n"
    else
      " := by\n" ++
      String.join build.locals.toList ++
      "  exact Symbolic.ActionWide.SparseEvidence.transport " ++
        "(action := " ++ build.source ++ ") " ++
        "(action' := " ++ dataName ++ ".source) " ++
        "(refs := " ++ build.input ++ ") " ++
        "(refs' := " ++ dataName ++ ".input) " ++
        "(needed := " ++ build.needed ++ ") " ++
        "(needed' := " ++ dataName ++ ".needed) " ++
        "(cert := " ++ build.cert ++ ") " ++
        "(cert' := " ++ dataName ++ ".cert) " ++
        "(result := " ++ build.result ++ ") " ++
        "(result' := " ++ dataName ++ ".result) " ++
        "rfl rfl (kernel_decide) (kernel_decide) rfl (" ++
        build.evidence ++ ")\n"
  let declaration :=
    "noncomputable def " ++ dataName ++ " : ActionEvidenceData :=\n" ++
    String.join build.locals.toList ++
    "  { source := " ++ build.source ++ ", cert := " ++ build.cert ++
      ", input := " ++ build.input ++ ", needed := " ++ build.needed ++
      ", result := " ++ build.result ++ " }\n" ++
    "theorem " ++ theoremName ++ " :\n    " ++
      evidenceType (dataName ++ ".source") (dataName ++ ".input")
        (dataName ++ ".needed") (dataName ++ ".cert")
        (dataName ++ ".result") ++ proof
  set ({ next := state.next + 1, resultNext := state.resultNext
         aliasNext := state.aliasNext, neededNext := state.neededNext
         declarations := state.declarations.push declaration } : EvidenceGenState)
  pure { source := dataName ++ ".source", cert := dataName ++ ".cert"
         input := dataName ++ ".input", needed := dataName ++ ".needed"
         result := dataName ++ ".result", evidence := theoremName
         locals := #[], size := 1 }

private partial def buildEvidence (registers : Array RegDecl)
    (source : Act) (cert : Loom.Release.Symbolic.ActionWide.ActionCert)
    (inputRefs : Array Loom.Release.Symbolic.Ref) (neededValues : List Nat)
    (sourceExpr certExpr inputExpr neededExpr : String)
    (inheritedLocals : Array String) (pathDepth : Nat) :
    EvidenceGenM EvidenceBuild := do
  let (sourceExpr, certExpr, inputExpr, neededExpr, inheritedLocals) ←
    if inheritedLocals.size ≥ 32 then do
      let (source, cert, input, needed) ← emitEvidenceContext sourceExpr certExpr
        inputExpr neededExpr inheritedLocals
      pure (source, cert, input, needed, #[])
    else pure (sourceExpr, certExpr, inputExpr, neededExpr, inheritedLocals)
  let (sourceExpr, certExpr, aliasLocals, pathDepth) ←
    if pathDepth ≥ 8 then do
      let (sourceName, certName, declaration) ←
        emitEvidenceAliases sourceExpr certExpr
      pure (sourceName, certName, #[declaration], 0)
    else pure (sourceExpr, certExpr, #[], pathDepth)
  let (neededExpr, neededLocal) ← emitEvidenceNeeded neededExpr
  let prefixLocals := (mergeLocals inheritedLocals aliasLocals).push neededLocal
  let some _result := evaluateCert registers inputRefs neededValues cert | failure
  let changedExpr := "Symbolic.ActionWide.changedOutputs (" ++ certExpr ++
    ").claimedSummary (" ++ neededExpr ++ ")"
  match source, cert with
  | .skip, .skip =>
      let (resultExpr, resultLocal) ← emitEvidenceResult
        ("{ refs := " ++ inputExpr ++ ", changed := [] }")
      let build : EvidenceBuild :=
        { source := sourceExpr, cert := certExpr, input := inputExpr
          needed := neededExpr, result := resultExpr
          evidence := "(.skip)"
          locals := prefixLocals.push resultLocal, size := 1 }
      pure build
  | .memWrite .., .memWrite =>
      let (resultExpr, resultLocal) ← emitEvidenceResult
        ("{ refs := " ++ inputExpr ++ ", changed := [] }")
      let build : EvidenceBuild :=
        { source := sourceExpr, cert := certExpr, input := inputExpr
          needed := neededExpr, result := resultExpr
          evidence := "(.memWrite)"
          locals := prefixLocals.push resultLocal, size := 1 }
      pure build
  | .write .., .write index valueRef =>
      let used := index ∈ neededValues
      let refsExpr := if used then
          "(" ++ inputExpr ++ ").write " ++ toString index ++ " (" ++
            Tools.ReleaseCertGen.actionWideRefToLean valueRef ++ ")"
        else inputExpr
      let changed := if used then "[" ++ toString index ++ "]" else "[]"
      let (resultExpr, resultLocal) ← emitEvidenceResult
        ("{ refs := " ++ refsExpr ++ ", changed := " ++ changed ++ " }")
      let evidence := if used then
          "(Symbolic.ActionWide.SparseEvidence.writeNeeded " ++
            "(wires := indexedWireTree) (table := wireTable) " ++
            "(registers := actionRegisters) " ++
            "(kernel_decide_inline) (kernel_decide_inline) " ++
            "(indexed_expr_decide))"
        else "(Symbolic.ActionWide.SparseEvidence.writeUnused " ++
          "(wires := indexedWireTree) (table := wireTable) " ++
          "(registers := actionRegisters) " ++
          "(kernel_decide_inline) (kernel_decide_inline))"
      let build : EvidenceBuild :=
        { source := sourceExpr, cert := certExpr, input := inputExpr
          needed := neededExpr, result := resultExpr, evidence
          locals := prefixLocals.push resultLocal, size := 1 }
      pure build
  | .seq left right, .seq _ leftCert rightCert =>
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededInputs
        rightCert.summary neededValues
      let leftSourceExpr := "Symbolic.ActionWide.seqLeftAction (" ++
        sourceExpr ++ ")"
      let rightSourceExpr := "Symbolic.ActionWide.seqRightAction (" ++
        sourceExpr ++ ")"
      let leftCertExpr := "Symbolic.ActionWide.ActionCert.seqLeft (" ++
        certExpr ++ ")"
      let rightCertExpr := "Symbolic.ActionWide.ActionCert.seqRight (" ++
        certExpr ++ ")"
      let leftNeededExpr := "Symbolic.ActionWide.neededInputs (" ++
        rightCertExpr ++ ").summary (" ++ neededExpr ++ ")"
      let leftBuild ← buildEvidence registers left leftCert inputRefs leftNeeded
        leftSourceExpr leftCertExpr inputExpr leftNeededExpr prefixLocals
        (pathDepth + 1)
      let some leftResult := evaluateCert registers inputRefs leftNeeded leftCert
        | failure
      let rightInputExpr := "(" ++ leftBuild.result ++ ").refs"
      let rightBuild ← buildEvidence registers right rightCert leftResult.refs
        neededValues rightSourceExpr rightCertExpr rightInputExpr neededExpr
        (mergeLocals prefixLocals leftBuild.locals)
        (pathDepth + 1)
      let (resultExpr, resultLocal) ← emitEvidenceResult ("{ refs := (" ++ rightBuild.result ++
        ").refs, changed := " ++ changedExpr ++ " }")
      let leftEvidence := transportEvidence leftBuild leftSourceExpr inputExpr
        leftNeededExpr leftCertExpr
      let rightEvidence := transportEvidence rightBuild rightSourceExpr
        rightInputExpr neededExpr rightCertExpr
      let proof :=
        "(Symbolic.ActionWide.SparseEvidence.seqProjected " ++
          "(wires := indexedWireTree) (table := wireTable) " ++
          "(registers := actionRegisters) " ++
          "(action := " ++ sourceExpr ++ ") (cert := " ++ certExpr ++ ") " ++
          "(leftResult := " ++ leftBuild.result ++ ") " ++
          "(rightResult := " ++ rightBuild.result ++ ") " ++
          "(kernel_decide_inline) (kernel_decide_inline) " ++
          "(kernel_decide_inline) (" ++
          leftEvidence ++ ") (" ++ rightEvidence ++ "))"
      let build : EvidenceBuild :=
        { source := sourceExpr, cert := certExpr, input := inputExpr
          needed := neededExpr, result := resultExpr, evidence := proof
          locals := (mergeLocals (mergeLocals prefixLocals leftBuild.locals)
            rightBuild.locals).push resultLocal
          size := leftBuild.size + rightBuild.size + 1 }
      if build.size ≥ 32 then emitEvidenceBoundary build else pure build
  | .ite _condition thenAction elseAction,
      .ite _ _ _joins thenCert elseCert =>
      let changed := Loom.Release.Symbolic.ActionWide.changedOutputs
        cert.claimedSummary neededValues
      let thenSourceExpr := "Symbolic.ActionWide.iteThenAction (" ++
        sourceExpr ++ ")"
      let elseSourceExpr := "Symbolic.ActionWide.iteElseAction (" ++
        sourceExpr ++ ")"
      let thenCertExpr := "Symbolic.ActionWide.ActionCert.iteThen (" ++
        certExpr ++ ")"
      let elseCertExpr := "Symbolic.ActionWide.ActionCert.iteElse (" ++
        certExpr ++ ")"
      let changedNeededExpr := "Symbolic.ActionWide.changedOutputs (" ++
        certExpr ++ ").claimedSummary (" ++ neededExpr ++ ")"
      let thenBuild ← buildEvidence registers thenAction thenCert inputRefs changed
        thenSourceExpr thenCertExpr inputExpr changedNeededExpr prefixLocals
        (pathDepth + 1)
      let elseBuild ← buildEvidence registers elseAction elseCert inputRefs changed
        elseSourceExpr elseCertExpr inputExpr changedNeededExpr prefixLocals
        (pathDepth + 1)
      let refsExpr := "Symbolic.ActionWide.applySparseJoins (" ++ inputExpr ++
        ") (" ++ certExpr ++ ").iteJoins"
      let (resultExpr, resultLocal) ← emitEvidenceResult ("{ refs := " ++ refsExpr ++
        ", changed := " ++ changedExpr ++ " }")
      let thenEvidence := transportEvidence thenBuild thenSourceExpr inputExpr
        changedNeededExpr thenCertExpr
      let elseEvidence := transportEvidence elseBuild elseSourceExpr inputExpr
        changedNeededExpr elseCertExpr
      let proof :=
        "(Symbolic.ActionWide.SparseEvidence.iteProjected " ++
          "(wires := indexedWireTree) (table := wireTable) " ++
          "(registers := actionRegisters) " ++
          "(action := " ++ sourceExpr ++ ") (cert := " ++ certExpr ++ ") " ++
          "(thenResult := " ++ thenBuild.result ++ ") " ++
          "(elseResult := " ++ elseBuild.result ++ ") " ++
          "(kernel_decide_inline) (kernel_decide_inline) " ++
          "(kernel_decide_inline) (indexed_expr_decide) (" ++
          thenEvidence ++ ") (" ++ elseEvidence ++
          ") (kernel_decide_inline))"
      let build : EvidenceBuild :=
        { source := sourceExpr, cert := certExpr, input := inputExpr
          needed := neededExpr, result := resultExpr, evidence := proof
          locals := (mergeLocals (mergeLocals prefixLocals thenBuild.locals)
            elseBuild.locals).push resultLocal
          size := thenBuild.size + elseBuild.size + 1 }
      if build.size ≥ 32 then emitEvidenceBoundary build else pure build
  | _, _ => failure

private unsafe def generateCoreEvidence (runtime output : System.FilePath)
    (split : Bool := false) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let checkpoints := runtimeCheckpoints program
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program | return 1
  let registers := design.regs.toArray
  let needed := List.range registers.size
  let initial := registers.map fun register =>
    Loom.Release.Symbolic.Ref.reg register.name
  let some refillCert := cert[0]? | return 1
  let refillNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs cert.tail needed
  let some refillResult := evaluateCert registers initial refillNeeded refillCert
    | return 1
  let some coreCert := cert[1]? | return 1
  let coreNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    (cert.drop 2) needed
  let initialState : EvidenceGenState := {}
  let some (rootBuild, state) := (buildEvidence registers
      (Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest) coreCert
      refillResult.refs coreNeeded
      "Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest"
      "actionCertNode15158"
      "coreEvidenceInput" "coreEvidenceNeeded" #[] 0).run
        initialState | return 1
  let some (rootBuild, state) := (emitEvidenceBoundary rootBuild false).run state
    | return 1
  IO.eprintln s!"generated {state.next} bounded evidence segments"
  let imports := "-- Generated bounded core evidence; DO NOT EDIT.\n" ++
    "import GeneratedRelease.Lnp64u.ActionCert\n" ++
    "import GeneratedRelease.Lnp64u.SemanticRoot\n" ++
    "import Loom.Release.KernelDecide\n" ++
    "import Loom.Release.SymbolicDecide\n" ++
    "import Machines.Lnp64u.Hw.Core\n" ++
    "import Machines.Lnp64u.Hw.Demo\n\n"
  let namespaceHeader :=
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Hw Loom.Release\n\n" ++
    "noncomputable section\n\n"
  let dataStructures :=
    "structure ActionEvidenceData where\n" ++
    "  source : Act\n" ++
    "  cert : Symbolic.ActionWide.ActionCert\n" ++
    "  input : Symbolic.ActionWide.SparseRefs\n" ++
    "  needed : List Nat\n" ++
    "  result : Symbolic.ActionWide.SparseResult\n\n" ++
    "structure ActionEvidenceContext where\n" ++
    "  source : Act\n" ++
    "  cert : Symbolic.ActionWide.ActionCert\n" ++
    "  input : Symbolic.ActionWide.SparseRefs\n" ++
    "  needed : List Nat\n\n" ++
    ""
  let localOptions :=
    "set_option maxRecDepth 1000000\n" ++
    "set_option maxHeartbeats 0\n" ++
    "set_option linter.unusedVariables false\n\n"
  let initialData :=
    "def actionRegisters : Array RegDecl := " ++ registersToLean registers ++
      "\n" ++
    "noncomputable def coreEvidenceInput : Symbolic.ActionWide.SparseRefs := " ++
      sparseDeltaToLean "Symbolic.ActionWide.SparseRefs.empty" initial
        refillResult.refs ++ "\n" ++
    "noncomputable def coreEvidenceNeeded : List Nat := [" ++
      String.intercalate ", " (coreNeeded.map toString) ++ "]\n\n"
  if split then
    IO.FS.createDirAll output
    let prelude := imports ++ namespaceHeader ++ dataStructures ++ localOptions ++
      initialData ++ "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged (output / "ActionEvidencePrelude.lean") prelude
    let mut batches : Array (Array String) := #[]
    let mut batch : Array String := #[]
    let mut batchBytes := 0
    for declaration in state.declarations do
      if batchBytes > 0 && batchBytes + declaration.length > 4 * 1024 * 1024 then
        batches := batches.push batch
        batch := #[]
        batchBytes := 0
      batch := batch.push declaration
      batchBytes := batchBytes + declaration.length
    if !batch.isEmpty then batches := batches.push batch
    IO.eprintln s!"generated {batches.size} evidence modules"
    for index in List.range batches.size do
      let some declarations := batches[index]? | return 1
      let imported := if index = 0 then
          "GeneratedRelease.Lnp64u.ActionEvidencePrelude"
        else
          "GeneratedRelease.Lnp64u.ActionEvidenceBatch" ++ pad3 (index - 1)
      let source := "-- Generated bounded evidence batch; DO NOT EDIT.\n" ++
        "import " ++ imported ++ "\n\n" ++ namespaceHeader ++ localOptions ++
        String.intercalate "\n" declarations.toList ++ "\n" ++
        "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
      writeIfChanged (output / ("ActionEvidenceBatch" ++ pad3 index ++ ".lean"))
        source
    let lastImport := if batches.isEmpty then
        "GeneratedRelease.Lnp64u.ActionEvidencePrelude"
      else "GeneratedRelease.Lnp64u.ActionEvidenceBatch" ++
        pad3 (batches.size - 1)
    let root := "-- Generated action evidence root; DO NOT EDIT.\n" ++
      "import " ++ lastImport ++ "\n\n" ++ namespaceHeader ++
      "theorem coreActionAccepted := " ++ rootBuild.evidence ++
        ".accepted\n\nend\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged (output / "ActionEvidenceRoot.lean") root
    let topDown := "-- Generated top-down action evidence spike; DO NOT EDIT.\n" ++
      "import GeneratedRelease.Lnp64u.FastIndexedRoot\n" ++
      "import GeneratedRelease.Lnp64u.ActionCert\n" ++
      "import Loom.Release.SymbolicDecide\n" ++
      "import Machines.Lnp64u.Hw.Core\n" ++
      "import Machines.Lnp64u.Hw.Demo\n" ++
      "import Machines.Lnp64u.Theorems.ReleaseOrder\n\n" ++ namespaceHeader ++
      localOptions ++ "indexed_expr_checkpoints " ++
        String.intercalate " " (checkpoints.map toString) ++ "\n\n" ++
      initialData ++
      "theorem coreActionEvidence :\n" ++
      "    ∃ result, Symbolic.ActionWide.BitSparseEvidence fastIndexedWireTree fastWireTable " ++
        "actionRegisters\n" ++
      "      (Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest)\n" ++
      "      coreEvidenceInput " ++ toString (indicesToBits coreNeeded) ++
        " actionCertNode15158 result :=\n" ++
      "  sparse_evidence_exists\n\n" ++
      "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged (output / "ActionTopDown.lean") topDown
  else
    let source := imports ++ namespaceHeader ++ dataStructures ++ localOptions ++
      initialData ++ String.intercalate "\n" state.declarations.toList ++
      "\ntheorem coreActionAccepted := " ++ rootBuild.evidence ++
      ".accepted\n\nend\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged output source
  return 0

private unsafe def generateCoreBranchProbe (runtime output : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let registers := design.regs.toArray
  let needed := List.range registers.size
  let initial := registers.map fun register =>
    Loom.Release.Symbolic.Ref.reg register.name
  let some refillCert := cert[0]? | return 1
  let refillNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs cert.tail needed
  let some refillResult := evaluateCert registers initial refillNeeded refillCert
    | return 1
  let some coreCert := cert[1]? | return 1
  IO.eprintln s!"core action certificate nodes={actionCertNodeCount coreCert}"
  let coreNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    (cert.drop 2) needed
  let (.ite summary _ _ thenCert _elseCert) := coreCert | return 1
  let changed := Loom.Release.Symbolic.ActionWide.changedOutputs summary coreNeeded
  let (.ite thenSummary _ _ retirementCert countdownCert) := thenCert | return 1
  let thenChanged := Loom.Release.Symbolic.ActionWide.changedOutputs
    thenSummary changed
  let some retirementResult := evaluateCert registers refillResult.refs
      thenChanged retirementCert | return 1
  let some countdownResult := evaluateCert registers refillResult.refs
      thenChanged countdownCert | return 1
  let source := "-- Generated core-branch segmentation probe; DO NOT EDIT.\n" ++
    "import GeneratedRelease.Lnp64u.ActionCert\n" ++
    "import GeneratedRelease.Lnp64u.SemanticRoot\n" ++
    "import Loom.Release.KernelDecide\n" ++
    "import Machines.Lnp64u.Hw.Core\n" ++
    "import Machines.Lnp64u.Hw.Demo\n\n" ++
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Release\n\n" ++
    "private abbrev design := Machines.Lnp64u.Hw.core " ++
      "Machines.Lnp64u.Demo.sysManifest\n" ++
    "noncomputable def coreInput : Array Symbolic.Ref := " ++
      Tools.ReleaseCertGen.actionWideRefsToLean refillResult.refs ++ "\n" ++
    "def coreNeeded : List Nat := [" ++
      String.intercalate ", " (coreNeeded.map toString) ++ "]\n" ++
    "def coreChanged : List Nat := [" ++
      String.intercalate ", " (changed.map toString) ++ "]\n" ++
    "def coreThenChanged : List Nat := [" ++
      String.intercalate ", " (thenChanged.map toString) ++ "]\n" ++
    "noncomputable def coreThenCert := " ++
      "Symbolic.ActionWide.ActionCert.iteThen actionCertNode15158\n" ++
    "noncomputable def coreElseCert := " ++
      "Symbolic.ActionWide.ActionCert.iteElse actionCertNode15158\n" ++
    "noncomputable def retirementCert := " ++
      "Symbolic.ActionWide.ActionCert.iteThen coreThenCert\n" ++
    "noncomputable def countdownCert := " ++
      "Symbolic.ActionWide.ActionCert.iteElse coreThenCert\n\n" ++
    "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\n" ++
    "theorem retirementAccepted :\n" ++
    "    Symbolic.ActionWide.runCheckedAction indexedWireTree wireTable " ++
      "design.regs.toArray\n" ++
    "      (Symbolic.ActionWide.iteThenAction " ++
      "(Symbolic.ActionWide.iteThenAction " ++
      "(Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest)))\n" ++
    "      coreInput coreThenChanged retirementCert = some " ++
      resultToLean retirementResult ++ " := kernel_decide\n\n" ++
    "theorem countdownAccepted :\n" ++
    "    Symbolic.ActionWide.runCheckedAction indexedWireTree wireTable " ++
      "design.regs.toArray\n" ++
    "      (Symbolic.ActionWide.iteElseAction " ++
      "(Symbolic.ActionWide.iteThenAction " ++
      "(Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest)))\n" ++
    "      coreInput coreThenChanged countdownCert = some " ++
      resultToLean countdownResult ++ " := kernel_decide\n\n" ++
    "end Loom.GeneratedRelease.Lnp64u\n"
  writeIfChanged output source
  return 0

set_option compiler.extract_closed false in
unsafe def main (args : List String) : IO UInt32 := do
  IO.eprintln "actionwidegen-start"
  match args with
  | ["acc8", runtime, output] =>
      generate (fun _ => Machines.Acc8.Core.design
          (Machines.Acc8.loadProg Machines.Acc8.golden))
        "Loom.GeneratedRelease.Acc8" runtime output
  | ["lnp64u", runtime, output] =>
      generate (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "Loom.GeneratedRelease.Lnp64u" runtime output
  | ["lnp64u-join-probe", runtime, output] =>
      generateJoinBlock (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "GeneratedRelease.Lnp64u.IndexedRoot" "Loom.GeneratedRelease.Lnp64u"
        "Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest"
        runtime output
  | ["lnp64u-join-probe", runtime, output, blockCount] =>
      let some blockCount := blockCount.toNat?
        | IO.eprintln "block count must be a natural number"; return 2
      generateJoinBlock (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "GeneratedRelease.Lnp64u.IndexedRoot" "Loom.GeneratedRelease.Lnp64u"
        "Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest"
        runtime output blockCount
  | ["lnp64u-local-join-probe", runtime, output, blockIndex] =>
      let some blockIndex := blockIndex.toNat?
        | IO.eprintln "block index must be a natural number"; return 2
      generateLocalJoinBlock runtime output blockIndex
  | ["lnp64u-local-joins", runtime, outputDir] =>
      generateLocalJoinBlocks runtime outputDir
  | ["lnp64u-named-cert", runtime, output] =>
      generateNamedCertificate runtime output
  | ["lnp64u-core-branch-probe", runtime, output] =>
      generateCoreBranchProbe runtime output
  | ["lnp64u-core-evidence", runtime, output] =>
      generateCoreEvidence runtime output
  | ["lnp64u-core-evidence-batches", runtime, outputDir] =>
      generateCoreEvidence runtime outputDir true
  | ["lnp64u-core-stats", runtime] =>
      reportCoreStats runtime
  | ["lnp64u-core-cuts", runtime, outputDir] =>
      generateCoreCuts runtime outputDir
  | ["lnp64u-dag-cut", runtime, output, cutIndex] =>
      let some cutIndex := cutIndex.toNat?
        | IO.eprintln "cut index must be a natural number"; return 2
      generateCoreDagProbe runtime output cutIndex
  | _ =>
      IO.eprintln "usage: actionwidegen {acc8|lnp64u} RUNTIME.json OUTPUT.lean"
      return 2
