-- Copyright (c) 2026 Kevin Baragona
-- SPDX-License-Identifier: Apache-2.0
import Tools.ReleaseCertGen
import Tools.RuntimeSsa
import Machines.Acc8.Core
import Machines.Acc8.Iss
import Machines.Lnp64u.Hw.Core
import Machines.Lnp64u.Hw.Demo

/-! Native untrusted generator for action-wide release certificates. -/

open Loom.Hw

private def writeIfChanged (path : System.FilePath) (contents : String) : IO Unit := do
  try
    if (← IO.FS.readFile path) == contents then return
  catch _ => pure ()
  if let some parent := path.parent then IO.FS.createDirAll parent
  IO.FS.writeFile path contents

private def source (namespaceName : String) (registers : List RegDecl) (cert :
    Loom.Release.Symbolic.ActionWide.RulesCert) : Option (String × String) := do
  let rendered ← Tools.ReleaseCertGen.actionWideRulesToLean registers cert
  let leanSource := "-- Generated by Tools.ActionWideGen; DO NOT EDIT.\n" ++
  "import Loom.Release.ActionWideRegister\n\n" ++
  "namespace " ++ namespaceName ++ "\n\n" ++
  "open Loom.Release\n\n" ++
  "def actionWideRegisterData : String :=\n" ++
  "  include_str \"ActionWideRegisterData.txt\"\n\n" ++
  "end " ++ namespaceName ++ "\n"
  pure (leanSource, rendered.data)

private unsafe def generate (makeDesign : Unit → Design) (namespaceName : String)
    (runtime output : System.FilePath) : IO UInt32 := do
  let started ← IO.monoMsNow
  let program ← Tools.RuntimeSsa.load runtime
  let loaded ← IO.monoMsNow
  IO.eprintln s!"runtime-load={loaded - started}ms"
  let design := makeDesign ()
  let designed ← IO.monoMsNow
  IO.eprintln s!"design={designed - loaded}ms"
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let generated ← IO.monoMsNow
  let some (contents, data) := source namespaceName design.regs cert
    | IO.eprintln "action-wide certificate encoding failed"; return 1
  let dataPath := output.parent.getD "." / "ActionWideRegisterData.txt"
  writeIfChanged dataPath data
  writeIfChanged output contents
  let written ← IO.monoMsNow
  IO.println (s!"runtime-load={loaded - started}ms " ++
    s!"design={designed - loaded}ms certificate={generated - designed}ms " ++
    s!"write={written - generated}ms")
  return 0

private def joinBlockSource (rootImport namespaceName designExpr : String)
    (fuel blockCount : Nat)
    (cert : Loom.Release.Symbolic.ActionWide.RulesCert) : String :=
  let joins := Tools.ReleaseCertGen.actionWideJoins cert
  let blocks := (List.range blockCount).map fun index =>
    joins.drop (index * 128) |>.take 128
  let declarations := String.intercalate "\n" <| blocks.zipIdx.map fun (block, index) =>
    "def joinProbe" ++ toString index ++
      " : List Symbolic.ActionWide.Join :=\n" ++
      Tools.ReleaseCertGen.actionWideJoinBlockToLean block ++ "\n\n" ++
    "theorem joinProbeAccepted" ++ toString index ++ " :\n" ++
      "    Symbolic.ActionWide.joinBlockMatchesFuel indexedWireTree wireTable\n" ++
      "      design.regs.toArray " ++ toString fuel ++ " joinProbe" ++
      toString index ++ " = true := kernel_decide\n"
  "-- Generated join-block feasibility probe; DO NOT EDIT.\n" ++
  "import " ++ rootImport ++ "\n" ++
  "import Loom.Release.ActionWideRegister\n" ++
  "import Loom.Release.KernelDecide\n" ++
  "import Machines.Lnp64u.Hw.Core\n" ++
  "import Machines.Lnp64u.Hw.Demo\n\n" ++
  "namespace " ++ namespaceName ++ "\n\n" ++
  "open Loom.Release\n\n" ++
  "private abbrev design := " ++ designExpr ++ "\n\n" ++
  "set_option maxRecDepth 1000000\n" ++
  "set_option maxHeartbeats 0\n\n" ++
  declarations ++ "\n" ++
  "end " ++ namespaceName ++ "\n"

private unsafe def generateJoinBlock (makeDesign : Unit → Design)
    (rootImport namespaceName designExpr : String)
    (runtime output : System.FilePath) (blockCount : Nat := 1) : IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := makeDesign ()
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let joins := Tools.ReleaseCertGen.actionWideJoins cert
  let joinCount := joins.length
  let perRule := cert.map fun rule => Tools.ReleaseCertGen.actionWideJoins [rule] |>.length
  let mut exact := 0
  let mut ordered := 0
  let mut previous : Option Nat := none
  for join in joins do
    match join.output with
    | .wire number =>
        if previous.all (· < number) then ordered := ordered + 1
        previous := some number
        if let some wire := program.wires[number]? then
          if let some (.mux guard yes no) := wire.rhs.toIndexed? then
            if guard == join.guard && yes == join.thenInput &&
                no == join.elseInput then
              exact := exact + 1
    | .reg _ => pure ()
  IO.eprintln s!"action-wide joins={joinCount}; emitting {blockCount} blocks"
  IO.eprintln s!"action-wide rules={cert.length}; joins/rule={perRule}"
  IO.eprintln s!"action-wide exact={exact}; monotonically-ordered={ordered}"
  writeIfChanged output (joinBlockSource rootImport namespaceName designExpr
    (program.wires.size + 1) blockCount cert)
  return 0

private def pad3 (number : Nat) : String :=
  let value := toString number
  if number < 10 then "00" ++ value
  else if number < 100 then "0" ++ value
  else value

private def pad4 (number : Nat) : String :=
  let value := toString number
  if number < 10 then "000" ++ value
  else if number < 100 then "00" ++ value
  else if number < 1000 then "0" ++ value
  else value

private def localJoinBlockSource (blockIndex : Nat)
    (joins : List Loom.Release.Symbolic.ActionWide.Join) : String :=
  let batchIndex := blockIndex / 4
  let suffix := pad4 blockIndex
  "-- Generated local join-block feasibility probe; DO NOT EDIT.\n" ++
  "import GeneratedRelease.Lnp64u.Batch" ++ pad3 batchIndex ++ "\n" ++
  "import Loom.Release.ActionWideJoin\n" ++
  "import Loom.Release.KernelDecide\n" ++
  "\n" ++
  "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
  "open Loom.Release\n\n" ++
  "set_option maxRecDepth 1000000\n\n" ++
  Tools.ReleaseCertGen.actionWideNamedJoinBlockToLean
    ("actionJoinBlock" ++ suffix) joins ++ "\n\n" ++
  "set_option maxRecDepth 1000000\n" ++
  "set_option maxHeartbeats 0\n\n" ++
  "theorem actionJoinBlockAccepted" ++ suffix ++ " :\n" ++
  "    Symbolic.ActionWide.localJoinBlockMatches " ++
    toString (blockIndex * 128) ++ " indexedWireBlock" ++
    suffix ++ " actionJoinBlock" ++ suffix ++
    " = true := kernel_decide\n\n" ++
  "end Loom.GeneratedRelease.Lnp64u\n"

private unsafe def generateLocalJoinBlock (runtime output : System.FilePath)
    (blockIndex : Nat) : IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let joins := (Tools.ReleaseCertGen.actionWideJoins cert).filter fun join =>
    match join.output with
    | .wire number => number / 128 == blockIndex
    | .reg _ => false
  IO.eprintln s!"local join block {blockIndex}: {joins.length} joins"
  writeIfChanged output (localJoinBlockSource blockIndex joins)
  return 0

private unsafe def generateLocalJoinBlocks (runtime outputDir : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let blockCount := (program.wires.size + 127) / 128
  let mut groups : Array (List Loom.Release.Symbolic.ActionWide.Join) :=
    Array.replicate blockCount []
  for join in Tools.ReleaseCertGen.actionWideJoins cert do
    if let .wire number := join.output then
      let blockIndex := number / 128
      if blockIndex < groups.size then
        groups := groups.modify blockIndex (join :: ·)
  IO.FS.createDirAll outputDir
  let mut emitted := 0
  let mut modules : List String := []
  for blockIndex in List.range groups.size do
    let joins := groups[blockIndex]!.reverse
    if !joins.isEmpty then
      let suffix := pad4 blockIndex
      let path := outputDir / s!"ActionJoinBlock{suffix}.lean"
      writeIfChanged path (localJoinBlockSource blockIndex joins)
      modules := s!"GeneratedRelease.Lnp64u.ActionJoinBlock{suffix}" :: modules
      emitted := emitted + 1
  writeIfChanged (outputDir / "action-join-modules.txt")
    (String.intercalate "\n" modules.reverse ++ "\n")
  IO.eprintln s!"emitted {emitted} nonempty local join blocks"
  return 0

private unsafe def generateNamedCertificate (runtime output : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let mut importedBlocks : Std.HashSet Nat := {}
  for join in Tools.ReleaseCertGen.actionWideJoins cert do
    if let .wire number := join.output then
      importedBlocks := importedBlocks.insert (number / 128)
  let imports := (List.range ((program.wires.size + 127) / 128)).filterMap
    fun blockIndex => if importedBlocks.contains blockIndex then
      some ("import GeneratedRelease.Lnp64u.ActionJoinBlock" ++ pad4 blockIndex)
    else none
  let source := "-- Generated bounded typed action certificate; DO NOT EDIT.\n" ++
    String.intercalate "\n" imports ++
    "\nimport Loom.Release.ActionWideRegister\n\n" ++
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Release\n\n" ++
    "set_option maxRecDepth 1000000\n\n" ++
    Tools.ReleaseCertGen.actionWideNamedCertificateToLean cert ++ "\n" ++
    "end Loom.GeneratedRelease.Lnp64u\n"
  writeIfChanged output source
  return 0

private def evaluateCert (registers : Array RegDecl) :
    Array Loom.Release.Symbolic.Ref → List Nat →
      Loom.Release.Symbolic.ActionWide.ActionCert →
      Option Loom.Release.Symbolic.ActionWide.Result
  | refs, _, .skip | refs, _, .memWrite =>
      some { refs, changed := [] }
  | refs, needed, .write index value =>
      if index ∉ needed then some { refs, changed := [] }
      else if index < refs.size then
        some { refs := refs.set! index value, changed := [index] }
      else none
  | refs, needed, .seq summary left right => do
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededInputs
        right.summary needed
      let leftResult ← evaluateCert registers refs leftNeeded left
      let rightResult ← evaluateCert registers leftResult.refs needed right
      pure { refs := rightResult.refs
             changed := Loom.Release.Symbolic.ActionWide.changedOutputs
               summary needed }
  | refs, needed, .ite summary _ joins thenCert elseCert => do
      let changed := Loom.Release.Symbolic.ActionWide.changedOutputs summary needed
      let thenResult ← evaluateCert registers refs changed thenCert
      let elseResult ← evaluateCert registers refs changed elseCert
      let mut output := refs
      if joins.length != changed.length then failure
      for (index, join) in changed.zip joins do
        let source ← registers[index]?
        guard (join.index == index && join.width == source.width)
        guard (thenResult.refs[index]?.isSome && elseResult.refs[index]?.isSome)
        output := output.set! index join.output
      pure { refs := output, changed }

private def actionCertNodeCount :
    Loom.Release.Symbolic.ActionWide.ActionCert → Nat
  | .skip | .memWrite | .write .. => 1
  | .seq _ left right | .ite _ _ _ left right =>
      actionCertNodeCount left + actionCertNodeCount right + 1

private def resultToLean (result : Loom.Release.Symbolic.ActionWide.Result) :
    String :=
  "{ refs := " ++ Tools.ReleaseCertGen.actionWideRefsToLean result.refs ++
    ", changed := [" ++ String.intercalate ", "
      (result.changed.map toString) ++ "] }"

private structure EvidenceBuild where
  source : String
  cert : String
  input : String
  needed : String
  result : String
  evidence : String
  locals : Array String := #[]
  size : Nat

private structure EvidenceGenState where
  next : Nat := 0
  resultNext : Nat := 0
  aliasNext : Nat := 0
  neededNext : Nat := 0
  declarations : Array String := #[]

private abbrev EvidenceGenM := StateT EvidenceGenState Option

private def emitEvidenceResult (expression : String) :
    EvidenceGenM (String × String) := do
  let state ← get
  let name := "actionResult" ++ toString state.resultNext
  let declaration := "  let " ++ name ++
    " : Symbolic.ActionWide.Result := " ++ expression ++ "\n"
  set ({ next := state.next, resultNext := state.resultNext + 1
         aliasNext := state.aliasNext, neededNext := state.neededNext
         declarations := state.declarations } : EvidenceGenState)
  pure (name, declaration)

private def emitEvidenceAliases (source cert : String) :
    EvidenceGenM (String × String × String) := do
  let state ← get
  let suffix := toString state.aliasNext
  let sourceName := "actionSourceAlias" ++ suffix
  let certName := "actionCertAlias" ++ suffix
  let declaration :=
    "  let " ++ sourceName ++ " : Act := " ++ source ++ "\n" ++
    "  let " ++ certName ++
      " : Symbolic.ActionWide.ActionCert := " ++ cert ++ "\n"
  set ({ next := state.next, resultNext := state.resultNext
         aliasNext := state.aliasNext + 1, neededNext := state.neededNext
         declarations := state.declarations } : EvidenceGenState)
  pure (sourceName, certName, declaration)

private def emitEvidenceNeeded (expression : String) :
    EvidenceGenM (String × String) := do
  let state ← get
  let name := "actionNeeded" ++ toString state.neededNext
  let declaration := "  let " ++ name ++
    " : List Nat := " ++ expression ++ "\n"
  set ({ next := state.next, resultNext := state.resultNext
         aliasNext := state.aliasNext, neededNext := state.neededNext + 1
         declarations := state.declarations } : EvidenceGenState)
  pure (name, declaration)

private def refsDeltaToLean (base : String)
    (before after : Array Loom.Release.Symbolic.Ref) : String := Id.run do
  let mut expression := base
  for index in List.range (min before.size after.size) do
    if let some beforeRef := before[index]? then
      if let some afterRef := after[index]? then
        if beforeRef != afterRef then
          expression := "(" ++ expression ++ ").set! " ++ toString index ++
            " (" ++ Tools.ReleaseCertGen.actionWideRefToLean afterRef ++ ")"
  pure expression

private def evidenceType (source input needed cert result : String) : String :=
  "Symbolic.ActionWide.CheckedEvidence indexedWireTree wireTable " ++
    "design.regs.toArray (" ++ source ++ ") (" ++ input ++ ") (" ++
    needed ++ ") (" ++ cert ++ ") (" ++ result ++ ")"

private def mergeLocals (left right : Array String) : Array String :=
  right.foldl (fun merged declaration =>
    if merged.contains declaration then merged else merged.push declaration) left

private def emitEvidenceContext (source cert input needed : String)
    (locals : Array String) :
    EvidenceGenM (String × String × String × String) := do
  let state ← get
  let suffix := toString state.aliasNext
  let name := "actionContext" ++ suffix
  let declaration :=
    "noncomputable def " ++ name ++ " : ActionEvidenceContext :=\n" ++
    String.join locals.toList ++
    "  { source := " ++ source ++ ", cert := " ++ cert ++
      ", input := " ++ input ++ ", needed := " ++ needed ++ " }\n"
  set ({ next := state.next, resultNext := state.resultNext
         aliasNext := state.aliasNext + 1, neededNext := state.neededNext
         declarations := state.declarations.push declaration } : EvidenceGenState)
  pure (name ++ ".source", name ++ ".cert", name ++ ".input",
    name ++ ".needed")

private def emitEvidenceBoundary (build : EvidenceBuild) (direct := false) :
    EvidenceGenM EvidenceBuild := do
  let state ← get
  let suffix := toString state.next
  let dataName := "segmentData" ++ suffix
  let theoremName := "segmentEvidence" ++ suffix
  let proof := if direct then
      " := (.direct (kernel_decide))\n"
    else
      " := by\n" ++
      "  unfold " ++ dataName ++ "\n" ++
      String.join build.locals.toList ++
      "  change " ++ evidenceType build.source build.input build.needed
        build.cert build.result ++ "\n" ++
      "  exact " ++ build.evidence ++ "\n"
  let declaration :=
    "noncomputable def " ++ dataName ++ " : ActionEvidenceData :=\n" ++
    String.join build.locals.toList ++
    "  { source := " ++ build.source ++ ", cert := " ++ build.cert ++
      ", input := " ++ build.input ++ ", needed := " ++ build.needed ++
      ", result := " ++ build.result ++ " }\n" ++
    "theorem " ++ theoremName ++ " :\n    " ++
      evidenceType (dataName ++ ".source") (dataName ++ ".input")
        (dataName ++ ".needed") (dataName ++ ".cert")
        (dataName ++ ".result") ++ proof
  set ({ next := state.next + 1, resultNext := state.resultNext
         aliasNext := state.aliasNext, neededNext := state.neededNext
         declarations := state.declarations.push declaration } : EvidenceGenState)
  pure { source := dataName ++ ".source", cert := dataName ++ ".cert"
         input := dataName ++ ".input", needed := dataName ++ ".needed"
         result := dataName ++ ".result", evidence := theoremName
         locals := #[], size := 1 }

private partial def buildEvidence (registers : Array RegDecl)
    (source : Act) (cert : Loom.Release.Symbolic.ActionWide.ActionCert)
    (inputRefs : Array Loom.Release.Symbolic.Ref) (neededValues : List Nat)
    (sourceExpr certExpr inputExpr neededExpr : String)
    (inheritedLocals : Array String) (pathDepth : Nat) :
    EvidenceGenM EvidenceBuild := do
  let (sourceExpr, certExpr, inputExpr, neededExpr, inheritedLocals) ←
    if inheritedLocals.size ≥ 32 then do
      let (source, cert, input, needed) ← emitEvidenceContext sourceExpr certExpr
        inputExpr neededExpr inheritedLocals
      pure (source, cert, input, needed, #[])
    else pure (sourceExpr, certExpr, inputExpr, neededExpr, inheritedLocals)
  let (sourceExpr, certExpr, aliasLocals, pathDepth) ←
    if pathDepth ≥ 8 then do
      let (sourceName, certName, declaration) ←
        emitEvidenceAliases sourceExpr certExpr
      pure (sourceName, certName, #[declaration], 0)
    else pure (sourceExpr, certExpr, #[], pathDepth)
  let (neededExpr, neededLocal) ← emitEvidenceNeeded neededExpr
  let prefixLocals := (mergeLocals inheritedLocals aliasLocals).push neededLocal
  let some result := evaluateCert registers inputRefs neededValues cert | failure
  let changedExpr := "Symbolic.ActionWide.changedOutputs (" ++ certExpr ++
    ").summary (" ++ neededExpr ++ ")"
  match source, cert with
  | .skip, .skip | .memWrite .., .memWrite | .write .., .write .. =>
      let refsExpr := refsDeltaToLean inputExpr inputRefs result.refs
      let (resultExpr, resultLocal) ← emitEvidenceResult ("{ refs := " ++ refsExpr ++
        ", changed := " ++ changedExpr ++ " }"
        )
      let build : EvidenceBuild :=
        { source := sourceExpr, cert := certExpr, input := inputExpr
          needed := neededExpr, result := resultExpr
          evidence := "(.direct (kernel_decide))"
          locals := prefixLocals.push resultLocal, size := 1 }
      pure build
  | .seq left right, .seq _ leftCert rightCert =>
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededInputs
        rightCert.summary neededValues
      let leftSourceExpr := "Symbolic.ActionWide.seqLeftAction (" ++
        sourceExpr ++ ")"
      let rightSourceExpr := "Symbolic.ActionWide.seqRightAction (" ++
        sourceExpr ++ ")"
      let leftCertExpr := "Symbolic.ActionWide.ActionCert.seqLeft (" ++
        certExpr ++ ")"
      let rightCertExpr := "Symbolic.ActionWide.ActionCert.seqRight (" ++
        certExpr ++ ")"
      let leftNeededExpr := "Symbolic.ActionWide.neededInputs (" ++
        rightCertExpr ++ ").summary (" ++ neededExpr ++ ")"
      let leftBuild ← buildEvidence registers left leftCert inputRefs leftNeeded
        leftSourceExpr leftCertExpr inputExpr leftNeededExpr prefixLocals
        (pathDepth + 1)
      let some leftResult := evaluateCert registers inputRefs leftNeeded leftCert
        | failure
      let rightInputExpr := "(" ++ leftBuild.result ++ ").refs"
      let rightBuild ← buildEvidence registers right rightCert leftResult.refs
        neededValues rightSourceExpr rightCertExpr rightInputExpr neededExpr
        (mergeLocals prefixLocals leftBuild.locals)
        (pathDepth + 1)
      let (resultExpr, resultLocal) ← emitEvidenceResult ("{ refs := (" ++ rightBuild.result ++
        ").refs, changed := " ++ changedExpr ++ " }")
      let proof := "(by\n" ++
        "  rw [Symbolic.ActionWide.action_eq_seq_projections " ++
          "(action := " ++ sourceExpr ++ ") (kernel_decide)]\n" ++
        "  rw [Symbolic.ActionWide.ActionCert.eq_seq_projections " ++
          "(cert := " ++ certExpr ++ ") (kernel_decide)]\n" ++
        "  exact .seq (leftResult := " ++ leftBuild.result ++ ") " ++
          "(rightResult := " ++ rightBuild.result ++ ") rfl (" ++
          leftBuild.evidence ++ ") (" ++ rightBuild.evidence ++ "))"
      let build : EvidenceBuild :=
        { source := sourceExpr, cert := certExpr, input := inputExpr
          needed := neededExpr, result := resultExpr, evidence := proof
          locals := (mergeLocals (mergeLocals prefixLocals leftBuild.locals)
            rightBuild.locals).push resultLocal
          size := leftBuild.size + rightBuild.size + 1 }
      if build.size ≥ 32 then emitEvidenceBoundary build else pure build
  | .ite _condition thenAction elseAction,
      .ite _ _ _joins thenCert elseCert =>
      let changed := Loom.Release.Symbolic.ActionWide.changedOutputs
        cert.claimedSummary neededValues
      let thenSourceExpr := "Symbolic.ActionWide.iteThenAction (" ++
        sourceExpr ++ ")"
      let elseSourceExpr := "Symbolic.ActionWide.iteElseAction (" ++
        sourceExpr ++ ")"
      let thenCertExpr := "Symbolic.ActionWide.ActionCert.iteThen (" ++
        certExpr ++ ")"
      let elseCertExpr := "Symbolic.ActionWide.ActionCert.iteElse (" ++
        certExpr ++ ")"
      let changedNeededExpr := "Symbolic.ActionWide.changedOutputs (" ++
        certExpr ++ ").claimedSummary (" ++ neededExpr ++ ")"
      let thenBuild ← buildEvidence registers thenAction thenCert inputRefs changed
        thenSourceExpr thenCertExpr inputExpr changedNeededExpr prefixLocals
        (pathDepth + 1)
      let elseBuild ← buildEvidence registers elseAction elseCert inputRefs changed
        elseSourceExpr elseCertExpr inputExpr changedNeededExpr prefixLocals
        (pathDepth + 1)
      let refsExpr := refsDeltaToLean inputExpr inputRefs result.refs
      let (resultExpr, resultLocal) ← emitEvidenceResult ("{ refs := " ++ refsExpr ++
        ", changed := " ++ changedExpr ++ " }")
      let proof := "(by\n" ++
        "  rw [Symbolic.ActionWide.action_eq_ite_projections " ++
          "(action := " ++ sourceExpr ++ ") (kernel_decide)]\n" ++
        "  rw [Symbolic.ActionWide.ActionCert.eq_ite_projections " ++
          "(cert := " ++ certExpr ++ ") (kernel_decide)]\n" ++
        "  exact .ite (thenResult := " ++ thenBuild.result ++ ") " ++
          "(elseResult := " ++ elseBuild.result ++ ") " ++
          "(merged := " ++ refsExpr ++ ") rfl (kernel_decide) (" ++
          thenBuild.evidence ++ ") (" ++ elseBuild.evidence ++
          ") (kernel_decide))"
      let build : EvidenceBuild :=
        { source := sourceExpr, cert := certExpr, input := inputExpr
          needed := neededExpr, result := resultExpr, evidence := proof
          locals := (mergeLocals (mergeLocals prefixLocals thenBuild.locals)
            elseBuild.locals).push resultLocal
          size := thenBuild.size + elseBuild.size + 1 }
      if build.size ≥ 32 then emitEvidenceBoundary build else pure build
  | _, _ => failure

private unsafe def generateCoreEvidence (runtime output : System.FilePath)
    (split : Bool := false) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program | return 1
  let registers := design.regs.toArray
  let needed := List.range registers.size
  let initial := registers.map fun register =>
    Loom.Release.Symbolic.Ref.reg register.name
  let some refillCert := cert[0]? | return 1
  let refillNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs cert.tail needed
  let some refillResult := evaluateCert registers initial refillNeeded refillCert
    | return 1
  let some coreCert := cert[1]? | return 1
  let coreNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    (cert.drop 2) needed
  let initialState : EvidenceGenState := {}
  let some (rootBuild, state) := (buildEvidence registers
      (Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest) coreCert
      refillResult.refs coreNeeded
      "Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest"
      "actionCertNode15158"
      "coreEvidenceInput" "coreEvidenceNeeded" #[] 0).run
        initialState | return 1
  let some (rootBuild, state) := (emitEvidenceBoundary rootBuild false).run state
    | return 1
  IO.eprintln s!"generated {state.next} bounded evidence segments"
  let imports := "-- Generated bounded core evidence; DO NOT EDIT.\n" ++
    "import GeneratedRelease.Lnp64u.ActionCert\n" ++
    "import GeneratedRelease.Lnp64u.SemanticRoot\n" ++
    "import Loom.Release.KernelDecide\n" ++
    "import Machines.Lnp64u.Hw.Core\n" ++
    "import Machines.Lnp64u.Hw.Demo\n\n"
  let namespaceHeader :=
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Hw Loom.Release\n\n" ++
    "noncomputable section\n\n"
  let dataStructures :=
    "structure ActionEvidenceData where\n" ++
    "  source : Act\n" ++
    "  cert : Symbolic.ActionWide.ActionCert\n" ++
    "  input : Array Symbolic.Ref\n" ++
    "  needed : List Nat\n" ++
    "  result : Symbolic.ActionWide.Result\n\n" ++
    "structure ActionEvidenceContext where\n" ++
    "  source : Act\n" ++
    "  cert : Symbolic.ActionWide.ActionCert\n" ++
    "  input : Array Symbolic.Ref\n" ++
    "  needed : List Nat\n\n" ++
    ""
  let localOptions :=
    "private abbrev design := Machines.Lnp64u.Hw.core " ++
      "Machines.Lnp64u.Demo.sysManifest\n" ++
    "set_option maxRecDepth 1000000\n" ++
    "set_option maxHeartbeats 0\n" ++
    "set_option linter.unusedVariables false\n\n"
  let initialData :=
    "noncomputable def coreEvidenceInput : Array Symbolic.Ref := " ++
      Tools.ReleaseCertGen.actionWideRefsToLean refillResult.refs ++ "\n" ++
    "noncomputable def coreEvidenceNeeded : List Nat := [" ++
      String.intercalate ", " (coreNeeded.map toString) ++ "]\n\n"
  if split then
    IO.FS.createDirAll output
    let prelude := imports ++ namespaceHeader ++ dataStructures ++ localOptions ++
      initialData ++ "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged (output / "ActionEvidencePrelude.lean") prelude
    let mut batches : Array (Array String) := #[]
    let mut batch : Array String := #[]
    let mut batchBytes := 0
    for declaration in state.declarations do
      if batchBytes > 0 && batchBytes + declaration.length > 4 * 1024 * 1024 then
        batches := batches.push batch
        batch := #[]
        batchBytes := 0
      batch := batch.push declaration
      batchBytes := batchBytes + declaration.length
    if !batch.isEmpty then batches := batches.push batch
    IO.eprintln s!"generated {batches.size} evidence modules"
    for index in List.range batches.size do
      let some declarations := batches[index]? | return 1
      let imported := if index = 0 then
          "GeneratedRelease.Lnp64u.ActionEvidencePrelude"
        else
          "GeneratedRelease.Lnp64u.ActionEvidenceBatch" ++ pad3 (index - 1)
      let source := "-- Generated bounded evidence batch; DO NOT EDIT.\n" ++
        "import " ++ imported ++ "\n\n" ++ namespaceHeader ++ localOptions ++
        String.intercalate "\n" declarations.toList ++ "\n" ++
        "end\n\nend Loom.GeneratedRelease.Lnp64u\n"
      writeIfChanged (output / ("ActionEvidenceBatch" ++ pad3 index ++ ".lean"))
        source
    let lastImport := if batches.isEmpty then
        "GeneratedRelease.Lnp64u.ActionEvidencePrelude"
      else "GeneratedRelease.Lnp64u.ActionEvidenceBatch" ++
        pad3 (batches.size - 1)
    let root := "-- Generated action evidence root; DO NOT EDIT.\n" ++
      "import " ++ lastImport ++ "\n\n" ++ namespaceHeader ++
      "theorem coreActionAccepted := " ++ rootBuild.evidence ++
        ".accepted\n\nend\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged (output / "ActionEvidenceRoot.lean") root
  else
    let source := imports ++ namespaceHeader ++ dataStructures ++ localOptions ++
      initialData ++ String.intercalate "\n" state.declarations.toList ++
      "\ntheorem coreActionAccepted := " ++ rootBuild.evidence ++
      ".accepted\n\nend\n\nend Loom.GeneratedRelease.Lnp64u\n"
    writeIfChanged output source
  return 0

private unsafe def generateCoreBranchProbe (runtime output : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let registers := design.regs.toArray
  let needed := List.range registers.size
  let initial := registers.map fun register =>
    Loom.Release.Symbolic.Ref.reg register.name
  let some refillCert := cert[0]? | return 1
  let refillNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs cert.tail needed
  let some refillResult := evaluateCert registers initial refillNeeded refillCert
    | return 1
  let some coreCert := cert[1]? | return 1
  IO.eprintln s!"core action certificate nodes={actionCertNodeCount coreCert}"
  let coreNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    (cert.drop 2) needed
  let (.ite summary _ _ thenCert _elseCert) := coreCert | return 1
  let changed := Loom.Release.Symbolic.ActionWide.changedOutputs summary coreNeeded
  let (.ite thenSummary _ _ retirementCert countdownCert) := thenCert | return 1
  let thenChanged := Loom.Release.Symbolic.ActionWide.changedOutputs
    thenSummary changed
  let some retirementResult := evaluateCert registers refillResult.refs
      thenChanged retirementCert | return 1
  let some countdownResult := evaluateCert registers refillResult.refs
      thenChanged countdownCert | return 1
  let source := "-- Generated core-branch segmentation probe; DO NOT EDIT.\n" ++
    "import GeneratedRelease.Lnp64u.ActionCert\n" ++
    "import GeneratedRelease.Lnp64u.SemanticRoot\n" ++
    "import Loom.Release.KernelDecide\n" ++
    "import Machines.Lnp64u.Hw.Core\n" ++
    "import Machines.Lnp64u.Hw.Demo\n\n" ++
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Release\n\n" ++
    "private abbrev design := Machines.Lnp64u.Hw.core " ++
      "Machines.Lnp64u.Demo.sysManifest\n" ++
    "noncomputable def coreInput : Array Symbolic.Ref := " ++
      Tools.ReleaseCertGen.actionWideRefsToLean refillResult.refs ++ "\n" ++
    "def coreNeeded : List Nat := [" ++
      String.intercalate ", " (coreNeeded.map toString) ++ "]\n" ++
    "def coreChanged : List Nat := [" ++
      String.intercalate ", " (changed.map toString) ++ "]\n" ++
    "def coreThenChanged : List Nat := [" ++
      String.intercalate ", " (thenChanged.map toString) ++ "]\n" ++
    "noncomputable def coreThenCert := " ++
      "Symbolic.ActionWide.ActionCert.iteThen actionCertNode15158\n" ++
    "noncomputable def coreElseCert := " ++
      "Symbolic.ActionWide.ActionCert.iteElse actionCertNode15158\n" ++
    "noncomputable def retirementCert := " ++
      "Symbolic.ActionWide.ActionCert.iteThen coreThenCert\n" ++
    "noncomputable def countdownCert := " ++
      "Symbolic.ActionWide.ActionCert.iteElse coreThenCert\n\n" ++
    "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\n" ++
    "theorem retirementAccepted :\n" ++
    "    Symbolic.ActionWide.runCheckedAction indexedWireTree wireTable " ++
      "design.regs.toArray\n" ++
    "      (Symbolic.ActionWide.iteThenAction " ++
      "(Symbolic.ActionWide.iteThenAction " ++
      "(Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest)))\n" ++
    "      coreInput coreThenChanged retirementCert = some " ++
      resultToLean retirementResult ++ " := kernel_decide\n\n" ++
    "theorem countdownAccepted :\n" ++
    "    Symbolic.ActionWide.runCheckedAction indexedWireTree wireTable " ++
      "design.regs.toArray\n" ++
    "      (Symbolic.ActionWide.iteElseAction " ++
      "(Symbolic.ActionWide.iteThenAction " ++
      "(Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest)))\n" ++
    "      coreInput coreThenChanged countdownCert = some " ++
      resultToLean countdownResult ++ " := kernel_decide\n\n" ++
    "end Loom.GeneratedRelease.Lnp64u\n"
  writeIfChanged output source
  return 0

set_option compiler.extract_closed false in
unsafe def main (args : List String) : IO UInt32 := do
  IO.eprintln "actionwidegen-start"
  match args with
  | ["acc8", runtime, output] =>
      generate (fun _ => Machines.Acc8.Core.design
          (Machines.Acc8.loadProg Machines.Acc8.golden))
        "Loom.GeneratedRelease.Acc8" runtime output
  | ["lnp64u", runtime, output] =>
      generate (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "Loom.GeneratedRelease.Lnp64u" runtime output
  | ["lnp64u-join-probe", runtime, output] =>
      generateJoinBlock (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "GeneratedRelease.Lnp64u.IndexedRoot" "Loom.GeneratedRelease.Lnp64u"
        "Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest"
        runtime output
  | ["lnp64u-join-probe", runtime, output, blockCount] =>
      let some blockCount := blockCount.toNat?
        | IO.eprintln "block count must be a natural number"; return 2
      generateJoinBlock (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "GeneratedRelease.Lnp64u.IndexedRoot" "Loom.GeneratedRelease.Lnp64u"
        "Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest"
        runtime output blockCount
  | ["lnp64u-local-join-probe", runtime, output, blockIndex] =>
      let some blockIndex := blockIndex.toNat?
        | IO.eprintln "block index must be a natural number"; return 2
      generateLocalJoinBlock runtime output blockIndex
  | ["lnp64u-local-joins", runtime, outputDir] =>
      generateLocalJoinBlocks runtime outputDir
  | ["lnp64u-named-cert", runtime, output] =>
      generateNamedCertificate runtime output
  | ["lnp64u-core-branch-probe", runtime, output] =>
      generateCoreBranchProbe runtime output
  | ["lnp64u-core-evidence", runtime, output] =>
      generateCoreEvidence runtime output
  | ["lnp64u-core-evidence-batches", runtime, outputDir] =>
      generateCoreEvidence runtime outputDir true
  | _ =>
      IO.eprintln "usage: actionwidegen {acc8|lnp64u} RUNTIME.json OUTPUT.lean"
      return 2
