-- Copyright (c) 2026 Kevin Baragona
-- SPDX-License-Identifier: Apache-2.0
import Tools.ReleaseCertGen
import Tools.RuntimeSsa
import Machines.Acc8.Core
import Machines.Acc8.Iss
import Machines.Lnp64u.Hw.Core
import Machines.Lnp64u.Hw.Demo

/-! Native untrusted generator for action-wide release certificates. -/

open Loom.Hw

private def writeIfChanged (path : System.FilePath) (contents : String) : IO Unit := do
  try
    if (← IO.FS.readFile path) == contents then return
  catch _ => pure ()
  if let some parent := path.parent then IO.FS.createDirAll parent
  IO.FS.writeFile path contents

private def source (namespaceName : String) (registers : List RegDecl) (cert :
    Loom.Release.Symbolic.ActionWide.RulesCert) : Option (String × String) := do
  let rendered ← Tools.ReleaseCertGen.actionWideRulesToLean registers cert
  let leanSource := "-- Generated by Tools.ActionWideGen; DO NOT EDIT.\n" ++
  "import Loom.Release.ActionWideRegister\n\n" ++
  "namespace " ++ namespaceName ++ "\n\n" ++
  "open Loom.Release\n\n" ++
  "def actionWideRegisterData : String :=\n" ++
  "  include_str \"ActionWideRegisterData.txt\"\n\n" ++
  "end " ++ namespaceName ++ "\n"
  pure (leanSource, rendered.data)

private unsafe def generate (makeDesign : Unit → Design) (namespaceName : String)
    (runtime output : System.FilePath) : IO UInt32 := do
  let started ← IO.monoMsNow
  let program ← Tools.RuntimeSsa.load runtime
  let loaded ← IO.monoMsNow
  IO.eprintln s!"runtime-load={loaded - started}ms"
  let design := makeDesign ()
  let designed ← IO.monoMsNow
  IO.eprintln s!"design={designed - loaded}ms"
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let generated ← IO.monoMsNow
  let some (contents, data) := source namespaceName design.regs cert
    | IO.eprintln "action-wide certificate encoding failed"; return 1
  let dataPath := output.parent.getD "." / "ActionWideRegisterData.txt"
  writeIfChanged dataPath data
  writeIfChanged output contents
  let written ← IO.monoMsNow
  IO.println (s!"runtime-load={loaded - started}ms " ++
    s!"design={designed - loaded}ms certificate={generated - designed}ms " ++
    s!"write={written - generated}ms")
  return 0

private def joinBlockSource (rootImport namespaceName designExpr : String)
    (fuel blockCount : Nat)
    (cert : Loom.Release.Symbolic.ActionWide.RulesCert) : String :=
  let joins := Tools.ReleaseCertGen.actionWideJoins cert
  let blocks := (List.range blockCount).map fun index =>
    joins.drop (index * 128) |>.take 128
  let declarations := String.intercalate "\n" <| blocks.zipIdx.map fun (block, index) =>
    "def joinProbe" ++ toString index ++
      " : List Symbolic.ActionWide.Join :=\n" ++
      Tools.ReleaseCertGen.actionWideJoinBlockToLean block ++ "\n\n" ++
    "theorem joinProbeAccepted" ++ toString index ++ " :\n" ++
      "    Symbolic.ActionWide.joinBlockMatchesFuel indexedWireTree wireTable\n" ++
      "      design.regs.toArray " ++ toString fuel ++ " joinProbe" ++
      toString index ++ " = true := kernel_decide\n"
  "-- Generated join-block feasibility probe; DO NOT EDIT.\n" ++
  "import " ++ rootImport ++ "\n" ++
  "import Loom.Release.ActionWideRegister\n" ++
  "import Loom.Release.KernelDecide\n" ++
  "import Machines.Lnp64u.Hw.Core\n" ++
  "import Machines.Lnp64u.Hw.Demo\n\n" ++
  "namespace " ++ namespaceName ++ "\n\n" ++
  "open Loom.Release\n\n" ++
  "private abbrev design := " ++ designExpr ++ "\n\n" ++
  "set_option maxRecDepth 1000000\n" ++
  "set_option maxHeartbeats 0\n\n" ++
  declarations ++ "\n" ++
  "end " ++ namespaceName ++ "\n"

private unsafe def generateJoinBlock (makeDesign : Unit → Design)
    (rootImport namespaceName designExpr : String)
    (runtime output : System.FilePath) (blockCount : Nat := 1) : IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := makeDesign ()
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let joins := Tools.ReleaseCertGen.actionWideJoins cert
  let joinCount := joins.length
  let perRule := cert.map fun rule => Tools.ReleaseCertGen.actionWideJoins [rule] |>.length
  let mut exact := 0
  let mut ordered := 0
  let mut previous : Option Nat := none
  for join in joins do
    match join.output with
    | .wire number =>
        if previous.all (· < number) then ordered := ordered + 1
        previous := some number
        if let some wire := program.wires[number]? then
          if let some (.mux guard yes no) := wire.rhs.toIndexed? then
            if guard == join.guard && yes == join.thenInput &&
                no == join.elseInput then
              exact := exact + 1
    | .reg _ => pure ()
  IO.eprintln s!"action-wide joins={joinCount}; emitting {blockCount} blocks"
  IO.eprintln s!"action-wide rules={cert.length}; joins/rule={perRule}"
  IO.eprintln s!"action-wide exact={exact}; monotonically-ordered={ordered}"
  writeIfChanged output (joinBlockSource rootImport namespaceName designExpr
    (program.wires.size + 1) blockCount cert)
  return 0

private def pad3 (number : Nat) : String :=
  let value := toString number
  if number < 10 then "00" ++ value
  else if number < 100 then "0" ++ value
  else value

private def pad4 (number : Nat) : String :=
  let value := toString number
  if number < 10 then "000" ++ value
  else if number < 100 then "00" ++ value
  else if number < 1000 then "0" ++ value
  else value

private def localJoinBlockSource (blockIndex : Nat)
    (joins : List Loom.Release.Symbolic.ActionWide.Join) : String :=
  let batchIndex := blockIndex / 4
  let suffix := pad4 blockIndex
  "-- Generated local join-block feasibility probe; DO NOT EDIT.\n" ++
  "import GeneratedRelease.Lnp64u.Batch" ++ pad3 batchIndex ++ "\n" ++
  "import Loom.Release.ActionWideJoin\n" ++
  "import Loom.Release.KernelDecide\n" ++
  "\n" ++
  "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
  "open Loom.Release\n\n" ++
  "set_option maxRecDepth 1000000\n\n" ++
  Tools.ReleaseCertGen.actionWideNamedJoinBlockToLean
    ("actionJoinBlock" ++ suffix) joins ++ "\n\n" ++
  "set_option maxRecDepth 1000000\n" ++
  "set_option maxHeartbeats 0\n\n" ++
  "theorem actionJoinBlockAccepted" ++ suffix ++ " :\n" ++
  "    Symbolic.ActionWide.localJoinBlockMatches " ++
    toString (blockIndex * 128) ++ " indexedWireBlock" ++
    suffix ++ " actionJoinBlock" ++ suffix ++
    " = true := kernel_decide\n\n" ++
  "end Loom.GeneratedRelease.Lnp64u\n"

private unsafe def generateLocalJoinBlock (runtime output : System.FilePath)
    (blockIndex : Nat) : IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let joins := (Tools.ReleaseCertGen.actionWideJoins cert).filter fun join =>
    match join.output with
    | .wire number => number / 128 == blockIndex
    | .reg _ => false
  IO.eprintln s!"local join block {blockIndex}: {joins.length} joins"
  writeIfChanged output (localJoinBlockSource blockIndex joins)
  return 0

private unsafe def generateLocalJoinBlocks (runtime outputDir : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let blockCount := (program.wires.size + 127) / 128
  let mut groups : Array (List Loom.Release.Symbolic.ActionWide.Join) :=
    Array.replicate blockCount []
  for join in Tools.ReleaseCertGen.actionWideJoins cert do
    if let .wire number := join.output then
      let blockIndex := number / 128
      if blockIndex < groups.size then
        groups := groups.modify blockIndex (join :: ·)
  IO.FS.createDirAll outputDir
  let mut emitted := 0
  let mut modules : List String := []
  for blockIndex in List.range groups.size do
    let joins := groups[blockIndex]!.reverse
    if !joins.isEmpty then
      let suffix := pad4 blockIndex
      let path := outputDir / s!"ActionJoinBlock{suffix}.lean"
      writeIfChanged path (localJoinBlockSource blockIndex joins)
      modules := s!"GeneratedRelease.Lnp64u.ActionJoinBlock{suffix}" :: modules
      emitted := emitted + 1
  writeIfChanged (outputDir / "action-join-modules.txt")
    (String.intercalate "\n" modules.reverse ++ "\n")
  IO.eprintln s!"emitted {emitted} nonempty local join blocks"
  return 0

private unsafe def generateNamedCertificate (runtime output : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let mut importedBlocks : Std.HashSet Nat := {}
  for join in Tools.ReleaseCertGen.actionWideJoins cert do
    if let .wire number := join.output then
      importedBlocks := importedBlocks.insert (number / 128)
  let imports := (List.range ((program.wires.size + 127) / 128)).filterMap
    fun blockIndex => if importedBlocks.contains blockIndex then
      some ("import GeneratedRelease.Lnp64u.ActionJoinBlock" ++ pad4 blockIndex)
    else none
  let source := "-- Generated bounded typed action certificate; DO NOT EDIT.\n" ++
    String.intercalate "\n" imports ++
    "\nimport Loom.Release.ActionWideRegister\n\n" ++
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Release\n\n" ++
    "set_option maxRecDepth 1000000\n\n" ++
    Tools.ReleaseCertGen.actionWideNamedCertificateToLean cert ++ "\n" ++
    "end Loom.GeneratedRelease.Lnp64u\n"
  writeIfChanged output source
  return 0

private def evaluateCert (registers : Array RegDecl) :
    Array Loom.Release.Symbolic.Ref → List Nat →
      Loom.Release.Symbolic.ActionWide.ActionCert →
      Option Loom.Release.Symbolic.ActionWide.Result
  | refs, _, .skip | refs, _, .memWrite =>
      some { refs, changed := [] }
  | refs, needed, .write index value =>
      if index ∉ needed then some { refs, changed := [] }
      else if index < refs.size then
        some { refs := refs.set! index value, changed := [index] }
      else none
  | refs, needed, .seq summary left right => do
      let leftNeeded := Loom.Release.Symbolic.ActionWide.neededInputs
        right.summary needed
      let leftResult ← evaluateCert registers refs leftNeeded left
      let rightResult ← evaluateCert registers leftResult.refs needed right
      pure { refs := rightResult.refs
             changed := Loom.Release.Symbolic.ActionWide.changedOutputs
               summary needed }
  | refs, needed, .ite summary _ joins thenCert elseCert => do
      let changed := Loom.Release.Symbolic.ActionWide.changedOutputs summary needed
      let thenResult ← evaluateCert registers refs changed thenCert
      let elseResult ← evaluateCert registers refs changed elseCert
      let mut output := refs
      if joins.length != changed.length then failure
      for (index, join) in changed.zip joins do
        let source ← registers[index]?
        guard (join.index == index && join.width == source.width)
        guard (thenResult.refs[index]?.isSome && elseResult.refs[index]?.isSome)
        output := output.set! index join.output
      pure { refs := output, changed }

private def resultToLean (result : Loom.Release.Symbolic.ActionWide.Result) :
    String :=
  "{ refs := " ++ Tools.ReleaseCertGen.actionWideRefsToLean result.refs ++
    ", changed := [" ++ String.intercalate ", "
      (result.changed.map toString) ++ "] }"

private unsafe def generateCoreBranchProbe (runtime output : System.FilePath) :
    IO UInt32 := do
  let program ← Tools.RuntimeSsa.load runtime
  let design := Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest
  let some cert := Tools.ReleaseCertGen.synthesizeActionWideRegisterCertRuntime
      design program
    | IO.eprintln "action-wide certificate synthesis failed"; return 1
  let registers := design.regs.toArray
  let needed := List.range registers.size
  let initial := registers.map fun register =>
    Loom.Release.Symbolic.Ref.reg register.name
  let some refillCert := cert[0]? | return 1
  let refillNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs cert.tail needed
  let some refillResult := evaluateCert registers initial refillNeeded refillCert
    | return 1
  let some coreCert := cert[1]? | return 1
  let coreNeeded := Loom.Release.Symbolic.ActionWide.neededRuleInputs
    (cert.drop 2) needed
  let (.ite summary _ _ thenCert elseCert) := coreCert | return 1
  let changed := Loom.Release.Symbolic.ActionWide.changedOutputs summary coreNeeded
  let some thenResult := evaluateCert registers refillResult.refs changed thenCert
    | return 1
  let some elseResult := evaluateCert registers refillResult.refs changed elseCert
    | return 1
  let source := "-- Generated core-branch segmentation probe; DO NOT EDIT.\n" ++
    "import GeneratedRelease.Lnp64u.ActionCert\n" ++
    "import GeneratedRelease.Lnp64u.SemanticRoot\n" ++
    "import Loom.Release.KernelDecide\n" ++
    "import Machines.Lnp64u.Hw.Core\n" ++
    "import Machines.Lnp64u.Hw.Demo\n\n" ++
    "namespace Loom.GeneratedRelease.Lnp64u\n\n" ++
    "open Loom.Release\n\n" ++
    "private abbrev design := Machines.Lnp64u.Hw.core " ++
      "Machines.Lnp64u.Demo.sysManifest\n" ++
    "noncomputable def coreInput : Array Symbolic.Ref := " ++
      Tools.ReleaseCertGen.actionWideRefsToLean refillResult.refs ++ "\n" ++
    "def coreNeeded : List Nat := [" ++
      String.intercalate ", " (coreNeeded.map toString) ++ "]\n" ++
    "def coreChanged : List Nat := [" ++
      String.intercalate ", " (changed.map toString) ++ "]\n" ++
    "noncomputable def coreThenCert := " ++
      "Symbolic.ActionWide.ActionCert.iteThen actionCertNode15158\n" ++
    "noncomputable def coreElseCert := " ++
      "Symbolic.ActionWide.ActionCert.iteElse actionCertNode15158\n\n" ++
    "set_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\n" ++
    "theorem coreThenAccepted :\n" ++
    "    Symbolic.ActionWide.runCheckedAction indexedWireTree wireTable " ++
      "design.regs.toArray\n" ++
    "      (Symbolic.ActionWide.iteThenAction " ++
      "(Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest))\n" ++
    "      coreInput coreChanged coreThenCert = some " ++
      resultToLean thenResult ++ " := kernel_decide\n\n" ++
    "theorem coreElseAccepted :\n" ++
    "    Symbolic.ActionWide.runCheckedAction indexedWireTree wireTable " ++
      "design.regs.toArray\n" ++
    "      (Symbolic.ActionWide.iteElseAction " ++
      "(Machines.Lnp64u.Hw.coreAct Machines.Lnp64u.Demo.sysManifest))\n" ++
    "      coreInput coreChanged coreElseCert = some " ++
      resultToLean elseResult ++ " := kernel_decide\n\n" ++
    "end Loom.GeneratedRelease.Lnp64u\n"
  writeIfChanged output source
  return 0

set_option compiler.extract_closed false in
unsafe def main (args : List String) : IO UInt32 := do
  IO.eprintln "actionwidegen-start"
  match args with
  | ["acc8", runtime, output] =>
      generate (fun _ => Machines.Acc8.Core.design
          (Machines.Acc8.loadProg Machines.Acc8.golden))
        "Loom.GeneratedRelease.Acc8" runtime output
  | ["lnp64u", runtime, output] =>
      generate (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "Loom.GeneratedRelease.Lnp64u" runtime output
  | ["lnp64u-join-probe", runtime, output] =>
      generateJoinBlock (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "GeneratedRelease.Lnp64u.IndexedRoot" "Loom.GeneratedRelease.Lnp64u"
        "Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest"
        runtime output
  | ["lnp64u-join-probe", runtime, output, blockCount] =>
      let some blockCount := blockCount.toNat?
        | IO.eprintln "block count must be a natural number"; return 2
      generateJoinBlock (fun _ =>
          Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest)
        "GeneratedRelease.Lnp64u.IndexedRoot" "Loom.GeneratedRelease.Lnp64u"
        "Machines.Lnp64u.Hw.core Machines.Lnp64u.Demo.sysManifest"
        runtime output blockCount
  | ["lnp64u-local-join-probe", runtime, output, blockIndex] =>
      let some blockIndex := blockIndex.toNat?
        | IO.eprintln "block index must be a natural number"; return 2
      generateLocalJoinBlock runtime output blockIndex
  | ["lnp64u-local-joins", runtime, outputDir] =>
      generateLocalJoinBlocks runtime outputDir
  | ["lnp64u-named-cert", runtime, output] =>
      generateNamedCertificate runtime output
  | ["lnp64u-core-branch-probe", runtime, output] =>
      generateCoreBranchProbe runtime output
  | _ =>
      IO.eprintln "usage: actionwidegen {acc8|lnp64u} RUNTIME.json OUTPUT.lean"
      return 2
